export type InterestLevel='curious'|'interested'|'actively_learning'|'deep_interest';
export type InterestStatus='active'|'paused'|'archived';
export type InterestType='interest'|'skill'|'goal'|'project';
export interface InterestResource{title:string;type:'book'|'video'|'website'|'course'|'paper'|'link';url:string;notes?:string}
export interface Interest{ id:string;name:string;category:string;icon?:string;description?:string;priority:number;interestLevel:InterestLevel;knowledgeLevel:number;status:InterestStatus;tags:string[];relatedInterests:string[];dailyKnowledgeEnabled:boolean;dailyTaskEnabled:boolean;frontierUpdateEnabled:boolean;learningGoals:string[];resources:InterestResource[];notes:string;whyInterested?:string;subtopics?:string[];learningPath?:string[];explorationLog?:Array<{date:string;learned:string;discovery:string;question:string}>;createdAt:string;updatedAt:string;lastExploredAt?:string;leisure?:boolean;types:InterestType[]}
const now='2026-08-28T00:00:00.000Z';
const item=(id:string,name:string,category:string,priority:number,types:InterestType[]=['interest'],relatedInterests:string[]=[],interestLevel:InterestLevel=priority>=85?'actively_learning':'interested'):Interest=>({id,name,category,priority,interestLevel,knowledgeLevel:0,status:'active',tags:[],relatedInterests,dailyKnowledgeEnabled:priority>=65,dailyTaskEnabled:priority>=75,frontierUpdateEnabled:priority>=85,learningGoals:[],resources:[],notes:'',subtopics:[],learningPath:['入门','基础','进阶','深入'],explorationLog:[],createdAt:now,updatedAt:now,types});
export const profileInterests:Interest[]=[
item('interest-neuroscience','Neuroscience','Science & Research',95,['interest'],['Computational Neuroscience','BCI']),item('interest-computational-neuroscience','Computational Neuroscience','Science & Research',100,['interest'],['Neuroscience','Computational Modelling']),item('interest-computational-cognitive-neuroscience','Computational Cognitive Neuroscience','Science & Research',92,['interest'],['Computational Neuroscience','Decision Making']),item('interest-computational-psychiatry','Computational Psychiatry','Science & Research',90,['interest'],['Computational Neuroscience','Decision Making']),item('interest-decision-making','Decision Making','Science & Research',92,['interest'],['Metacognition','Agency']),item('interest-metacognition','Metacognition','Science & Research',90,['interest'],['Decision Making','Confidence']),item('interest-agency','Agency','Science & Research',88,['interest'],['Sense of Agency','Controllability']),item('interest-sense-agency','Sense of Agency','Science & Research',88,['interest'],['Agency','Controllability']),item('interest-controllability','Controllability','Science & Research',85,['interest'],['Sense of Agency','Flow']),item('interest-bci','BCI','Science & Research',88,['interest'],['EEG','Neural Decoding','AI']),item('interest-ai','AI','Science & Research',88,['interest','skill'],['Machine Learning','Neural Decoding']),item('interest-machine-learning','Machine Learning','Science & Research',90,['interest','skill'],['AI','Computational Modelling']),item('interest-computational-modelling','Computational Modelling','Technology',95,['interest','skill'],['Statistics','Python','Computational Neuroscience']),item('interest-research','Research','Science & Research',95,['interest','goal'],['Scientific Reading','Experimental Design']),
item('interest-tcm','中医','Traditional Culture & Esoterica',55),item('interest-yijing','易经','Traditional Culture & Esoterica',55,['interest'],['中医','相术']),item('interest-face-reading','相术','Traditional Culture & Esoterica',40,['interest'],['易经']),item('interest-tarot','塔罗牌','Traditional Culture & Esoterica',35),item('interest-management','管理','Business & Management',55),item('interest-entrepreneurship','创业','Business & Management',55,['interest','goal'],['商业模式']),item('interest-business-model','商业模式','Business & Management',50),item('interest-leadership','领导力','Business & Management',45),item('interest-video-editing','剪辑','Creative & Media',58,['interest','skill'],['摄影','内容创作']),item('interest-photography','摄影','Creative & Media',50,['interest','skill'],['剪辑','内容创作']),item('interest-content','内容创作','Creative & Media',50),
item('interest-music','音乐','Music',48),item('interest-trombone','长号','Music',42,['interest','skill'],['音乐','管弦乐']),item('interest-vocal','声乐','Music',38,['interest','skill'],['音乐','歌剧']),item('interest-classical','古典音乐','Music',42),item('interest-orchestra','管弦乐','Music',35),item('interest-opera','歌剧','Music',32),item('interest-python','Python','Technology',85,['interest','skill'],['数据分析','AI','Computational Modelling']),item('interest-ai-tools','AI Tools','Technology',75,['interest','skill'],['AI','自动化']),item('interest-app-development','App Development','Technology',65,['interest','skill']),item('interest-automation','自动化','Technology',60,['interest','skill']),item('interest-github','GitHub','Technology',60,['interest','skill']),item('interest-data-analysis','数据分析','Technology',82,['interest','skill'],['Statistics','Python']),
item('interest-fitness','健身','Life & Experience',52),item('interest-cooking','烹饪','Life & Experience',45),item('interest-coffee','咖啡','Life & Experience',42),item('interest-tea','茶','Life & Experience',38),item('interest-cocktails','鸡尾酒','Life & Experience',35),item('interest-bar','酒吧文化','Life & Experience',30),item('interest-travel','旅行','Life & Experience',50),item('interest-food','美食','Life & Experience',48),item('interest-pokemon','Pokémon','Entertainment',35),item('interest-rpg','RPG','Entertainment',35),item('interest-games','电子游戏','Entertainment',35),item('interest-game-builds','游戏机制与 Build 研究','Entertainment',38)
];
