export type QuestType='DAILY'|'WEEKLY'|'CHALLENGE'|'PROMOTION'|'BOSS';
export type AreaArchetype='RESEARCH'|'TECHNICAL'|'LANGUAGE'|'CREATIVE'|'MUSIC'|'BUSINESS'|'PRACTICAL'|'CULTURE'|'FITNESS'|'GAME_ANALYSIS';
export type EvidenceType='TEXT'|'NOTE'|'PHOTO'|'VIDEO'|'AUDIO'|'CODE'|'FILE'|'LINK'|'DATASET'|'CHECKLIST'|'REFLECTION'|'NONE';
export type Rank=1|2|3|4|5|6|7|8;
export type UnlockConditionType='QUEST_COUNT'|'QUEST_FAMILY_COUNT'|'CONCEPT_MASTERY'|'SKILL_LEVEL'|'TIME_SPENT'|'PROJECT_COMPLETE'|'RESOURCE_READ'|'PAPER_READ'|'CHAIN_COMPLETE'|'OUTPUT_SUBMITTED';
export interface UnlockCondition{type:UnlockConditionType;value:number;questType?:QuestType;familyIds?:string[];label:string}
export interface QuestFamily{id:string;name:string;description:string;area:string;archetype:AreaArchetype;chainOrder?:string[]}
export interface QuestVariant{id:string;familyId:string;rank:Rank;type:QuestType;title:string;description:string;parameters?:Record<string,string|number>;acceptanceCriteria:string[];evidenceType:EvidenceType;minutes:number;difficulty:1|2|3|4|5;cooldownDays:number;weight:number;prerequisites:string[];unlockConditions:UnlockCondition[];repeatRewardMultiplier:number;domainSpecific:boolean}
export interface Quest{ id:string;variantId?:string;familyId?:string;archetype?:AreaArchetype;rank?:Rank;title:string;description:string;type:QuestType;targetId:string;targetName:string;acceptanceCriteria?:string[];evidenceType?:EvidenceType;unlockConditions?:UnlockCondition[];parameters?:Record<string,string|number>;minutes:number;difficulty:1|2|3|4|5;prerequisites?:string[];cooldownDays?:number;weight?:number;repeatRewardMultiplier?:number;evidence?:string;pinned?:boolean;locked?:boolean;status:'available'|'accepted'|'completed'|'skipped';createdAt:string;completedAt?:string;source?:'generated'|'imported'|'legacy' }
export interface AreaRank{targetId:string;targetName:string;rank:number;dailyCompleted:number;weeklyCompleted:number;promotionUnlocked:boolean;promotionCompleted:boolean;familyProgress?:Record<string,{completed:number;lastCompletedAt?:string}>}
export const rankNames=['Discovery','Foundation','Understanding','Application','Analysis','Synthesis','Independent','Original'];

const slug=(value:string)=>value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9\u4e00-\u9fff]+/g,'-').replace(/^-|-$/g,'');
export function resolveQuestDomain(name:string){const n=name.trim().toLowerCase();if(/japanese|日本語|日语/.test(n))return'language.japanese';if(/russian|русский|俄语/.test(n))return'language.russian';if(/bci|brain.?computer|neural interface/.test(n))return'research.bci';if(/agency/.test(n))return'research.agency';if(/ai|machine learning/.test(n))return'technical.ai';return slug(name)}
export function inferArchetype(name:string):AreaArchetype{const n=name.toLowerCase();if(/japanese|russian|language|日语|俄语/.test(n))return'LANGUAGE';if(/fitness|gym|running|健身/.test(n))return'FITNESS';if(/music|vocal|trombone|音乐|声乐/.test(n))return'MUSIC';if(/photo|video|creative|摄影|剪辑|创作/.test(n))return'CREATIVE';if(/business|product|startup|management|商业|创业|管理/.test(n))return'BUSINESS';if(/game|pokemon|rpg|游戏/.test(n))return'GAME_ANALYSIS';if(/python|github|app|program|signal processing|machine learning|ai\b/.test(n))return'TECHNICAL';if(/culture|philosophy|易经|中医|塔罗|文化/.test(n))return'CULTURE';if(/cooking|coffee|tea|travel|烹饪|咖啡|茶|旅行/.test(n))return'PRACTICAL';return'RESEARCH'}

const familySets:Record<AreaArchetype,string[]>={
 RESEARCH:['Core Concepts','Paper Reading','Methods','Measurement','Data Analysis','Computational Models','Experimental Design','Theory Building'],
 TECHNICAL:['Foundations','Tooling','Implementation','Debugging','Testing','Systems Design','Documentation','Projects'],
 LANGUAGE:['Vocabulary','Grammar','Listening','Speaking','Reading','Writing','Pronunciation','Culture'],
 CREATIVE:['Technique','Visual Analysis','Ideation','Creation','Editing','Storytelling','Portfolio','External Feedback'],
 MUSIC:['Technique','Ear Training','Theory','Sight Reading','Repertoire','Performance','Recording','Reflection'],
 BUSINESS:['Problem Validation','Customer Interviews','Market Research','MVP','User Testing','Metrics','Revenue','Strategy'],
 PRACTICAL:['Foundations','Materials','Technique','Practice','Quality Control','Planning','Service','Personal System'],
 CULTURE:['Core Concepts','Primary Sources','Historical Context','Interpretation','Comparison','Critique','Application','Synthesis'],
 FITNESS:['Technique','Consistency','Strength','Conditioning','Mobility','Recovery','Training Plan','Performance'],
 GAME_ANALYSIS:['Mechanics','Systems','Strategy','Builds','Decision Review','Metagame','Testing','Guide Creation']
};
const specialFamilies:Record<string,string[]>={
 'research.bci':['EEG Foundations','BCI Paradigms','Signal Processing','Neural Decoding','Paper Reading','Experimental Design','Clinical Applications'],
 'research.agency':['Core Concepts','Paradigms','Measurement','Experimental Design','Paper Reading','Computational Models','Theory Building'],
 'language.japanese':['Vocabulary','Grammar','Listening','Speaking','Reading','Writing','Kana','Kanji','Culture'],
 'language.russian':['Vocabulary','Grammar','Listening','Speaking','Reading','Writing','Cyrillic','Cases','Culture'],
 'technical.ai':['ML Foundations','Data Preparation','Model Training','Evaluation','Implementation','Paper Reading','Responsible AI','Projects']
};
export function questFamilies(area:string):QuestFamily[]{const archetype=inferArchetype(area);return(specialFamilies[resolveQuestDomain(area)]||familySets[archetype]).map((name,index)=>({id:`${slug(area)}-${slug(name)}`,name,description:`Build ${name.toLowerCase()} capability in ${area}.`,area,archetype,chainOrder:index<6?[`R${Math.max(1,index)}`,`R${Math.min(8,index+1)}`]:undefined}))}

const typeForRank=(rank:Rank):QuestType=>rank<=3?'DAILY':rank<=5?'WEEKLY':rank===6?'CHALLENGE':rank===7?'PROMOTION':'BOSS';
const evidenceFor=(type:QuestType,archetype:AreaArchetype):EvidenceType=>type==='DAILY'?'NOTE':archetype==='LANGUAGE'?'AUDIO':archetype==='TECHNICAL'?'CODE':archetype==='FITNESS'?'VIDEO':type==='BOSS'?'FILE':'REFLECTION';
const rankVerb=['identify','explain','distinguish','apply','analyse','integrate','work independently with','create an original contribution using'];
function copyFor(area:string,family:string,rank:Rank,archetype:AreaArchetype){const verb=rankVerb[rank-1];const subject=`${family.toLowerCase()} in ${area}`;const output=rank<=2?'a 3-point note':rank===3?'a worked comparison':rank===4?'a completed exercise with annotated steps':rank===5?'an evidence-based critique':rank===6?'an integrated mini-project':rank===7?'an independently produced artifact':'an original, shareable capstone';let title=`${verb[0].toUpperCase()+verb.slice(1)} ${subject}`;let description=`${verb[0].toUpperCase()+verb.slice(1)} ${subject} and produce ${output}.`;
 if(resolveQuestDomain(area)==='research.bci'&&family==='Signal Processing'&&rank===4){title='Filter and inspect one EEG channel';description='Load one EEG channel, apply a 1–40 Hz band-pass filter, plot before/after traces, and explain why the filter was used.'}
 if(family==='Paper Reading'){const steps=['Read an abstract and identify the research question','Identify a paper’s hypothesis and variables','Analyse one figure independently','Critique a paper’s Methods','Compare a paper with a competing explanation','Integrate three papers into one evidence map','Identify a theoretical weakness and propose a discriminating experiment','Turn a paper synthesis into an independent research question'];title=steps[rank-1];description=`Use one ${area} paper and produce a reviewable ${output}.`}
 if(archetype==='LANGUAGE'&&family==='Speaking'){title=rank<=2?`Record ${rank*3} sentences in ${area}`:`Complete a ${Math.min(15,rank*2)}-minute ${area} speaking task`;description=`Speak without reading a full script, then note one pronunciation or fluency improvement.`}
 if(resolveQuestDomain(area)==='language.japanese'&&family==='Kana'){title=rank===1?'Read and write one hiragana row from memory':`Use kana accurately in ${rank*2} words`;description='Read the symbols aloud, write them without copying, and mark any confusion.'}
 if(resolveQuestDomain(area)==='language.russian'&&family==='Cyrillic'){title=rank===1?'Read and write five Cyrillic letters from memory':`Read a Cyrillic passage at R${rank} level`;description='Read aloud, transcribe the target text, and mark pronunciation errors.'}
 return{title,description,output}}
export function questVariants(area:string,rank:Rank=1):QuestVariant[]{const archetype=inferArchetype(area);return questFamilies(area).flatMap((family,familyIndex)=>{const ranks=([rank,Math.min(8,rank+1)] as Rank[]).filter((v,i,a)=>a.indexOf(v)===i);return ranks.map(r=>{const type=typeForRank(r);const copy=copyFor(area,family.name,r,archetype);const id=`${family.id}-r${r}`;return{id,familyId:family.id,rank:r,type,title:copy.title,description:copy.description,acceptanceCriteria:[`Target is specific to ${area}`,`Action is completed and ${copy.output} is saved`,r>=4?'Method or process is documented':'One takeaway is written',r>=7?'Output is independently reviewable':'Done condition is checked'],evidenceType:evidenceFor(type,archetype),minutes:type==='DAILY'?10:type==='WEEKLY'?60:type==='CHALLENGE'?90:type==='PROMOTION'?120:240,difficulty:Math.min(5,Math.ceil(r/2)) as 1|2|3|4|5,cooldownDays:type==='DAILY'?3:14,weight:Math.max(1,9-familyIndex),prerequisites:r>1?[`${family.id}-r${r-1}`]:[],unlockConditions:r===7?promotionRequirements(archetype):[],repeatRewardMultiplier:type==='DAILY'?.5:.25,domainSpecific:family.name!=='Core Concepts'}})})}
export function promotionRequirements(archetype:AreaArchetype):UnlockCondition[]{const shared:UnlockCondition[]=[{type:'QUEST_COUNT',questType:'DAILY',value:8,label:'Complete 8 Daily quests'},{type:'QUEST_COUNT',questType:'WEEKLY',value:2,label:'Complete 2 Weekly quests'},{type:'QUEST_FAMILY_COUNT',value:4,label:'Practise 4 different Quest Families'}];const mastery:Record<AreaArchetype,UnlockCondition>={RESEARCH:{type:'PAPER_READ',value:3,label:'Read 3 papers with notes'},TECHNICAL:{type:'PROJECT_COMPLETE',value:1,label:'Complete one working project'},LANGUAGE:{type:'OUTPUT_SUBMITTED',value:2,label:'Submit speaking and writing evidence'},CREATIVE:{type:'OUTPUT_SUBMITTED',value:3,label:'Add 3 reviewed portfolio pieces'},MUSIC:{type:'OUTPUT_SUBMITTED',value:2,label:'Submit one performance and one recording'},BUSINESS:{type:'OUTPUT_SUBMITTED',value:3,label:'Record customer, MVP, and metric evidence'},PRACTICAL:{type:'SKILL_LEVEL',value:3,label:'Demonstrate repeatable technique'},CULTURE:{type:'RESOURCE_READ',value:3,label:'Analyse 3 primary sources'},FITNESS:{type:'TIME_SPENT',value:300,label:'Log 300 minutes with recovery'},GAME_ANALYSIS:{type:'OUTPUT_SUBMITTED',value:2,label:'Submit analysis and tested guide'}};return[...shared,mastery[archetype]]}
export function requirementsMet(conditions:UnlockCondition[],quests:Quest[]){const completed=quests.filter(q=>q.status==='completed');return conditions.every(c=>c.type==='QUEST_COUNT'?completed.filter(q=>!c.questType||q.type===c.questType).length>=c.value:c.type==='QUEST_FAMILY_COUNT'?new Set(completed.map(q=>q.familyId).filter(Boolean)).size>=c.value:c.type==='TIME_SPENT'?completed.reduce((n,q)=>n+q.minutes,0)>=c.value:completed.filter(q=>q.evidence?.trim()).length>=Math.min(c.value,completed.length||c.value))}
export function familyCoverage(quests:Quest[],families:QuestFamily[]){return Object.fromEntries(families.map(f=>{const done=quests.filter(q=>q.familyId===f.id&&q.status==='completed');return[f.id,{completed:done.length,lastCompletedAt:done.sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)))[0]?.completedAt}]}))}
export function scoreQuestVariant(variant:QuestVariant,history:Quest[],context:{priority?:number;availableMinutes?:number;projectTerms?:string[]}={}){const familyDone=history.filter(q=>q.familyId===variant.familyId&&q.status==='completed');const recent=familyDone.filter(q=>Date.now()-new Date(q.completedAt||q.createdAt).getTime()<14*864e5).length;const duplicate=history.some(q=>q.variantId===variant.id&&Date.now()-new Date(q.completedAt||q.createdAt).getTime()<variant.cooldownDays*864e5);const timeFit=context.availableMinutes?Math.max(0,5-Math.abs(context.availableMinutes-variant.minutes)/15):2;const project=(context.projectTerms||[]).some(term=>(variant.title+' '+variant.description).toLowerCase().includes(term.toLowerCase()))?3:0;return(context.priority||1)*2+(8-familyDone.length*1.5)+(4-recent)+timeFit+project+(duplicate?-100:0)+variant.weight*.1}
export function selectBalancedVariants(variants:QuestVariant[],history:Quest[],count:number,context:Parameters<typeof scoreQuestVariant>[2]={}){const selected:QuestVariant[]=[];for(const candidate of [...variants].sort((a,b)=>scoreQuestVariant(b,history,context)-scoreQuestVariant(a,history,context))){if(selected.length>=count)break;if(selected.some(x=>x.familyId===candidate.familyId))continue;selected.push(candidate)}return selected}
export function makeQuest(variant:QuestVariant,targetId:string,targetName:string):Quest{return{id:`quest-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,variantId:variant.id,familyId:variant.familyId,archetype:inferArchetype(targetName),rank:variant.rank,title:variant.title,description:variant.description,type:variant.type,targetId,targetName,acceptanceCriteria:variant.acceptanceCriteria,evidenceType:variant.evidenceType,unlockConditions:variant.unlockConditions,parameters:variant.parameters,minutes:variant.minutes,difficulty:variant.difficulty,prerequisites:variant.prerequisites,cooldownDays:variant.cooldownDays,weight:variant.weight,repeatRewardMultiplier:variant.repeatRewardMultiplier,locked:!requirementsMet(variant.unlockConditions,[]),status:'available',createdAt:new Date().toISOString(),source:'generated'}}
export function migrateQuest(quest:any):Quest{const area=String(quest.targetName||quest.area||'Legacy / General');const family=quest.familyId||questFamilies(area).find(f=>quest.title?.toLowerCase().includes(f.name.toLowerCase().split(' ')[0]))?.id||`${slug(area)}-legacy-general`;return{...quest,id:String(quest.id||`legacy-${Date.now()}-${Math.random()}`),title:String(quest.title||'Legacy quest'),description:String(quest.description||''),type:(['DAILY','WEEKLY','CHALLENGE','PROMOTION','BOSS'].includes(quest.type)?quest.type:'DAILY') as QuestType,targetId:String(quest.targetId||`legacy-${slug(area)}`),targetName:area,familyId:family,archetype:quest.archetype||inferArchetype(area),rank:(Math.max(1,Math.min(8,Number(quest.rank||quest.stage||1))) as Rank),acceptanceCriteria:quest.acceptanceCriteria||['Preserved legacy completion record'],evidenceType:quest.evidenceType||'NOTE',status:quest.status||'available',createdAt:quest.createdAt||new Date().toISOString(),source:quest.source||'legacy'}}
export const questTemplates=(area:string)=>questVariants(area,1);
export const defaultQuestPool=questVariants('BCI',1).map(v=>({...v,area:'BCI'}));
export const prerequisitesMet=(quest:Quest,completed:Quest[])=>!quest.prerequisites?.length||quest.prerequisites.every(id=>completed.some(q=>q.variantId===id||q.id===id));
export function weightedSample<T extends{weight?:number}>(items:T[],count:number){return [...items].sort((a,b)=>(b.weight||1)-(a.weight||1)).slice(0,count)}
