export type QuestType='DAILY'|'WEEKLY'|'PRACTICE'|'LEARNING'|'EXPLORATION'|'RESEARCH'|'CREATIVE'|'CHALLENGE'|'PROMOTION'|'CAPSTONE'|'BOSS'|'CUSTOM';
export interface Quest{ id:string; title:string; description:string; type:QuestType; targetId:string; targetName:string; minutes:number; difficulty:1|2|3|4|5; prerequisites?:string[]; cooldownDays?:number; weight?:number; weekKey?:string; evidence?:string; pinned?:boolean; status:'available'|'accepted'|'completed'|'skipped'; createdAt:string; completedAt?:string; source?:'generated'|'imported' }
export interface AreaRank{ targetId:string; targetName:string; rank:number; dailyCompleted:number; weeklyCompleted:number; promotionUnlocked:boolean; promotionCompleted:boolean }
export const rankNames=['Initiate','Beginner','Developing','Intermediate','Advanced','High Rank','Master Rank','Expert'];
export const questSeedAreas=[
 ...['Neuroscience','Computational Neuroscience','Computational Cognitive Neuroscience','Computational Psychiatry','Decision Making','Metacognition','Agency','Sense of Agency','Controllability','BCI','AI','Machine Learning','Research','Confidence','Attention','Boredom','Flow','Curiosity','EEG','Neural Decoding','Reinforcement Learning','Bayesian Models','Neural Interfaces'],
 ...['Computational Modelling','Python','AI Tools','App Development','GitHub','Signal Processing','自动化','数据分析'],
 ...['Product Thinking','管理','创业','商业模式','领导力','团队管理','市场与增长','产品思维'],
 ...['剪辑','摄影','内容创作','视觉叙事','视频制作'],
 ...['音乐','长号','声乐','古典音乐','管弦乐','歌剧','音乐制作','编曲'],
 ...['健身','烹饪','咖啡','茶','鸡尾酒','酒吧文化','旅行','美食'],
 ...['中医','易经','相术','塔罗牌','中国哲学'],
 ...['AI / Machine Learning','AI 工具','App 开发','Neural Interfaces'],
 ...['Pokémon','RPG','电子游戏','游戏机制与 Build 研究']
];
const seedDaily=['定义一个核心概念，并写出机制与例子','读一篇摘要，用一句话写出研究问题','只看一张图，解释坐标、条件与结论','写3个主动回忆问题并闭卷回答','比较两个易混概念','找一个经典研究并说明影响','找一个近12个月研究并记录新意','提出一个可证伪假设与预测','识别一个混淆变量或替代解释','画一张5节点概念图','解释一种常用测量或分析方法','检查一项证据的样本与推断边界','把生活现象转成研究问题','提出一个后续实验','用100字总结今天最值得保留的知识'];
const seedWeekly=['完成一次60–90分钟专题学习并输出一页笔记','完成一个可展示的小项目或实践样品','比较至少3个来源/范例并写综合结论','向他人讲解或演示，并记录反馈','做一次闭卷复盘或技能测评','整理本周证据、错误与下周改进计划'];
const seedChallenge=['连续7天完成最小练习并保留证据','在限定90分钟内从零完成一个小成果','选择一个陌生子主题，产出结构化入门指南','接受一次外部反馈并完成可见修订'];
const seedPromotion=['12次Daily + 2次Weekly，并完成一次闭卷解释','20次Daily + 4次Weekly + 1次Challenge，并提交作品','30次Daily + 6次Weekly + 2次Challenge，完成方法比较','40次Daily + 8次Weekly，完成端到端真实项目','完成跨领域项目并进行正式展示','形成个人方法论、旗舰成果并指导他人'];
const seedBoss=['解决一个真实问题的端到端项目','作品集或研究档案与正式答辩'];
const domainPack=(name:string,daily:string[],weekly:string[],challenge:string[],promotion:string[],boss:string[])=>[...daily.map(title=>({title:`${title}：${name}`,description:`围绕 ${name} 完成这项实践。`,type:'DAILY' as const,minutes:20,difficulty:1 as const})),...weekly.map(title=>({title:`${title}：${name}`,description:`完成后保留可复查记录。`,type:'WEEKLY' as const,minutes:60,difficulty:3 as const})),...challenge.map(title=>({title:`${title}：${name}`,description:'记录过程、结果和下一步调整。',type:'CHALLENGE' as const,minutes:60,difficulty:4 as const})),...promotion.map((title,index)=>({title:`晋级任务 R${index+1}：${name}`,description:title,type:'PROMOTION' as const,minutes:90,difficulty:4 as const})),...boss.map(title=>({title:`Boss Quest：${title} · ${name}`,description:'完成一个可展示的综合成果。',type:'BOSS' as const,minutes:180,difficulty:5 as const}))];
const creativeDaily=['拍摄一个主题并保留 3 张精选照片','练习一个构图或用光方法','剪辑一段 30 秒短片并完成一次修改','分析一个喜欢的作品并写出叙事结构','完成一次素材整理与命名','用不同视角记录同一个对象'];
const creativeWeekly=['完成一个小型摄影或剪辑作品','模仿一个参考作品并写出差异','整理一页自己的创作流程','获得一次反馈并完成修改'];
const creativeChallenge=['连续 7 天完成一次创作练习','在 90 分钟内完成一个可发布作品','使用限制条件完成一次创作','建立一个可展示的作品页面'];
const creativePromotion=['完成一个主题作品系列','连续 4 周保持创作并整理过程','形成自己的视觉或叙事风格'];
const creativeBoss=['完成一个完整作品集并公开展示','策划并完成一次主题创作项目'];
const experienceDaily=['认识一个基础概念并做一次实际体验','记录一次体验的步骤、感受和结果','比较两种方法或材料的差异','完成一次 20 分钟主题练习','整理一个可复用的小技巧','为下一次体验提出一个问题'];
const experienceWeekly=['完成一次主题体验并写一页记录','比较至少三种选择并总结偏好','邀请他人参与并记录反馈','整理一份自己的体验清单'];
const experienceChallenge=['连续 7 天完成最小体验练习','在限定预算内完成一次主题体验','从零设计并完成一次体验流程','复现一次满意的结果'];
const experiencePromotion=['建立个人体验档案','完成一个月记录并总结偏好','形成自己的选择与复盘方法'];
const experienceBoss=['策划并完成一次完整主题体验','制作一份可分享的个人指南'];
const techDaily=['完成一个小功能或自动化步骤','阅读一个工具文档并实际试用','记录一次操作的输入、输出与问题','比较两个工具或方案','修复一个小问题并写下原因','把一个重复动作变成可复用流程'];
const techWeekly=['完成一个可运行的小项目','整理一页工具或开发笔记','比较三种方案并选择一个实现','向他人演示并记录反馈'];
const techChallenge=['连续 7 天完成最小实践','在 90 分钟内完成一个可运行原型','从零复现一个功能并记录步骤','解决一个真实的小问题'];
const techPromotion=['完成一个可展示的工具项目','建立个人工作流并连续使用一个月','形成一份可复用的技术指南'];
const techBoss=['完成一个端到端应用或自动化项目','发布一个可被他人使用的作品'];
const gameDaily=['分析一个机制并举出实际例子','研究一个角色、卡组或 Build 的选择','完成一次游戏并记录决策过程','比较两种策略的优缺点','整理一个术语或系统说明','复盘一次失败并提出改进方案'];
const gameWeekly=['完成一次系统化 Build 或机制研究','比较三个方案并写出选择依据','向他人解释一个游戏系统','整理一页自己的攻略或研究笔记'];
const gameChallenge=['连续 7 天记录一次游戏决策','在限制条件下完成一个 Build','从零制作一份入门指南','接受一次实战验证并修改方案'];
const gamePromotion=['完成一个系统性游戏研究档案','形成自己的 Build 分析方法','完成一次可分享的攻略作品'];
const gameBoss=['完成一份完整机制或 Build 研究报告','策划并完成一个可展示的游戏项目'];
const domainTemplates:Record<string,ReturnType<typeof domainPack>>={
 '健身':domainPack('健身',['完成一次力量或有氧训练','练习一个动作并记录关键要点','完成 20 分钟灵活性训练','记录今天的训练重量、次数或心率','安排一次主动恢复或拉伸','完成一次热身并观察身体状态'],['制定一周训练计划并执行至少三次','记录一次训练表现并找出一个改进点','比较两种训练方式对身体状态的影响','完成一次训练后复盘睡眠、饮食与恢复'],['连续 7 天完成最小运动量','在 45 分钟内完成一次完整训练并记录数据','学习一个动作的正确形式并拍下自我检查记录','完成一次体能测试并制定下阶段目标'],['连续 4 周保持训练计划并提交记录','完成一次个人体能指标对比','建立适合自己的训练与恢复流程'],['完成一个 8 周训练周期并总结变化','形成可持续的个人健身计划并执行展示']),
 '茶':domainPack('茶',['认识一种茶的产地、工艺和风味','用同一种茶尝试两种冲泡参数','记录一次品饮的香气、滋味和回甘','比较两种茶的外形与口感','整理一个茶类的基本分类','为今天的茶写一段品鉴笔记'],['完成一次三种茶的对比品饮','整理一页自己的冲泡参数卡','了解一个茶区或制茶工艺并写出要点','邀请他人一起品饮并记录反馈'],['连续 7 天记录不同茶的品饮体验','在限定条件下冲泡并复现一杯满意的茶','设计一次主题茶席并说明选择理由','完成一次盲品并记录判断依据'],['建立个人茶叶与冲泡档案','完成一个月的品饮记录并总结偏好','为一种茶制作一份可复用的冲泡指南'],['策划并完成一次完整茶主题分享','形成个人品茶方法与长期探索清单']),
 '烹饪':domainPack('烹饪',['完成一道简单菜并记录步骤','练习一种刀工或基础技法','尝试一次调味比例并记录结果','整理一道菜的食材与备料清单','复现一道喜欢的菜','为一顿饭设计一个简单菜单'],['完成一次三道菜的小菜单','比较两种烹饪方法的口感差异','整理五道可重复制作的家常菜','邀请他人试吃并记录反馈'],['连续 7 天完成一次家庭烹饪','在限定预算内完成一顿饭','从食材到成品完成一次完整备餐挑战','改良一道失败过的菜并记录变化'],['建立个人基础菜谱库','完成一个月烹饪记录并总结最常做的菜','形成自己的备餐与采购流程'],['策划一次主题菜单并完整执行','完成一份可分享的个人食谱作品集']),
 '摄影':domainPack('摄影',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'剪辑':domainPack('剪辑',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'内容创作':domainPack('内容创作',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'视觉叙事':domainPack('视觉叙事',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'视频制作':domainPack('视频制作',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'音乐':domainPack('音乐',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'长号':domainPack('长号',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'声乐':domainPack('声乐',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'古典音乐':domainPack('古典音乐',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'管弦乐':domainPack('管弦乐',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'歌剧':domainPack('歌剧',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'音乐制作':domainPack('音乐制作',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'编曲':domainPack('编曲',creativeDaily,creativeWeekly,creativeChallenge,creativePromotion,creativeBoss),'咖啡':domainPack('咖啡',experienceDaily,experienceWeekly,experienceChallenge,experiencePromotion,experienceBoss),'鸡尾酒':domainPack('鸡尾酒',experienceDaily,experienceWeekly,experienceChallenge,experiencePromotion,experienceBoss),'酒吧文化':domainPack('酒吧文化',experienceDaily,experienceWeekly,experienceChallenge,experiencePromotion,experienceBoss),'旅行':domainPack('旅行',experienceDaily,experienceWeekly,experienceChallenge,experiencePromotion,experienceBoss),'美食':domainPack('美食',experienceDaily,experienceWeekly,experienceChallenge,experiencePromotion,experienceBoss),'AI 工具':domainPack('AI 工具',techDaily,techWeekly,techChallenge,techPromotion,techBoss),'App 开发':domainPack('App 开发',techDaily,techWeekly,techChallenge,techPromotion,techBoss),'Pokémon':domainPack('Pokémon',gameDaily,gameWeekly,gameChallenge,gamePromotion,gameBoss),'RPG':domainPack('RPG',gameDaily,gameWeekly,gameChallenge,gamePromotion,gameBoss),'电子游戏':domainPack('电子游戏',gameDaily,gameWeekly,gameChallenge,gamePromotion,gameBoss),'游戏机制与 Build 研究':domainPack('游戏机制与 Build 研究',gameDaily,gameWeekly,gameChallenge,gamePromotion,gameBoss)
};
export const defaultQuestPool=questSeedAreas.flatMap((area,areaIndex)=>[...seedDaily.map((title,index)=>({id:`seed-${areaIndex}-d${index+1}`,area,type:'DAILY' as const,title:`${title}：${area}`,description:`围绕 ${area} 完成这项小任务。`,minutes:15,difficulty:1 as const})),...seedWeekly.map((title,index)=>({id:`seed-${areaIndex}-w${index+1}`,area,type:'WEEKLY' as const,title:`${title}：${area}`,description:`保留可复查产物。`,minutes:75,difficulty:3 as const})),...seedChallenge.map((title,index)=>({id:`seed-${areaIndex}-c${index+1}`,area,type:'CHALLENGE' as const,title:`${title}：${area}`,description:'记录过程证据与结果。',minutes:60,difficulty:4 as const})),...seedPromotion.map((title,index)=>({id:`seed-${areaIndex}-p${index+1}`,area,type:'PROMOTION' as const,title:`晋级任务 R${index+1}：${area}`,description:title,minutes:90,difficulty:4 as const})),...seedBoss.map((title,index)=>({id:`seed-${areaIndex}-b${index+1}`,area,type:'BOSS' as const,title:`Boss Quest：${title} · ${area}`,description:'综合多个能力完成最终成果。',minutes:180,difficulty:5 as const}))]);
export const questTemplates=(name:string):Omit<Quest,'id'|'targetId'|'targetName'|'createdAt'|'status'>[]=>{const domain=domainTemplates[name.toLowerCase()];if(domain)return domain as any;const seeded=defaultQuestPool.filter(item=>item.area.toLowerCase()===name.toLowerCase());if(seeded.length)return seeded as any;return [
 {title:`Review one ${name} concept`,description:`Recall one idea from ${name} without notes, then check your understanding.`,type:'DAILY',minutes:10,difficulty:1},
 {title:`Explore one question in ${name}`,description:`Write down one question and spend a focused session finding a useful answer.`,type:'EXPLORATION',minutes:15,difficulty:2},
 {title:`Make one small practice step in ${name}`,description:`Turn your current interest into a concrete, observable exercise.`,type:'PRACTICE',minutes:20,difficulty:2},
 {title:`Study one deeper source on ${name}`,description:`Read a section of a paper, book or course and capture three takeaways.`,type:'WEEKLY',minutes:45,difficulty:3},
 {title:`Explain ${name} in your own words`,description:`Create a short explanation that demonstrates understanding rather than recognition.`,type:'CHALLENGE',minutes:30,difficulty:3},
 {title:`Promotion: demonstrate ${name}`,description:`Complete a small artifact or explanation that proves your current level.`,type:'PROMOTION',minutes:40,difficulty:4}
]};
export const makeQuest=(template:ReturnType<typeof questTemplates>[number],targetId:string,targetName:string):Quest=>({...template,id:`quest-${targetId}-${template.type}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,targetId,targetName,cooldownDays:template.type==='WEEKLY'?7:2,weight:1,status:'available',createdAt:new Date().toISOString()});
export function weightedSample<T extends {weight?:number}>(items:T[],count:number){const configured=typeof localStorage!=='undefined'?Number(localStorage.getItem('personal-life-os-daily-quest-count')||3):3;const requested=count===3?Math.max(1,Math.min(8,configured)):count;const pool=[...items];const result:T[]=[];while(pool.length&&result.length<requested){const total=pool.reduce((sum,item)=>sum+Math.max(.01,item.weight||1),0);let pick=Math.random()*total;const index=pool.findIndex(item=>{pick-=Math.max(.01,item.weight||1);return pick<=0});result.push(pool.splice(index<0?pool.length-1:index,1)[0])}return result}
export const prerequisitesMet=(quest:Quest,completed:Quest[])=>!quest.prerequisites?.length||quest.prerequisites.every(requirement=>completed.some(item=>item.id===requirement||item.title.toLowerCase()===requirement.toLowerCase()));
