import type { EntityRelation, Goal, LearningArea, Skill } from './types';

const area=(id:string,name:string,priority:'High'|'Medium',focus:string,longTermGoal:string,topics:string[],color:string):LearningArea=>({id,name,description:focus,priority,status:'Active',progress:0,focus,longTermGoal,topics,color});
export const profileAreas:LearningArea[]=[
  area('profile-area-computational-neuroscience','Computational Neuroscience','High','Strengthen computational modelling foundations and connect models to behavioural and neuroscience questions.','Develop strong computational neuroscience research ability suitable for advanced research and PhD-level work.',['Neural Computation','Computational Cognitive Science','Mathematical Modelling','Dynamical Systems','Bayesian Models','Reinforcement Learning','Neural Coding','Neural Decoding'],'#8b7cf6'),
  area('profile-area-decision','Decision Making & Metacognition','High','Understand computational mechanisms underlying decisions, confidence, agency and perceived control.','Design, analyse and computationally model behavioural experiments in decision making and metacognition.',['Decision Making','Metacognition','Confidence','Sense of Agency','Controllability','Goal-directed Behaviour','Choice','Uncertainty','Cognitive Control'],'#62a98b'),
  area('profile-area-bci','Brain-Computer Interfaces','High','Build foundations in EEG analysis, signal processing and machine-learning-based neural decoding.','Conduct computational BCI research and build neural decoding pipelines.',['EEG','Neural Decoding','Signal Processing','Machine Learning','Motor Imagery','Assistive BCI','Neural Interfaces'],'#3bb5a3'),
  area('profile-area-psychiatry','Computational Psychiatry','High','Understand how computational models can explain behavioural and psychiatric differences.','Connect computational neuroscience, decision making and psychiatry in research.',['Reinforcement Learning','Decision Models','Depression','Motivation','Cognitive Control','Latent State Models','Individual Differences'],'#d18b62'),
  area('profile-area-attention','Attention, Boredom & Flow','Medium','Understand why boredom, attention, perceived control and flow emerge during goal-directed behaviour.','Develop computational or behavioural research questions connecting agency, controllability, boredom and flow.',['Attention','Boredom','Flow','Motivation','Mind Wandering','Time Perception','Goal Evaluation','Reward','Agency'],'#9c8df3'),
  area('profile-area-ai','Artificial Intelligence & Machine Learning','High','Build ML knowledge that can be applied to neuroscience, BCI and computational research.','Become comfortable using modern ML methods in scientific research.',['Machine Learning','Artificial Intelligence','Neural Networks','Reinforcement Learning','Representation Learning','Model Evaluation','AI Tools','LLMs'],'#e6a04b'),
  area('profile-area-statistics','Statistics & Quantitative Methods','High','Build strong statistical reasoning for behavioural and computational neuroscience.','Independently analyse complex research datasets and evaluate computational models rigorously.',['Probability','Regression','Model Comparison','Maximum Likelihood','AIC','Simulation','Parameter Recovery','Statistical Inference','Experimental Statistics'],'#8175df'),
  area('profile-area-methodology','Research Methodology','High','Move from research question to experiment, analysis and publication-quality interpretation.','Become an independent researcher capable of designing and executing rigorous studies.',['Experimental Design','Behavioural Experiments','Literature Review','Scientific Writing','Critical Appraisal','Reproducibility','Open Science','Research Communication','Evidence Evaluation'],'#78a590')
];

const skill=(id:string,name:string,target:'Beginner'|'Intermediate'|'Advanced',focus:string,priority:'High'|'Medium'):Skill=>({id,name,level:'Beginner',target,practiceCount:0,minutes:0,lastPracticed:'Not yet',focus,progress:0});
export const profileSkills:Skill[]=[
  skill('profile-skill-python','Python','Advanced','NumPy · pandas · matplotlib · scientific Python · simulation · data analysis','High'),skill('profile-skill-r','R','Intermediate','RStudio · data manipulation · statistics · visualization · reproducible reports','Medium'),skill('profile-skill-matlab','MATLAB','Intermediate','Computational neuroscience and BCI analysis','Medium'),skill('profile-skill-jspsych','jsPsych','Advanced','Behavioural task design · timing · randomization · data capture','High'),skill('profile-skill-git','Git & GitHub','Intermediate','Version control · branching · reproducible research workflow','Medium'),skill('profile-skill-react','React & TypeScript','Intermediate','React · TypeScript · Vite · frontend architecture · application state','Medium'),
  skill('profile-skill-data-analysis','Data Analysis','Advanced','Research data cleaning, modelling and interpretation','High'),skill('profile-skill-visualization','Data Visualization','Intermediate','Clear plots and research communication','Medium'),skill('profile-skill-stats','Statistical Analysis','Advanced','Inference, regression and model comparison','High'),skill('profile-skill-modelling','Computational Modelling','Advanced','Likelihood · negative log likelihood · estimation · recovery · bias · MAE · AIC','High'),skill('profile-skill-simulation','Simulation','Intermediate','Simulation and parameter recovery','Medium'),skill('profile-skill-ml','Machine Learning','Advanced','Scientific machine learning and evaluation','High'),skill('profile-skill-rl','Reinforcement Learning','Intermediate','Decision models and reward learning','Medium'),skill('profile-skill-decoding','Neural Decoding','Intermediate','Feature extraction, decoding and evaluation','Medium'),skill('profile-skill-eeg','EEG Analysis','Intermediate','EEG preprocessing and neural signals','Medium'),skill('profile-skill-signal','Signal Processing','Intermediate','Filtering, time-frequency analysis and artefacts','Medium'),
  skill('profile-skill-reading','Scientific Reading','Advanced','Identify central claim, evidence, methodology, limitations and computational relevance','High'),skill('profile-skill-literature','Literature Search','Intermediate','Systematic search and source management','Medium'),skill('profile-skill-appraisal','Critical Appraisal','Intermediate','Evaluate evidence and limitations','Medium'),skill('profile-skill-writing','Scientific Writing','Advanced','Clear abstracts, arguments and research notes','Medium'),skill('profile-skill-design','Experimental Design','Advanced','Design rigorous behavioural and computational experiments','High'),skill('profile-skill-task-design','Behavioural Task Design','Intermediate','Task structure, timing and participant testing','Medium'),skill('profile-skill-presentation','Research Presentation','Intermediate','Academic communication and evidence evaluation','Medium'),skill('profile-skill-reproducible','Reproducible Research','Intermediate','Open science, Git and reproducible workflows','Medium'),
  skill('profile-skill-behavioural-neuroscience','Behavioural Neuroscience','Intermediate','Behavioural mechanisms and experimental interpretation','Medium'),skill('profile-skill-bci','EEG / BCI','Intermediate','Neural interfaces and BCI foundations','Medium'),skill('profile-skill-cognitive-modelling','Cognitive Modelling','Intermediate','Computational accounts of cognition','Medium'),skill('profile-skill-psychiatry','Computational Psychiatry','Intermediate','Computational accounts of psychiatric differences','Medium'),skill('profile-skill-wetlab','Basic Wet Lab Neuroscience','Intermediate','Foundational wet-lab literacy','Medium'),skill('profile-skill-ipsc','iPSC Lab Techniques','Beginner','Foundational iPSC lab literacy','Medium')
].map(item=>({...item,level:item.name==='Python'?'Intermediate':item.level}));

export const profileGoals:Goal[]=[
  {id:'profile-goal-foundations',title:'Build strong computational neuroscience foundations',period:'Long-term',progress:0,detail:'Computational Neuroscience · Python · Statistics · Computational Modelling'},
  {id:'profile-goal-models',title:'Become capable of independently fitting and evaluating computational models',period:'Long-term',progress:0,detail:'Modelling · Statistics · Model Comparison · Parameter Recovery'},
  {id:'profile-goal-bci',title:'Develop BCI and neural decoding skills',period:'Long-term',progress:0,detail:'BCI · EEG · Signal Processing · Neural Decoding · Machine Learning'},
  {id:'profile-goal-researcher',title:'Become an independent behavioural/computational neuroscience researcher',period:'Long-term',progress:0,detail:'Experimental Design · Scientific Reading · Writing · Data Analysis'}
];

export const profileRelations:Array<Omit<EntityRelation,'id'|'createdAt'|'updatedAt'>>=[
  ['Computational Neuroscience','requires','Statistics'],['Computational Neuroscience','requires','Python'],['Computational Neuroscience','uses','Computational Modelling'],['Computational Modelling','requires','Statistics'],['Computational Modelling','uses','Python'],['Decision Making','related_to','Metacognition'],['Decision Making','related_to','Sense of Agency'],['Sense of Agency','related_to','Controllability'],['Attention','related_to','Boredom'],['Boredom','related_to','Flow'],['Flow','related_to','Goal-directed Behaviour'],['Brain-Computer Interfaces','requires','Signal Processing'],['Brain-Computer Interfaces','requires','Machine Learning'],['Brain-Computer Interfaces','uses','EEG'],['EEG','supports','Neural Decoding'],['Neural Decoding','uses','Machine Learning'],['Computational Psychiatry','uses','Reinforcement Learning'],['Computational Psychiatry','related_to','Decision Making'],['Machine Learning','supports','Neural Decoding'],['Scientific Reading','supports','Literature Review'],['Experimental Design','supports','Behavioural Task Design'],['Behavioural Task Design','uses','jsPsych'],['Reproducible Research','uses','Git & GitHub']
].map(([source,relation,target])=>({sourceType:'LearningArea',sourceId:source,targetType:'Skill',targetId:target,relationType:relation}));
