import type { ActivityEntity, AppData, HabitLog, RepositorySnapshot, SkillLog, TaskCompletion } from '../domain/types';
import { loadSnapshot } from '../repositories/appRepository';

export function getUnifiedActivities(snapshot:RepositorySnapshot=loadSnapshot()):ActivityEntity[]{return [...snapshot.activities].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));}
export function getActivitiesForDate(date:string,snapshot:RepositorySnapshot=loadSnapshot()){return getUnifiedActivities(snapshot).filter(activity=>activity.occurredAt.slice(0,10)===date);}
export function getTaskCompletionsForDate(date:string,snapshot:RepositorySnapshot=loadSnapshot()):TaskCompletion[]{return snapshot.taskCompletions.filter(item=>item.completedAt.slice(0,10)===date);}
export function getHabitLogsForDate(date:string,snapshot:RepositorySnapshot=loadSnapshot()):HabitLog[]{return snapshot.habitLogs.filter(item=>item.date===date);}
export function getSkillLogsForDate(date:string,snapshot:RepositorySnapshot=loadSnapshot()):SkillLog[]{return (snapshot.skillLogs||[]).filter(item=>item.occurredAt.slice(0,10)===date);}
export function summarizeToday(data:AppData,date:string=new Date().toISOString().slice(0,10)){const snapshot=loadSnapshot();const activities=getActivitiesForDate(date,snapshot);const taskCompletions=getTaskCompletionsForDate(date,snapshot);const habitLogs=getHabitLogsForDate(date,snapshot);return{activities,taskCompletions,habitLogs,tasksCompleted:new Set(taskCompletions.map(x=>x.taskId)).size,habitsCompleted:habitLogs.filter(x=>x.completed).length,minutes:activities.reduce((sum,x)=>sum+(x.durationMinutes||0),0)+data.log.minutes};}
export function getDisplayActivities(snapshot:RepositorySnapshot=loadSnapshot()){return getUnifiedActivities(snapshot).map(activity=>({id:activity.id,label:activity.title,type:activity.type,time:new Date(activity.occurredAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),meta:activity.durationMinutes?`${activity.durationMinutes} minutes · ${activity.source||'Activity'}`:activity.source||'Activity'}));}
export function getAnalyticsEntries(data:AppData,days=7){const snapshot=loadSnapshot();const today=new Date();return Array.from({length:days},(_,index)=>{const date=new Date(today);date.setDate(today.getDate()-(days-1-index));const key=date.toISOString().slice(0,10);const activities=getActivitiesForDate(key,snapshot);const completions=getTaskCompletionsForDate(key,snapshot);const minutes=activities.reduce((sum,item)=>sum+(item.durationMinutes||0),0)+(key===data.log.date?data.log.minutes:0);return{date:key,log:{minutes},tasks:Array.from({length:new Set(completions.map(item=>item.taskId)).size},(_,taskIndex)=>String(taskIndex)),skillPractices:getSkillLogsForDate(key,snapshot).length};});}
