import type { Book } from '../domain/books';
export type BookEvidence={chunkId:string;text:string;pageStart:number;pageEnd:number;score:number};
const stopwords=new Set('the a an and or of to in on for with from is are was were be this that what does how why about into by as it its their his her our your book say'.split(' '));
const terms=(value:string)=>value.toLowerCase().split(/[^\p{L}\p{N}]+/u).map(term=>term.trim()).filter(term=>term.length>2&&!stopwords.has(term));
const overlap=(a:string,b:string)=>{const left=new Set(terms(a));const right=new Set(terms(b));const common=[...left].filter(term=>right.has(term)).length;return common/Math.max(1,new Set([...left,...right]).size)};
export function retrieveBookChunks(book:Book,question:string,limit=4):BookEvidence[]{const query=terms(question);if(!query.length)return[];const chunks=book.bookChunks||[];const documentFrequency=new Map<string,number>();chunks.forEach(chunk=>new Set(terms(chunk.text)).forEach(term=>documentFrequency.set(term,(documentFrequency.get(term)||0)+1)));const candidates=chunks.map(chunk=>{const normalized=chunk.text.toLowerCase();const words=terms(chunk.text);const unique=new Set(words);const rare=query.reduce((sum,term)=>sum+(unique.has(term)?Math.log((chunks.length+1)/((documentFrequency.get(term)||0)+1)):0),0);const matched=query.reduce((sum,term)=>sum+(unique.has(term)?1:0),0);const phrase=question.trim().length>5&&normalized.includes(question.trim().toLowerCase())?1:0;const score=matched/query.length*.65+rare/Math.max(1,query.length)*.25+phrase*.1;return{chunkId:chunk.id,text:chunk.text,pageStart:chunk.pageStart,pageEnd:chunk.pageEnd,score}}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score);const selected:BookEvidence[]=[];for(const candidate of candidates){if(selected.length>=Math.min(8,limit))break;if(selected.every(item=>overlap(item.text,candidate.text)<.72)||candidate.score>selected[0]?.score*1.25)selected.push(candidate);}return selected;}
export function formatBookEvidence(evidence:BookEvidence[]){return evidence.map(item=>`Chapter source · pp. ${item.pageStart}${item.pageEnd===item.pageStart?'':`–${item.pageEnd}`}\n${item.text}`).join('\n\n');}
export type RetrievalCase={question:string;expectedChunkIds:string[]};
export function evaluateRetrieval(book:Book,cases:RetrievalCase[],k=4){const results=cases.map(test=>{const actual=retrieveBookChunks(book,test.question,k).map(item=>item.chunkId);const expected=new Set(test.expectedChunkIds);const hits=actual.filter(id=>expected.has(id)).length;return{question:test.question,hits,recall:expected.size?hits/expected.size:0,precision:actual.length?hits/actual.length:0,hitRate:hits>0?1:0}});return{recallAtK:results.length?results.reduce((sum,item)=>sum+item.recall,0)/results.length:0,precisionAtK:results.length?results.reduce((sum,item)=>sum+item.precision,0)/results.length:0,hitRate:results.length?results.reduce((sum,item)=>sum+item.hitRate,0)/results.length:0,results};}
