import type { Book } from '../domain/books';
import { metadataRepository } from '../repositories/legacyRepositories';

export type BookAIConcept={name:string;summary:string;tier:1|2|3|4;whyEssential?:string;prerequisites?:string[];sourceChunkIds?:string[];centralityScore?:number;dependencyScore?:number;bookThesisImportance?:number;userRelevanceScore?:number;practicalValue?:number;redundancyPenalty?:number};
export type BookAIResult={bookType:string;coreThesis:string;concepts:BookAIConcept[];recalls:Array<{question:string;answer:string;difficulty:'Easy'|'Medium'|'Hard';conceptName:string}>;warnings?:string[]};
export type BookCitation={chunkId:string;pageStart:number;pageEnd:number;supportingQuote?:string};
export type BookAnswer={answer:string;confidence:number;citations:BookCitation[];insufficientEvidence:boolean;followUpQuestions?:string[]};

async function postBookRequest(endpoint:string,payload:unknown){const target=endpoint.trim();try{const url=new URL(target);if(url.protocol!=='https:')throw new Error('AI endpoint must use HTTPS.')}catch(error){if(error instanceof Error&&error.message==='AI endpoint must use HTTPS.')throw error;throw new Error('AI endpoint URL is invalid. Check Settings.')}const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),15000);try{const response=await fetch(target,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});const raw=await response.text();let body:any;try{body=raw?JSON.parse(raw):null}catch{throw new Error(`AI endpoint returned non-JSON response (${response.status}).`)}if(!response.ok)throw new Error(body?.error||`AI endpoint failed (${response.status}).`);return body}catch(error){if(error instanceof DOMException&&error.name==='AbortError')throw new Error('AI request timed out after 15 seconds. Check that the Supabase Function is deployed and the URL in Settings is correct.');if(error instanceof TypeError)throw new Error('Could not reach the AI endpoint. Check the Supabase URL, deployment and internet connection.');throw error}finally{window.clearTimeout(timeout)}}
export async function requestBookAI(endpoint:string,book:Book,context:{areas:string[];skills:string[];goals:string[]}){const body=await postBookRequest(endpoint,{kind:'book-extract',book:{id:book.id,title:book.title,chunks:(book.bookChunks||[]).slice(0,24).map(chunk=>({text:chunk.text,pageStart:chunk.pageStart,pageEnd:chunk.pageEnd,chunkIndex:chunk.chunkIndex}))},context});if(!body?.result)throw new Error(body?.error||'The AI returned no structured book result. Update the ai-recommendations Supabase Function.');return body.result as BookAIResult;}
export const configuredBookAIEndpoint=()=>metadataRepository.get<string>('personal-life-os-ai-endpoint','');
export async function requestBookAnswer(endpoint:string,book:Book,question:string,evidence:Array<{chunkId:string;text:string;pageStart:number;pageEnd:number}>){const body=await postBookRequest(endpoint,{kind:'book-answer',question,book:{id:book.id,title:book.title},evidence:evidence.map(item=>({chunkId:item.chunkId,text:item.text,pageStart:item.pageStart,pageEnd:item.pageEnd}))});if(!body?.result)throw new Error(body?.error||'The AI returned no structured book answer. Update the ai-recommendations Supabase Function.');return body.result as BookAnswer;}
