import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import type { BookPage, ParsedBook } from '../domain/bookParsing';

export interface BookParser { parse(file:File):Promise<ParsedBook>; }
const now=()=>new Date().toISOString();
const chunkPages=(pages:BookPage[],size=1800,overlap=180)=>{const chunks:ParsedBook['chunks']=[];let carry='';let index=0;for(const page of pages){const text=(carry+' '+page.text).trim();if(!text)continue;let start=0;while(start<text.length){const end=Math.min(text.length,start+size);const value=text.slice(start,end).trim();if(value)chunks.push({id:`chunk-${Date.now()}-${index}`,text:value,pageStart:page.pageNumber,pageEnd:page.pageNumber,chunkIndex:index++,tokenEstimate:Math.ceil(value.length/4),createdAt:now()});start=end-overlap;}carry=text.slice(Math.max(0,text.length-overlap));}return chunks;};
export class TextBookParser implements BookParser {async parse(file:File):Promise<ParsedBook>{const text=await file.text();const pages=[{pageNumber:1,text:text.trim()}];return{pages,chunks:chunkPages(pages),warnings:text.trim()?[]:['The text file is empty.'],sourceType:'text'};}}
export class MarkdownBookParser extends TextBookParser {async parse(file:File){const result=await super.parse(file);return{...result,sourceType:'markdown' as const};}}
export class PdfBookParser implements BookParser {async parse(file:File):Promise<ParsedBook>{const bytes=new Uint8Array(await file.arrayBuffer());let document:any;try{document=await pdfjs.getDocument({data:bytes,disableWorker:true} as any).promise;}catch(error){throw new Error(error instanceof Error?`PDF could not be opened: ${error.message}`:'PDF could not be opened. It may be corrupted or password protected.');}const pages:BookPage[]=[];const warnings:string[]=[];for(let pageNumber=1;pageNumber<=document.numPages;pageNumber++){const page=await document.getPage(pageNumber);const content=await page.getTextContent();const text=content.items.map((item:any)=>typeof item.str==='string'?item.str:'').join(' ').replace(/\s+/g,' ').trim();pages.push({pageNumber,text});if(!text)warnings.push(`Page ${pageNumber} contains no selectable text; it may be scanned or image-only.`);}if(!pages.some(page=>page.text))warnings.push('No selectable text was extracted from this PDF. OCR is required for scanned books.');return{pages,chunks:chunkPages(pages),warnings,sourceType:'pdf'};}}
export const parserFor=(file:File):BookParser=>file.type==='application/pdf'||/\.pdf$/i.test(file.name)?new PdfBookParser():/\.md$/i.test(file.name)||file.type==='text/markdown'?new MarkdownBookParser():new TextBookParser();
