import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import workerSrc from 'pdfjs-dist/legacy/build/pdf.worker.mjs?url';
import { strFromU8, unzipSync } from 'fflate';

// Vite serves the PDF worker as a separate asset. Without this, pdfjs throws
// "GlobalWorkerOptions.workerSrc" errors when a user uploads a PDF.
pdfjs.GlobalWorkerOptions.workerSrc = workerSrc;
import type { BookPage, ParsedBook } from '../domain/bookParsing';

export interface BookParser { parse(file:File):Promise<ParsedBook>; }
const now=()=>new Date().toISOString();
const normalizeText=(value:string)=>value.replace(/\u00ad/g,'').replace(/(\w)-\s+(\w)/g,'$1$2').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,' ').replace(/\s+/g,' ').trim();
export const textLayerLooksCorrupted=(value:string)=>{const words=value.split(/\s+/).filter(Boolean);if(words.length<25)return false;const tiny=words.filter(word=>word.length<=2).length/words.length;const symbols=(value.match(/[|_{}[\]=]{2,}/g)||[]).length;const replacement=(value.match(/�/g)||[]).length;return tiny>.38||symbols>2||replacement>0};
const chunkPages=(pages:BookPage[],size=1800,overlap=180)=>{const chunks:ParsedBook['chunks']=[];let buffer='';let startPage=0;let endPage=0;let index=0;for(const page of pages){const text=normalizeText(page.text);if(!text)continue;if(!buffer)startPage=page.pageNumber;buffer=(buffer+' '+text).trim();endPage=page.pageNumber;while(buffer.length>size){const window=buffer.slice(0,size);const boundary=Math.max(window.lastIndexOf('. '),window.lastIndexOf('。'),window.lastIndexOf('? '),window.lastIndexOf('! '));const cut=boundary>size*.65?boundary+1:size;const value=buffer.slice(0,cut).trim();chunks.push({id:`chunk-${Date.now()}-${index}`,text:value,pageStart:startPage,pageEnd:endPage,chunkIndex:index++,tokenEstimate:Math.ceil(value.length/4),createdAt:now()});buffer=buffer.slice(Math.max(0,cut-overlap)).trim();} }if(buffer)chunks.push({id:`chunk-${Date.now()}-${index}`,text:buffer,pageStart:startPage,pageEnd:endPage,chunkIndex:index,tokenEstimate:Math.ceil(buffer.length/4),createdAt:now()});return chunks;};
export class TextBookParser implements BookParser {async parse(file:File):Promise<ParsedBook>{const text=normalizeText(await file.text());const pages=[{pageNumber:1,text}];return{pages,chunks:chunkPages(pages),warnings:text?[]:['The text file is empty.'],sourceType:'text'};}}
export class MarkdownBookParser extends TextBookParser {async parse(file:File){const result=await super.parse(file);return{...result,sourceType:'markdown' as const};}}
export class PdfBookParser implements BookParser {async parse(file:File):Promise<ParsedBook>{const bytes=new Uint8Array(await file.arrayBuffer());let document:any;try{document=await pdfjs.getDocument({data:bytes} as any).promise;}catch(error){throw new Error(error instanceof Error?`PDF could not be opened: ${error.message}`:'PDF could not be opened. It may be corrupted or password protected.');}const pages:BookPage[]=[];const warnings:string[]=[];for(let pageNumber=1;pageNumber<=document.numPages;pageNumber++){const page=await document.getPage(pageNumber);const content=await page.getTextContent();const text=normalizeText(content.items.map((item:any)=>typeof item.str==='string'?item.str:'').join(' '));pages.push({pageNumber,text});if(!text)warnings.push(`Page ${pageNumber} contains no selectable text; it may be scanned or image-only.`);if(text.length>0&&text.length<120)warnings.push(`Page ${pageNumber} contains unusually little text; verify its extraction.`);}const combined=pages.map(page=>page.text).join(' ');if(!pages.some(page=>page.text))warnings.push('No selectable text was extracted from this PDF. OCR is required for scanned books.');else if(textLayerLooksCorrupted(combined))warnings.push('This PDF text layer appears corrupted. OCR is recommended before Analyze.');return{pages,chunks:chunkPages(pages),warnings,sourceType:'pdf'};}}
const normalizePath=(value:string)=>{const parts:string[]=[];for(const part of value.replace(/^\//,'').split('/')){if(!part||part==='.')continue;if(part==='..')parts.pop();else parts.push(part)}return parts.join('/')};
const resolvePath=(base:string,target:string)=>normalizePath(`${base?`${base}/`:''}${target.split('#')[0]}`);
export class EpubBookParser implements BookParser {async parse(file:File):Promise<ParsedBook>{let files:Record<string,Uint8Array>;try{files=unzipSync(new Uint8Array(await file.arrayBuffer()));}catch{throw new Error('EPUB could not be opened. The file may be corrupted or encrypted.')}const read=(path:string)=>files[normalizePath(path)]?strFromU8(files[normalizePath(path)]):'';const warnings:string[]=[];const container=read('META-INF/container.xml');const rootfile=container.match(/full-path=["']([^"']+)["']/i)?.[1];if(!rootfile)throw new Error('EPUB could not be opened: package metadata is missing.');const opf=read(rootfile);const opfBase=rootfile.includes('/')?rootfile.slice(0,rootfile.lastIndexOf('/')):'';const manifest=new Map<string,string>();for(const match of opf.matchAll(/<item\b[^>]*?id=["']([^"']+)["'][^>]*?href=["']([^"']+)["'][^>]*>/gi))manifest.set(match[1],resolvePath(opfBase,decodeURIComponent(match[2])));const spineIds=Array.from(opf.matchAll(/<itemref\b[^>]*?idref=["']([^"']+)["'][^>]*>/gi)).map(match=>match[1]);const pages:BookPage[]=[];for(const id of spineIds){const path=manifest.get(id);if(!path)continue;const source=read(path);if(!source)continue;const document=new DOMParser().parseFromString(source,'application/xhtml+xml');const text=normalizeText(document.body?.textContent||'');pages.push({pageNumber:pages.length+1,text});if(!text)warnings.push(`EPUB chapter ${pages.length} contains no selectable text.`);}if(!pages.length)throw new Error('EPUB could not be opened: no readable chapters were found.');return{pages,chunks:chunkPages(pages),warnings,sourceType:'epub'};}}
export const parserFor=(file:File):BookParser=>file.type==='application/pdf'||/\.pdf$/i.test(file.name)?new PdfBookParser():file.type==='application/epub+zip'||/\.epub$/i.test(file.name)?new EpubBookParser():/\.md$/i.test(file.name)||file.type==='text/markdown'?new MarkdownBookParser():new TextBookParser();
