import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import type { BookPage, ParsedBook } from '../domain/bookParsing';

export interface BookParser { parse(file:File):Promise<ParsedBook>; }
const now=()=>new Date().toISOString();
const normalizeText=(value:string)=>value.replace(/\u00ad/g,'').replace(/(\w)-\s+(\w)/g,'$1$2').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,' ').replace(/\s+/g,' ').trim();
const chunkPages=(pages:BookPage[],size=1800,overlap=180)=>{const chunks:ParsedBook['chunks']=[];let buffer='';let startPage=0;let endPage=0;let index=0;for(const page of pages){const text=normalizeText(page.text);if(!text)continue;if(!buffer)startPage=page.pageNumber;buffer=(buffer+' '+text).trim();endPage=page.pageNumber;while(buffer.length>size){const window=buffer.slice(0,size);const boundary=Math.max(window.lastIndexOf('. '),window.lastIndexOf('。'),window.lastIndexOf('? '),window.lastIndexOf('! '));const cut=boundary>size*.65?boundary+1:size;const value=buffer.slice(0,cut).trim();chunks.push({id:`chunk-${Date.now()}-${index}`,text:value,pageStart:startPage,pageEnd:endPage,chunkIndex:index++,tokenEstimate:Math.ceil(value.length/4),createdAt:now()});buffer=buffer.slice(Math.max(0,cut-overlap)).trim();} }if(buffer)chunks.push({id:`chunk-${Date.now()}-${index}`,text:buffer,pageStart:startPage,pageEnd:endPage,chunkIndex:index,tokenEstimate:Math.ceil(buffer.length/4),createdAt:now()});return chunks;};
export class TextBookParser implements BookParser {async parse(file:File):Promise<ParsedBook>{const text=normalizeText(await file.text());const pages=[{pageNumber:1,text}];return{pages,chunks:chunkPages(pages),warnings:text?[]:['The text file is empty.'],sourceType:'text'};}}
export class MarkdownBookParser extends TextBookParser {async parse(file:File){const result=await super.parse(file);return{...result,sourceType:'markdown' as const};}}
export class PdfBookParser implements BookParser {async parse(file:File):Promise<ParsedBook>{const bytes=new Uint8Array(await file.arrayBuffer());let document:any;try{document=await pdfjs.getDocument({data:bytes,disableWorker:true} as any).promise;}catch(error){throw new Error(error instanceof Error?`PDF could not be opened: ${error.message}`:'PDF could not be opened. It may be corrupted or password protected.');}const pages:BookPage[]=[];const warnings:string[]=[];for(let pageNumber=1;pageNumber<=document.numPages;pageNumber++){const page=await document.getPage(pageNumber);const content=await page.getTextContent();const text=normalizeText(content.items.map((item:any)=>typeof item.str==='string'?item.str:'').join(' '));pages.push({pageNumber,text});if(!text)warnings.push(`Page ${pageNumber} contains no selectable text; it may be scanned or image-only.`);if(text.length>0&&text.length<120)warnings.push(`Page ${pageNumber} contains unusually little text; verify its extraction.`);}if(!pages.some(page=>page.text))warnings.push('No selectable text was extracted from this PDF. OCR is required for scanned books.');return{pages,chunks:chunkPages(pages),warnings,sourceType:'pdf'};}}
export const parserFor=(file:File):BookParser=>file.type==='application/pdf'||/\.pdf$/i.test(file.name)?new PdfBookParser():/\.md$/i.test(file.name)||file.type==='text/markdown'?new MarkdownBookParser():new TextBookParser();
