export type CalendarSubscriptionEvent={id:string;title:string;date:string;startTime:string;endTime:string;location:string;description:string};

const URL_KEY='personal-life-os-calendar-subscription-url';
const EVENTS_KEY='personal-life-os-calendar-subscription-events';
const UPDATED_KEY='personal-life-os-calendar-subscription-updated';
const unescapeText=(value='')=>value.replace(/\\n/gi,' · ').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\').trim();
const field=(block:string,name:string)=>block.split('\n').find(line=>line.startsWith(name+':')||line.startsWith(name+';'))?.replace(/^[^:]+:/,'')||'';
const parseDateTime=(value:string)=>{const compact=value.replace(/[^0-9TZ]/g,'');const year=Number(compact.slice(0,4));const month=Number(compact.slice(4,6));const day=Number(compact.slice(6,8));const hour=Number(compact.slice(9,11)||0);const minute=Number(compact.slice(11,13)||0);const date=compact.endsWith('Z')?new Date(Date.UTC(year,month-1,day,hour,minute)):new Date(year,month-1,day,hour,minute);const pad=(part:number)=>String(part).padStart(2,'0');return{date:`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`,time:`${pad(date.getHours())}:${pad(date.getMinutes())}`}};

export function parseICalendar(source:string){const unfolded=source.replace(/\r?\n[ \t]/g,'').replace(/\r\n/g,'\n');return unfolded.split('BEGIN:VEVENT').slice(1).map((part,index)=>part.split('END:VEVENT')[0]).map((block,index)=>{const start=parseDateTime(field(block,'DTSTART'));const end=parseDateTime(field(block,'DTEND'));const uid=field(block,'UID')||`${start.date}-${start.time}-${index}`;return{id:uid,title:unescapeText(field(block,'SUMMARY'))||'UCL event',date:start.date,startTime:start.time,endTime:end.time,location:unescapeText(field(block,'LOCATION')),description:unescapeText(field(block,'DESCRIPTION'))}}).filter(event=>event.date&&event.startTime)}
export function loadCalendarSubscription(){try{return{url:localStorage.getItem(URL_KEY)||'',events:JSON.parse(localStorage.getItem(EVENTS_KEY)||'[]') as CalendarSubscriptionEvent[],updatedAt:localStorage.getItem(UPDATED_KEY)||''}}catch{return{url:'',events:[] as CalendarSubscriptionEvent[],updatedAt:''}}}
export function clearCalendarSubscription(){localStorage.removeItem(URL_KEY);localStorage.removeItem(EVENTS_KEY);localStorage.removeItem(UPDATED_KEY)}
export function importCalendarFile(source:string,url=''){const events=parseICalendar(source);if(!events.length)throw new Error('No calendar events were found.');const updatedAt=new Date().toISOString();if(url)localStorage.setItem(URL_KEY,url);localStorage.setItem(EVENTS_KEY,JSON.stringify(events));localStorage.setItem(UPDATED_KEY,updatedAt);return{url:url||localStorage.getItem(URL_KEY)||'',events,updatedAt}}
export async function syncCalendarSubscription(url:string){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`Calendar returned ${response.status}.`);const events=parseICalendar(await response.text());if(!events.length)throw new Error('No calendar events were found.');const updatedAt=new Date().toISOString();localStorage.setItem(URL_KEY,url);localStorage.setItem(EVENTS_KEY,JSON.stringify(events));localStorage.setItem(UPDATED_KEY,updatedAt);return{url,events,updatedAt}}
