import type { HabitLog } from '../domain/types';

export function upsertHabitLog(logs:HabitLog[],next:HabitLog):HabitLog[]{return [next,...logs.filter(log=>!(log.habitId===next.habitId&&log.date===next.date))];}
export function calculateDailyStreak(habitId:string,logs:HabitLog[],today=new Date().toISOString().slice(0,10)){const completed=new Set(logs.filter(log=>log.habitId===habitId&&log.completed).map(log=>log.date));let cursor=new Date(`${today}T12:00:00`);let streak=0;while(completed.has(cursor.toISOString().slice(0,10))){streak++;cursor.setDate(cursor.getDate()-1)}return streak;}
export function calculateWeekdayStreak(habitId:string,logs:HabitLog[],today=new Date().toISOString().slice(0,10)){const completed=new Set(logs.filter(log=>log.habitId===habitId&&log.completed).map(log=>log.date));let cursor=new Date(`${today}T12:00:00`);let streak=0;while(true){const day=cursor.getDay();if(day!==0&&day!==6){if(!completed.has(cursor.toISOString().slice(0,10)))break;streak++;}cursor.setDate(cursor.getDate()-1);if(streak>366)break;}return streak;}
export function calculateWeeklyStreak(habitId:string,logs:HabitLog[],targetPerWeek=1,today=new Date().toISOString().slice(0,10)){const weeks=new Map<string,number>();for(const log of logs.filter(item=>item.habitId===habitId&&item.completed)){const date=new Date(`${log.date}T12:00:00`);const day=date.getDay()||7;date.setDate(date.getDate()-day+1);const key=date.toISOString().slice(0,10);weeks.set(key,(weeks.get(key)||0)+1);}const current=new Date(`${today}T12:00:00`);let day=current.getDay()||7;current.setDate(current.getDate()-day+1);let streak=0;while((weeks.get(current.toISOString().slice(0,10))||0)>=targetPerWeek){streak++;current.setDate(current.getDate()-7);if(streak>260)break;}return streak;}
export function calculateHabitStreak(habitId:string,logs:HabitLog[],frequency:string,target='1',today=new Date().toISOString().slice(0,10)){if(frequency.toLowerCase().includes('week'))return calculateWeeklyStreak(habitId,logs,Math.max(1,Number.parseInt(target)||1),today);if(frequency.toLowerCase().includes('weekday'))return calculateWeekdayStreak(habitId,logs,today);return calculateDailyStreak(habitId,logs,today);}
export function calculateHabitBestStreak(habitId:string,logs:HabitLog[],frequency:string,target='1'){const dates=logs.filter(item=>item.habitId===habitId&&item.completed).map(item=>item.date).sort();if(!dates.length)return 0;let best=0;for(const date of dates)best=Math.max(best,calculateHabitStreak(habitId,logs,frequency,target,date));return best;}
export function isHabitCompletedToday(habitId:string,logs:HabitLog[],today=new Date().toISOString().slice(0,10)){return logs.some(item=>item.habitId===habitId&&item.date===today&&item.completed);}
