import type { HabitLog } from '../domain/types';
import { localDateKey } from '../domain/date';

const atNoon=(key:string)=>new Date(`${key}T12:00:00`);
const previous=(key:string)=>{const date=atNoon(key);date.setDate(date.getDate()-1);return localDateKey(date)};
const weekStart=(key:string)=>{const date=atNoon(key);const day=date.getDay()||7;date.setDate(date.getDate()-day+1);return localDateKey(date)};
export function upsertHabitLog(logs:HabitLog[],next:HabitLog):HabitLog[]{return [next,...logs.filter(log=>!(log.habitId===next.habitId&&log.date===next.date))]}
export function calculateDailyStreak(habitId:string,logs:HabitLog[],today=localDateKey()){const completed=new Set(logs.filter(log=>log.habitId===habitId&&log.completed).map(log=>log.date));let cursor=today;let streak=0;while(completed.has(cursor)){streak++;cursor=previous(cursor)}return streak}
export function calculateWeekdayStreak(habitId:string,logs:HabitLog[],today=localDateKey()){const completed=new Set(logs.filter(log=>log.habitId===habitId&&log.completed).map(log=>log.date));let cursor=atNoon(today);let streak=0;while(true){const day=cursor.getDay();if(day!==0&&day!==6){const key=localDateKey(cursor);if(!completed.has(key))break;streak++}cursor.setDate(cursor.getDate()-1);if(streak>366)break}return streak}
export function calculateWeeklyStreak(habitId:string,logs:HabitLog[],targetPerWeek=1,today=localDateKey()){const weeks=new Map<string,number>();for(const log of logs.filter(item=>item.habitId===habitId&&item.completed))weeks.set(weekStart(log.date),(weeks.get(weekStart(log.date))||0)+1);let cursor=weekStart(today);let streak=0;while((weeks.get(cursor)||0)>=targetPerWeek){streak++;const date=atNoon(cursor);date.setDate(date.getDate()-7);cursor=localDateKey(date);if(streak>260)break}return streak}
export function calculateHabitStreak(habitId:string,logs:HabitLog[],frequency:string,target='1',today=localDateKey()){if(frequency.toLowerCase().includes('week'))return calculateWeeklyStreak(habitId,logs,Math.max(1,Number.parseInt(target)||1),today);if(frequency.toLowerCase().includes('weekday'))return calculateWeekdayStreak(habitId,logs,today);return calculateDailyStreak(habitId,logs,today)}
export function calculateHabitBestStreak(habitId:string,logs:HabitLog[],frequency:string,target='1'){const dates=logs.filter(item=>item.habitId===habitId&&item.completed).map(item=>item.date).sort();if(!dates.length)return 0;let best=0;for(const date of dates)best=Math.max(best,calculateHabitStreak(habitId,logs,frequency,target,date));return best}
export function isHabitCompletedToday(habitId:string,logs:HabitLog[],today=localDateKey()){return logs.some(item=>item.habitId===habitId&&item.date===today&&item.completed)}
