import type { AppData, EntityRelation, RepositorySnapshot } from '../domain/types';
import { profileAreas, profileGoals, profileRelations, profileSkills } from '../domain/userProfileSeed';
import { profileInterests } from '../domain/interests';
import { saveSnapshot } from '../repositories/appRepository';

const normalize=(value:string)=>value.toLowerCase().replace(/[–—‑]/g,'-').replace(/[^a-z0-9]+/g,'');
const mergeNames=<T extends {id:string;name:string}>(existing:T[], additions:T[], merge:(current:T,addition:T)=>T)=>{const result=[...existing];const byName=new Map(result.map(item=>[normalize(item.name),item]));for(const addition of additions){const key=normalize(addition.name);const current=byName.get(key);if(current){const next=merge(current,addition);result[result.findIndex(item=>item.id===current.id)]=next;byName.set(key,next)}else{result.push(addition);byName.set(key,addition)}}return result};
const relationId=(name:string,areas:AppData['areas'],skills:AppData['skills'])=>areas.find(item=>normalize(item.name)===normalize(name))?.id||skills.find(item=>normalize(item.name)===normalize(name))?.id;
export function bootstrapUserProfile(snapshot:RepositorySnapshot):RepositorySnapshot{const data=snapshot.data;const interests=mergeNames(data.interests||[],profileInterests,(current,addition)=>({...current,relatedInterests:Array.from(new Set([...current.relatedInterests,...addition.relatedInterests])),tags:Array.from(new Set([...current.tags,...addition.tags]))}));const areas=mergeNames(data.areas,profileAreas,(current,addition)=>({...current,description:current.description||addition.description,focus:current.focus||addition.focus,longTermGoal:current.longTermGoal||addition.longTermGoal,topics:Array.from(new Set([...current.topics,...addition.topics]))}));const skills=mergeNames(data.skills,profileSkills,(current,addition)=>({...current,target:current.target||addition.target,focus:current.focus||addition.focus}));const goals=[...(data.goals||[])];for(const goal of profileGoals){if(!goals.some(item=>normalize(item.title)===normalize(goal.title)))goals.push(goal)}const existing=snapshot.relations||[];const relations=[...existing];for(const relation of profileRelations){const sourceId=relationId(relation.sourceId,areas,skills);const targetId=relationId(relation.targetId,areas,skills);if(!sourceId||!targetId)continue;if(!relations.some(item=>item.sourceId===sourceId&&item.targetId===targetId&&item.relationType===relation.relationType))relations.push({id:`profile-relation-${normalize(relation.sourceId)}-${normalize(relation.targetId)}-${relation.relationType}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),sourceType:areas.some(item=>item.id===sourceId)?'LearningArea':'Skill',sourceId,relationType:relation.relationType,targetType:areas.some(item=>item.id===targetId)?'LearningArea':'Skill',targetId})}const next={...snapshot,data:{...data,areas,skills,goals,interests},relations};if(snapshot.legacy?.['personal-profile-version']!==1){next.legacy={...(snapshot.legacy||{}),'personal-profile-version':1};saveSnapshot(next)}return next;}
