import type { AppData, EntityRelation, RepositorySnapshot } from '../domain/types';
import { profileAreas, profileGoals, profileRelations, profileSkills } from '../domain/userProfileSeed';
import { profileInterests, profileInterestAdditions, profileInterestAliases } from '../domain/interests';
import { saveSnapshot } from '../repositories/appRepository';
import { DEFAULT_WEEKLY_ROUTINE } from '../domain/weeklyRoutine';
import type { Project } from '../domain/types';

const normalize=(value:string)=>String(value||'').toLowerCase().replace(/[–—‑]/g,'-').replace(/[^a-z0-9]+/g,'');
const mergeNames=<T extends {id:string;name:string}>(existing:T[], additions:T[], merge:(current:T,addition:T)=>T)=>{const result=[...existing];const byName=new Map(result.map(item=>[normalize(item.name),item]));for(const addition of additions){const key=normalize(addition.name);const current=byName.get(key);if(current){const next=merge(current,addition);result[result.findIndex(item=>item.id===current.id)]=next;byName.set(key,next)}else{result.push(addition);byName.set(key,addition)}}return result};
const relationId=(name:string,areas:AppData['areas'],skills:AppData['skills'])=>areas.find(item=>normalize(item.name)===normalize(name))?.id||skills.find(item=>normalize(item.name)===normalize(name))?.id;
const researchProjects:Array<Project&{matches:string[]}>= [
 {id:'project-meg-semantic',name:'Wang Haiteng / Ray Dolan Lab — MEG Semantic Decoding',type:'Research project',status:'In progress',progress:0,deadline:'No deadline',meta:'Long-term high priority · implement RNN, CNN and Transformer before MEG semantic decoding',next:'Implement the next model component from first principles',color:'#7267d9',matches:['wanghaiteng','raydolan','semanticdecoding']},
 {id:'project-neur0002-agency',name:'Patrick Haggard + Chunlin — NEUR0002 Literature Review',type:'Research project',status:'In progress',progress:0,deadline:'No deadline',meta:'AI effects on human sense of agency · literature reading, synthesis and 4000-word review',next:'Read and critically annotate the next paper',color:'#5f9fd6',matches:['patrickhaggard','neur0002','senseofagency']},
 {id:'project-maze-reconstruction',name:'Zhou Xiaoyu — Maze Reconstruction Project',type:'Research project',status:'In progress',progress:0,deadline:'No deadline',meta:'Independent technical project · stable weekly reconstruction and cognitive modelling work',next:'Continue the next technical reconstruction step',color:'#52a68a',matches:['zhouxiaoyu','mazereconstruction']},
 {id:'project-metacognition-anika',name:'Anika Bolt — Metacognition Experiment',type:'Research project',status:'In progress',progress:0,deadline:'No deadline',meta:'Two flexible 3-hour experiment blocks per week · two participants per block',next:'Confirm participant availability for the next experiment block',color:'#d68b61',matches:['anikabolt','metacognitionexperiment']},
 {id:'project-boredom-agency',name:'Tal Nahari + Denis Lan — Boredom × Agency',type:'Research project',status:'In progress',progress:0,deadline:'No deadline',meta:'Maintenance mode · await data/results and follow up when needed',next:'Check for results or follow-up actions',color:'#a47bc2',matches:['talnahari','denislan','boredomagency']},
];
export function bootstrapUserProfile(snapshot:RepositorySnapshot):RepositorySnapshot{const data={...snapshot.data,areas:Array.isArray(snapshot.data.areas)?snapshot.data.areas:[],skills:Array.isArray(snapshot.data.skills)?snapshot.data.skills:[],goals:Array.isArray(snapshot.data.goals)?snapshot.data.goals:[],interests:Array.isArray(snapshot.data.interests)?snapshot.data.interests:[],projects:Array.isArray(snapshot.data.projects)?snapshot.data.projects:[],weeklyRoutine:snapshot.data.weeklyRoutine||DEFAULT_WEEKLY_ROUTINE};const interests=mergeNames(data.interests||[],[...profileInterests,...profileInterestAdditions,...profileInterestAliases],(current,addition)=>({...current,relatedInterests:Array.from(new Set([...(current.relatedInterests||[]),...addition.relatedInterests])),tags:Array.from(new Set([...(current.tags||[]),...addition.tags]))}));const areas=mergeNames(data.areas,profileAreas,(current,addition)=>({...current,description:current.description||addition.description,focus:current.focus||addition.focus,longTermGoal:current.longTermGoal||addition.longTermGoal,topics:Array.from(new Set([...current.topics,...addition.topics]))}));const skills=mergeNames(data.skills,profileSkills,(current,addition)=>({...current,target:current.target||addition.target,focus:current.focus||addition.focus}));const goals=[...(data.goals||[])];for(const goal of profileGoals){if(!goals.some(item=>normalize(item.title)===normalize(goal.title)))goals.push(goal)}const projects=[...data.projects];for(const project of researchProjects){if(!projects.some(item=>project.matches.some(match=>normalize(`${item.name} ${item.meta}`).includes(match)))){const{matches:_,...value}=project;projects.push(value)}}const existing=snapshot.relations||[];const relations=[...existing];for(const relation of profileRelations){const sourceId=relationId(relation.sourceId,areas,skills);const targetId=relationId(relation.targetId,areas,skills);if(!sourceId||!targetId)continue;if(!relations.some(item=>item.sourceId===sourceId&&item.targetId===targetId&&item.relationType===relation.relationType))relations.push({id:`profile-relation-${normalize(relation.sourceId)}-${normalize(relation.targetId)}-${relation.relationType}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),sourceType:areas.some(item=>item.id===sourceId)?'LearningArea':'Skill',sourceId,relationType:relation.relationType,targetType:areas.some(item=>item.id===targetId)?'LearningArea':'Skill',targetId})}const next={...snapshot,data:{...data,areas,skills,goals,projects,interests},relations};if(snapshot.legacy?.['personal-profile-version']!==5){next.legacy={...(snapshot.legacy||{}),'personal-profile-version':5};saveSnapshot(next)}return next;}
