import type { Quest } from '../domain/quests';

export type QuestSeedType='DAILY'|'WEEKLY'|'CHALLENGE'|'PROMOTION'|'BOSS';
export interface QuestSeed { id:string; area:string; canonicalArea?:string; parentArea?:string; type:QuestSeedType; rank?:string; targetRank?:string; difficulty:1|2|3|4|5; estimatedMinutes:number; cooldownDays:number; weight:number; prerequisites:string[]; tags:string[]; title:string; description?:string; acceptanceCriteria?:string[]; evidenceType?:string; enabled?:boolean; locale?:string; version?:string }
const types=new Set<QuestSeedType>(['DAILY','WEEKLY','CHALLENGE','PROMOTION','BOSS']);
const slug=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9\u4e00-\u9fff]+/g,'-');
export function validateQuestPool(input:unknown){const raw=Array.isArray(input)?input:(input as any)?.quests||(input as any)?.templates;if(!Array.isArray(raw))throw new Error('Quest Pool must be an array or an object with quests.');const ids=new Set<string>();const quests:QuestSeed[]=raw.map((item:any,index)=>{const id=String(item.id||`imported-${slug(item.title||item.name||'quest')}-${index}`);if(ids.has(id))throw new Error(`Duplicate quest id: ${id}`);ids.add(id);const type=String(item.type||'DAILY').toUpperCase() as QuestSeedType;if(!types.has(type))throw new Error(`Unsupported quest type: ${type}`);const area=String(item.area||item.targetName||item.canonicalArea||'Custom board');return{id,area,canonicalArea:String(item.canonicalArea||area),parentArea:item.parentArea?String(item.parentArea):undefined,type,rank:item.rank?String(item.rank):'R1',targetRank:item.targetRank?String(item.targetRank):undefined,difficulty:Math.min(5,Math.max(1,Number(item.difficulty||1))) as QuestSeed['difficulty'],estimatedMinutes:Math.max(1,Number(item.estimatedMinutes||item.minutes||15)),cooldownDays:Math.max(0,Number(item.cooldownDays||0)),weight:Math.max(0,Number(item.weight||1)),prerequisites:Array.isArray(item.prerequisites)?item.prerequisites.map(String):[],tags:Array.isArray(item.tags)?item.tags.map(String):[],title:String(item.title||item.name||'Imported quest'),description:item.description?String(item.description):'',acceptanceCriteria:Array.isArray(item.acceptanceCriteria)?item.acceptanceCriteria.map(String):[],evidenceType:item.evidenceType?String(item.evidenceType):undefined,enabled:item.enabled!==false,locale:item.locale?String(item.locale):'en',version:item.version?String(item.version):'1.0'} });return quests}
export function seedToQuest(seed:QuestSeed,targetId:string):Quest{return{id:seed.id,title:seed.title,description:seed.description||'',type:seed.type,targetId,targetName:seed.area,minutes:seed.estimatedMinutes,difficulty:seed.difficulty,prerequisites:seed.prerequisites,status:'available',createdAt:new Date().toISOString(),source:'imported'}}
export const questPoolRules={canonicalAreas:64,dailyPerRotation:3,weeklyPerRotation:3,majorQuestTypes:['CHALLENGE','PROMOTION','BOSS'] as QuestSeedType[],cooldownRequired:true,weightedSelection:true,prerequisitesSupported:true,evidenceRequiredFor:['WEEKLY','CHALLENGE','PROMOTION','BOSS'] as QuestSeedType[],aliases:['canonicalArea','parentArea','targetName','area'],acceptedContainers:['array','quests','templates'] as const};
