import type { ItemDefinition, InventoryItem, RewardCurrency, RewardState, RewardTransaction } from '../domain/types';
import { localDateKey } from '../domain/date';
import { loadSnapshot, saveSnapshot } from '../repositories/appRepository';

export const SHOP_ITEMS:ItemDefinition[]=[
 {id:'game-15',name:'15m Game Time Voucher',description:'Adds 15 minutes to today’s purchased gaming allowance.',category:'GAME_TIME',rarity:'COMMON',stackable:true,effectType:'GAMING_MINUTES',effectValue:15,shopAvailable:true,shopPrice:15,shopCurrency:'CREDITS',icon:'🎮',active:true},
 {id:'game-30',name:'30m Game Time Voucher',description:'Adds 30 minutes to today’s purchased gaming allowance.',category:'GAME_TIME',rarity:'COMMON',stackable:true,effectType:'GAMING_MINUTES',effectValue:30,shopAvailable:true,shopPrice:28,shopCurrency:'CREDITS',icon:'🎮',active:true},
 {id:'game-60',name:'60m Game Time Voucher',description:'Adds 60 minutes to today’s purchased gaming allowance.',category:'GAME_TIME',rarity:'UNCOMMON',stackable:true,effectType:'GAMING_MINUTES',effectValue:60,shopAvailable:true,shopPrice:52,shopCurrency:'CREDITS',icon:'🎮',active:true},
 {id:'daily-reroll',name:'Daily Quest Reroll',description:'A single reroll for an eligible daily quest.',category:'QUEST',rarity:'UNCOMMON',stackable:true,shopAvailable:true,shopPrice:20,shopCurrency:'CREDITS',icon:'↻',active:true},
 {id:'quest-freeze',name:'Quest Freeze',description:'Protects an eligible daily quest from expiring.',category:'QUEST',rarity:'RARE',stackable:true,shopAvailable:true,shopPrice:35,shopCurrency:'CREDITS',icon:'❄',active:true},
 {id:'weekly-reroll',name:'Weekly Quest Reroll',description:'A single reroll for an eligible weekly quest.',category:'QUEST',rarity:'RARE',stackable:true,shopAvailable:false,icon:'↻',active:true},
 {id:'double-reward',name:'Double Reward Token',description:'Doubles the next eligible Credits reward only.',category:'BOOST',rarity:'VERY_RARE',stackable:true,shopAvailable:false,icon:'✦',active:true},
];
const id=()=>`reward-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const tx=(currencyType:RewardCurrency,amount:number,direction:RewardTransaction['direction'],reason:string,sourceType?:string,sourceId?:string):RewardTransaction=>({id:id(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),currencyType,amount,direction,reason,sourceType,sourceId});
export function getRewardState():RewardState{return loadSnapshot().rewards}
export function updateRewardConfig(changes:Partial<RewardState['config']>){const snapshot=loadSnapshot();const config={...snapshot.rewards.config,...changes};saveSnapshot({...snapshot,rewards:{...snapshot.rewards,config}});return config}
export function grantReward(amount:number,reason:string,sourceType='Quest',sourceId?:string,extra:{tickets?:number;masterTokens?:number}={}){const snapshot=loadSnapshot();if(sourceId&&snapshot.rewards.transactions.some(item=>item.sourceId===sourceId&&item.sourceType===sourceType))return snapshot.rewards;const created=[tx('CREDITS',amount,'EARN',reason,sourceType,sourceId)];if(extra.tickets)created.push(tx('TICKETS',extra.tickets,'EARN',reason,sourceType,sourceId));if(extra.masterTokens)created.push(tx('MASTER_TOKENS',extra.masterTokens,'EARN',reason,sourceType,sourceId));const rewards={...snapshot.rewards,credits:snapshot.rewards.credits+amount,tickets:snapshot.rewards.tickets+(extra.tickets||0),masterTokens:snapshot.rewards.masterTokens+(extra.masterTokens||0),transactions:[...created,...snapshot.rewards.transactions].slice(0,2000)};saveSnapshot({...snapshot,rewards});return rewards}
export function purchaseItem(item:ItemDefinition){const snapshot=loadSnapshot();const price=snapshot.rewards.config.gameVoucherPrices[item.id]??item.shopPrice??0;if(item.shopCurrency!=='CREDITS'||snapshot.rewards.credits<price)return false;const now=new Date().toISOString();const inventory=[...snapshot.rewards.inventory];const found=inventory.find(x=>x.itemDefinitionId===item.id);if(found)found.quantity+=1;else inventory.unshift({id:id(),createdAt:now,updatedAt:now,itemDefinitionId:item.id,quantity:1,acquiredAt:now,source:'Shop'} as InventoryItem);const rewards={...snapshot.rewards,credits:snapshot.rewards.credits-price,inventory,transactions:[tx('CREDITS',price,'SPEND',`Purchased ${item.name}`,'Shop',item.id),...snapshot.rewards.transactions].slice(0,2000),inventoryTransactions:[{id:id(),createdAt:now,updatedAt:now,itemDefinitionId:item.id,quantity:1,direction:'ADD' as const,reason:'Shop purchase'},...snapshot.rewards.inventoryTransactions].slice(0,2000)};saveSnapshot({...snapshot,rewards});return true}
export function activateVoucher(item:ItemDefinition){if(item.category!=='GAME_TIME'||!item.effectValue)return false;const snapshot=loadSnapshot();const inventory=snapshot.rewards.inventory.find(x=>x.itemDefinitionId===item.id);if(!inventory||inventory.quantity<1)return false;const date=localDateKey();const existing=snapshot.rewards.allowances.find(x=>x.date===date)||{date,baseMinutes:60,activatedVoucherMinutes:0,bonusMinutes:0,usedMinutes:0,overageMinutes:0};const cap=[0,6].includes(new Date().getDay())?snapshot.rewards.config.weekendActivationCap:snapshot.rewards.config.weekdayActivationCap;if(existing.activatedVoucherMinutes+item.effectValue>cap)return false;inventory.quantity-=1;const rewards={...snapshot.rewards,inventory:snapshot.rewards.inventory,allowances:[...snapshot.rewards.allowances.filter(x=>x.date!==date),{...existing,activatedVoucherMinutes:existing.activatedVoucherMinutes+item.effectValue}],inventoryTransactions:[{id:id(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),itemDefinitionId:item.id,quantity:1,direction:'REMOVE' as const,reason:'Activated game voucher'},...snapshot.rewards.inventoryTransactions]};saveSnapshot({...snapshot,rewards});return true}
export function getGamingAllowance(date=localDateKey()){const rewards=getRewardState();return rewards.allowances.find(x=>x.date===date)||{date,baseMinutes:60,activatedVoucherMinutes:0,bonusMinutes:0,usedMinutes:0,overageMinutes:0}}
export function getRewardAnalytics(){const snapshot=loadSnapshot();const since=new Date();since.setDate(since.getDate()-6);const transactions=snapshot.rewards.transactions.filter(item=>new Date(item.createdAt)>=since);const entries=snapshot.timeEntries.filter(item=>item.category==='Entertainment'&&item.entertainmentSubtype==='Gaming'&&new Date(item.endedAt)>=since);return{earned:transactions.filter(item=>item.currencyType==='CREDITS'&&item.direction==='EARN').reduce((sum,item)=>sum+item.amount,0),spent:transactions.filter(item=>item.currencyType==='CREDITS'&&item.direction==='SPEND').reduce((sum,item)=>sum+item.amount,0),tickets:transactions.filter(item=>item.currencyType==='TICKETS'&&item.direction==='EARN').reduce((sum,item)=>sum+item.amount,0),masterTokens:transactions.filter(item=>item.currencyType==='MASTER_TOKENS'&&item.direction==='EARN').reduce((sum,item)=>sum+item.amount,0),gamingMinutes:entries.reduce((sum,item)=>sum+item.durationMinutes,0),gamingOverage:snapshot.rewards.allowances.filter(item=>new Date(item.date)>=since).reduce((sum,item)=>sum+item.overageMinutes,0)}}
export function consumeGamingMinutes(minutes:number,date=localDateKey()){const snapshot=loadSnapshot();const current=snapshot.rewards.allowances.find(x=>x.date===date)||{date,baseMinutes:60,activatedVoucherMinutes:0,bonusMinutes:0,usedMinutes:0,overageMinutes:0};const available=current.baseMinutes+current.activatedVoucherMinutes+current.bonusMinutes;const next={...current,usedMinutes:current.usedMinutes+minutes,overageMinutes:Math.max(0,current.usedMinutes+minutes-available)};saveSnapshot({...snapshot,rewards:{...snapshot.rewards,allowances:[...snapshot.rewards.allowances.filter(x=>x.date!==date),next]}});return next}
export function rewardForQuest(type:string,difficulty:number){if(type==='WEEKLY')return 25+difficulty*7;if(type==='CHALLENGE')return 40+difficulty*10;if(type==='PROMOTION')return 100;if(type==='BOSS')return 200;return [0,5,8,12,18,25][Math.max(1,Math.min(5,difficulty))]}
export function grantQuestReward(type:string,difficulty:number,sourceId:string,title:string){const snapshot=loadSnapshot();if(snapshot.rewards.transactions.some(item=>item.sourceType==='Quest'&&item.sourceId===sourceId))return snapshot.rewards;const previous=snapshot.rewards.transactions.filter(item=>item.sourceType==='Quest'&&item.reason.includes(title)).length;const multiplier=previous===0?1:previous===1?.5:.25;const base=rewardForQuest(type,difficulty);const credits=Math.round(base*multiplier*(snapshot.rewards.doubleRewardArmed?2:1));const rewards=grantReward(credits,`Completed ${type} quest: ${title}`,'Quest',sourceId,{tickets:type==='PROMOTION'?1:type==='BOSS'?2:0,masterTokens:type==='PROMOTION'?1:type==='BOSS'?2:0});if(snapshot.rewards.doubleRewardArmed){const latest=loadSnapshot();saveSnapshot({...latest,rewards:{...latest.rewards,doubleRewardArmed:false}})}const today=localDateKey();const dailyCount=loadSnapshot().rewards.transactions.filter(item=>item.sourceType==='Quest'&&item.direction==='EARN'&&item.createdAt.slice(0,10)===today).length;if(type==='DAILY'&&dailyCount>=3&&!loadSnapshot().rewards.transactions.some(item=>item.sourceType==='DailyBonus'&&item.createdAt.slice(0,10)===today))grantReward(10,'Complete 3 Daily Quests bonus','DailyBonus',today);maybeWeeklyConsistencyBonus();return rewards}
export function maybeWeeklyConsistencyBonus(){const snapshot=loadSnapshot();const today=new Date();const dates=new Set<string>();for(let offset=0;offset<7;offset++){const date=new Date(today);date.setDate(today.getDate()-offset);const key=localDateKey(date);if(snapshot.activities.some(item=>localDateKey(new Date(item.occurredAt))===key)||snapshot.timeEntries.some(item=>localDateKey(new Date(item.endedAt))===key))dates.add(key)}const weekKey=localDateKey(new Date(today.getFullYear(),today.getMonth(),today.getDate()-today.getDay()));if(dates.size>=5&&!snapshot.rewards.transactions.some(item=>item.sourceType==='WeeklyConsistency'&&item.sourceId===weekKey))grantReward(30,'5 of 7 days consistency bonus','WeeklyConsistency',weekKey);return dates.size>=5}
export function armDoubleReward(){const snapshot=loadSnapshot();const item=snapshot.rewards.inventory.find(x=>x.itemDefinitionId==='double-reward');if(!item||item.quantity<1)return false;item.quantity-=1;saveSnapshot({...snapshot,rewards:{...snapshot.rewards,doubleRewardArmed:true,inventory:snapshot.rewards.inventory,inventoryTransactions:[{id:id(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),itemDefinitionId:'double-reward',quantity:1,direction:'REMOVE',reason:'Armed Double Reward Token'},...snapshot.rewards.inventoryTransactions]}});return true}
export function maybeRewardDrop(type:string,difficulty:number,sourceId:string){const snapshot=loadSnapshot();if(snapshot.rewards.transactions.some(item=>item.sourceType==='RewardDrop'&&item.sourceId===sourceId))return null;const chance=type==='DAILY'?[0,.02,.03,.05,.07,.1][difficulty]||.02:type==='WEEKLY'?.12:type==='CHALLENGE'?.25:type==='PROMOTION'||type==='BOSS'?1:0;if(Math.random()>chance)return null;const pool=type==='BOSS'?[['game-60',1],['double-reward',1]]:type==='PROMOTION'?[['daily-reroll',1],['double-reward',1]]:type==='CHALLENGE'?[['game-30',1],['daily-reroll',1],['quest-freeze',1]]:[['daily-reroll',1],['game-15',1]];const picked=pool[Math.floor(Math.random()*pool.length)];const definition=SHOP_ITEMS.find(item=>item.id===picked[0]);if(!definition)return null;const now=new Date().toISOString();const inventory=[...snapshot.rewards.inventory];const found=inventory.find(item=>item.itemDefinitionId===definition.id);if(found)found.quantity+=1;else inventory.unshift({id:id(),createdAt:now,updatedAt:now,itemDefinitionId:definition.id,quantity:1,acquiredAt:now,source:'Quest drop'} as InventoryItem);const rewards={...snapshot.rewards,inventory,transactions:[tx('TICKETS',0, 'ADJUST',`Drop: ${definition.name}`,'RewardDrop',sourceId),...snapshot.rewards.transactions],inventoryTransactions:[{id:id(),createdAt:now,updatedAt:now,itemDefinitionId:definition.id,quantity:1,direction:'ADD' as const,reason:'Quest drop',sourceId},...snapshot.rewards.inventoryTransactions]};saveSnapshot({...snapshot,rewards});return definition}
export function drawReward(){const snapshot=loadSnapshot();if(snapshot.rewards.tickets<1)return null;const now=new Date().toISOString();const outcomes=[{kind:'credits',label:'+5 Credits',credits:5,weight:45},{kind:'credits',label:'+10 Credits',credits:10,weight:30},{kind:'item',label:'15m Game Time Voucher',itemId:'game-15',weight:15},{kind:'item',label:'Daily Quest Reroll',itemId:'daily-reroll',weight:8},{kind:'item',label:'30m Game Time Voucher',itemId:'game-30',weight:2}];let pick=Math.random()*outcomes.reduce((sum,item)=>sum+item.weight,0);const outcome=outcomes.find(item=>(pick-=item.weight)<=0)||outcomes[0];const transactions=[tx('TICKETS',1,'SPEND','Reward Draw','RewardDraw')];let inventory=[...snapshot.rewards.inventory];let inventoryTransactions=[...snapshot.rewards.inventoryTransactions];let credits=snapshot.rewards.credits;if(outcome.kind==='credits'){credits+=outcome.credits!;transactions.push(tx('CREDITS',outcome.credits!,'EARN',`Reward Draw: ${outcome.label}`,'RewardDraw'))}else{const existing=inventory.find(item=>item.itemDefinitionId===outcome.itemId);if(existing)existing.quantity+=1;else inventory.unshift({id:id(),createdAt:now,updatedAt:now,itemDefinitionId:outcome.itemId!,quantity:1,acquiredAt:now,source:'Reward Draw'} as InventoryItem);inventoryTransactions.unshift({id:id(),createdAt:now,updatedAt:now,itemDefinitionId:outcome.itemId!,quantity:1,direction:'ADD',reason:'Reward Draw'} as any)}const rewards={...snapshot.rewards,tickets:snapshot.rewards.tickets-1,credits,inventory,transactions:[...transactions,...snapshot.rewards.transactions].slice(0,2000),inventoryTransactions:inventoryTransactions.slice(0,2000)};saveSnapshot({...snapshot,rewards});return outcome}
