import type { ItemDefinition, InventoryItem, RewardCurrency, RewardState, RewardTransaction } from '../domain/types';
import { localDateKey } from '../domain/date';
import { loadSnapshot, saveSnapshot } from '../repositories/appRepository';

export const SHOP_ITEMS:ItemDefinition[]=[
 {id:'game-15',name:'15m Game Time Voucher',description:'Adds 15 minutes to today’s purchased gaming allowance.',category:'GAME_TIME',rarity:'COMMON',stackable:true,effectType:'GAMING_MINUTES',effectValue:15,shopAvailable:true,shopPrice:15,shopCurrency:'CREDITS',icon:'🎮',active:true},
 {id:'game-30',name:'30m Game Time Voucher',description:'Adds 30 minutes to today’s purchased gaming allowance.',category:'GAME_TIME',rarity:'COMMON',stackable:true,effectType:'GAMING_MINUTES',effectValue:30,shopAvailable:true,shopPrice:28,shopCurrency:'CREDITS',icon:'🎮',active:true},
 {id:'game-60',name:'60m Game Time Voucher',description:'Adds 60 minutes to today’s purchased gaming allowance.',category:'GAME_TIME',rarity:'UNCOMMON',stackable:true,effectType:'GAMING_MINUTES',effectValue:60,shopAvailable:true,shopPrice:52,shopCurrency:'CREDITS',icon:'🎮',active:true},
 {id:'daily-reroll',name:'Daily Quest Reroll',description:'A single reroll for an eligible daily quest.',category:'QUEST',rarity:'UNCOMMON',stackable:true,shopAvailable:true,shopPrice:20,shopCurrency:'CREDITS',icon:'↻',active:true},
 {id:'quest-freeze',name:'Quest Freeze',description:'Protects an eligible daily quest from expiring.',category:'QUEST',rarity:'RARE',stackable:true,shopAvailable:true,shopPrice:35,shopCurrency:'CREDITS',icon:'❄',active:true},
];
const id=()=>`reward-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const tx=(currencyType:RewardCurrency,amount:number,direction:RewardTransaction['direction'],reason:string,sourceType?:string,sourceId?:string):RewardTransaction=>({id:id(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),currencyType,amount,direction,reason,sourceType,sourceId});
export function getRewardState():RewardState{return loadSnapshot().rewards}
export function grantReward(amount:number,reason:string,sourceType='Quest',sourceId?:string,extra:{tickets?:number;masterTokens?:number}={}){const snapshot=loadSnapshot();if(sourceId&&snapshot.rewards.transactions.some(item=>item.sourceId===sourceId&&item.sourceType===sourceType))return snapshot.rewards;const created=[tx('CREDITS',amount,'EARN',reason,sourceType,sourceId)];if(extra.tickets)created.push(tx('TICKETS',extra.tickets,'EARN',reason,sourceType,sourceId));if(extra.masterTokens)created.push(tx('MASTER_TOKENS',extra.masterTokens,'EARN',reason,sourceType,sourceId));const rewards={...snapshot.rewards,credits:snapshot.rewards.credits+amount,tickets:snapshot.rewards.tickets+(extra.tickets||0),masterTokens:snapshot.rewards.masterTokens+(extra.masterTokens||0),transactions:[...created,...snapshot.rewards.transactions].slice(0,2000)};saveSnapshot({...snapshot,rewards});return rewards}
export function purchaseItem(item:ItemDefinition){const snapshot=loadSnapshot();const price=item.shopPrice||0;if(item.shopCurrency!=='CREDITS'||snapshot.rewards.credits<price)return false;const now=new Date().toISOString();const inventory=[...snapshot.rewards.inventory];const found=inventory.find(x=>x.itemDefinitionId===item.id);if(found)found.quantity+=1;else inventory.unshift({id:id(),createdAt:now,updatedAt:now,itemDefinitionId:item.id,quantity:1,acquiredAt:now,source:'Shop'} as InventoryItem);const rewards={...snapshot.rewards,credits:snapshot.rewards.credits-price,inventory,transactions:[tx('CREDITS',price,'SPEND',`Purchased ${item.name}`,'Shop',item.id),...snapshot.rewards.transactions].slice(0,2000),inventoryTransactions:[{id:id(),createdAt:now,updatedAt:now,itemDefinitionId:item.id,quantity:1,direction:'ADD' as const,reason:'Shop purchase'},...snapshot.rewards.inventoryTransactions].slice(0,2000)};saveSnapshot({...snapshot,rewards});return true}
export function activateVoucher(item:ItemDefinition){if(item.category!=='GAME_TIME'||!item.effectValue)return false;const snapshot=loadSnapshot();const inventory=snapshot.rewards.inventory.find(x=>x.itemDefinitionId===item.id);if(!inventory||inventory.quantity<1)return false;const date=localDateKey();const existing=snapshot.rewards.allowances.find(x=>x.date===date)||{date,baseMinutes:60,activatedVoucherMinutes:0,bonusMinutes:0,usedMinutes:0,overageMinutes:0};const cap=[0,6].includes(new Date().getDay())?180:120;if(existing.activatedVoucherMinutes+item.effectValue>cap)return false;inventory.quantity-=1;const rewards={...snapshot.rewards,inventory:snapshot.rewards.inventory,allowances:[...snapshot.rewards.allowances.filter(x=>x.date!==date),{...existing,activatedVoucherMinutes:existing.activatedVoucherMinutes+item.effectValue}],inventoryTransactions:[{id:id(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),itemDefinitionId:item.id,quantity:1,direction:'REMOVE' as const,reason:'Activated game voucher'},...snapshot.rewards.inventoryTransactions]};saveSnapshot({...snapshot,rewards});return true}
export function getGamingAllowance(date=localDateKey()){const rewards=getRewardState();return rewards.allowances.find(x=>x.date===date)||{date,baseMinutes:60,activatedVoucherMinutes:0,bonusMinutes:0,usedMinutes:0,overageMinutes:0}}
export function consumeGamingMinutes(minutes:number,date=localDateKey()){const snapshot=loadSnapshot();const current=snapshot.rewards.allowances.find(x=>x.date===date)||{date,baseMinutes:60,activatedVoucherMinutes:0,bonusMinutes:0,usedMinutes:0,overageMinutes:0};const available=current.baseMinutes+current.activatedVoucherMinutes+current.bonusMinutes;const next={...current,usedMinutes:current.usedMinutes+minutes,overageMinutes:Math.max(0,current.usedMinutes+minutes-available)};saveSnapshot({...snapshot,rewards:{...snapshot.rewards,allowances:[...snapshot.rewards.allowances.filter(x=>x.date!==date),next]}});return next}
export function rewardForQuest(type:string,difficulty:number){if(type==='WEEKLY')return 25+difficulty*7;if(type==='CHALLENGE')return 40+difficulty*10;if(type==='PROMOTION')return 100;if(type==='BOSS')return 200;return [0,5,8,12,18,25][Math.max(1,Math.min(5,difficulty))]}
export function drawReward(){const snapshot=loadSnapshot();if(snapshot.rewards.tickets<1)return null;const now=new Date().toISOString();const outcomes=[{kind:'credits',label:'+5 Credits',credits:5,weight:45},{kind:'credits',label:'+10 Credits',credits:10,weight:30},{kind:'item',label:'15m Game Time Voucher',itemId:'game-15',weight:15},{kind:'item',label:'Daily Quest Reroll',itemId:'daily-reroll',weight:8},{kind:'item',label:'30m Game Time Voucher',itemId:'game-30',weight:2}];let pick=Math.random()*outcomes.reduce((sum,item)=>sum+item.weight,0);const outcome=outcomes.find(item=>(pick-=item.weight)<=0)||outcomes[0];const transactions=[tx('TICKETS',1,'SPEND','Reward Draw','RewardDraw')];let inventory=[...snapshot.rewards.inventory];let inventoryTransactions=[...snapshot.rewards.inventoryTransactions];let credits=snapshot.rewards.credits;if(outcome.kind==='credits'){credits+=outcome.credits!;transactions.push(tx('CREDITS',outcome.credits!,'EARN',`Reward Draw: ${outcome.label}`,'RewardDraw'))}else{const existing=inventory.find(item=>item.itemDefinitionId===outcome.itemId);if(existing)existing.quantity+=1;else inventory.unshift({id:id(),createdAt:now,updatedAt:now,itemDefinitionId:outcome.itemId!,quantity:1,acquiredAt:now,source:'Reward Draw'} as InventoryItem);inventoryTransactions.unshift({id:id(),createdAt:now,updatedAt:now,itemDefinitionId:outcome.itemId!,quantity:1,direction:'ADD',reason:'Reward Draw'} as any)}const rewards={...snapshot.rewards,tickets:snapshot.rewards.tickets-1,credits,inventory,transactions:[...transactions,...snapshot.rewards.transactions].slice(0,2000),inventoryTransactions:inventoryTransactions.slice(0,2000)};saveSnapshot({...snapshot,rewards});return outcome}
