import { useSyncExternalStore } from 'react';
import type { Activity, ActivityEntity, AppData, HabitLog, LearningArea, Project, Skill, SkillLog, Task, TaskCompletion } from '../domain/types';
import { loadSnapshot, saveSnapshot } from '../repositories/appRepository';
import type { RepositorySnapshot } from '../domain/types';
import { calculateHabitBestStreak, calculateHabitStreak, upsertHabitLog } from '../services/habitService';
import { bootstrapUserProfile } from '../services/profileBootstrapService';
import { seed } from '../domain/seed';
import { localDateKey } from '../domain/date';
import { completeQuest, undoQuest, type QuestBoardState } from '../domain/questActions';

type Updater=AppData|((data:AppData)=>AppData);
const listeners=new Set<()=>void>();
let repository=bootstrapUserProfile(loadSnapshot());
let currentData:AppData=repository.data||seed;

const now=()=>new Date().toISOString();
const notify=()=>listeners.forEach(listener=>listener());
const saveData=(next:AppData)=>{currentData=next;repository={...loadSnapshot(),data:next,updatedAt:now()};saveSnapshot(repository);notify()};
const activity=(type:ActivityEntity['type'],title:string,source:string,metadata:Record<string,unknown>,durationMinutes?:number):ActivityEntity=>{const timestamp=now();return{id:`activity-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:timestamp,updatedAt:timestamp,type,title,occurredAt:timestamp,source,metadata,durationMinutes}};
const legacyActivity=(item:ActivityEntity):Activity=>({id:item.id,label:item.title,type:item.type,time:'Just now',meta:item.durationMinutes?`${item.durationMinutes} minutes · ${item.source||'Activity'}`:item.source||'Activity'});
const commitEvent=(next:AppData,event:ActivityEntity)=>{next.activities=[legacyActivity(event),...next.activities].slice(0,500);const latest=loadSnapshot();repository={...latest,activities:[event,...latest.activities].slice(0,500),data:next,updatedAt:now()};currentData=next;saveSnapshot(repository);notify()};

export function setAppData(updater:Updater){saveData(typeof updater==='function'?updater(currentData):updater)}
export function getAppData(){return currentData}
export function getAppSnapshot(){return {...loadSnapshot(),data:currentData}}
export function restoreAppSnapshot(snapshot:RepositorySnapshot){repository={...snapshot,schemaVersion:6,updatedAt:now()};currentData=repository.data;saveSnapshot(repository);notify()}
export function subscribeAppStore(listener:()=>void){listeners.add(listener);return()=>listeners.delete(listener)}

export function useAppStore(){
  const data=useSyncExternalStore(subscribeAppStore,()=>currentData,()=>currentData);
  const setData=(updater:Updater)=>setAppData(updater);
  const toggleTask=(id:string)=>{const task=currentData.tasks.find(item=>item.id===id);if(!task)return;const done=task.status!=='done';const date=localDateKey();const timestamp=now();const next:AppData={...currentData,tasks:currentData.tasks.map(item=>item.id===id?{...item,status:done?'done':'todo',completedAt:done?timestamp:undefined}:item)};const questId=task.questId||task.notes?.match(/^Quest:\s*(.+)$/)?.[1];if(questId){try{const board=JSON.parse(localStorage.getItem('personal-life-os-quest-board-v1')||'{"ranks":[],"quests":[]}') as QuestBoardState;const updated=done?completeQuest(board,questId,'',timestamp):undoQuest(board,questId);localStorage.setItem('personal-life-os-quest-board-v1',JSON.stringify(updated))}catch{}}if(task.areaId)next.areas=next.areas.map(item=>item.id===task.areaId?{...item,progress:Math.max(0,Math.min(100,item.progress+(done?2:-2)))}:item);if(task.skillId)next.skills=next.skills.map(item=>item.id===task.skillId?{...item,progress:Math.max(0,Math.min(100,item.progress+(done?2:-2))),lastPracticed:done?date:item.lastPracticed}:item);if(task.habitId){const habit=next.habits.find(item=>item.id===task.habitId);if(habit){const log:HabitLog={id:`habit-log-${Date.now()}`,createdAt:timestamp,updatedAt:timestamp,habitId:habit.id,date,completed:done};const logs=upsertHabitLog(repository.habitLogs,log);next.habits=next.habits.map(item=>item.id===habit.id?{...item,checked:done,streak:calculateHabitStreak(item.id,logs,item.frequency,item.target,date),best:Math.max(item.best,calculateHabitBestStreak(item.id,logs,item.frequency,item.target))}:item);repository={...repository,habitLogs:logs}}}if(done){const completion:TaskCompletion={id:`completion-${Date.now()}`,createdAt:timestamp,updatedAt:timestamp,taskId:id,completedAt:timestamp,source:task.source||'Task'};repository={...repository,taskCompletions:[completion,...repository.taskCompletions].slice(0,1000)}}commitEvent(next,activity(done?'TaskCompleted':'Custom',task.title,task.source||'Task',{taskId:id,completed:done}));};
  const toggleHabit=(id:string)=>{const habit=currentData.habits.find(item=>item.id===id);if(!habit)return;const completed=!habit.checked;const date=localDateKey();const timestamp=now();const log:HabitLog={id:`habit-log-${Date.now()}`,createdAt:timestamp,updatedAt:timestamp,habitId:id,date,completed};const logs=upsertHabitLog(repository.habitLogs,log);const streak=calculateHabitStreak(id,logs,habit.frequency,habit.target,date);const best=calculateHabitBestStreak(id,logs,habit.frequency,habit.target);const next:AppData={...currentData,habits:currentData.habits.map(item=>item.id===id?{...item,checked:completed,streak,best}:item),tasks:currentData.tasks.map(item=>item.habitId===id&&item.scheduledDate===date?{...item,status:completed?'done':'todo',completedAt:completed?timestamp:undefined}:item)};repository={...repository,habitLogs:logs};commitEvent(next,activity(completed?'HabitCompleted':'Custom',habit.name,'Habit',{habitId:id,completed}))};
  const updateLog=(field:keyof AppData['log'],value:string|number)=>setAppData(data=>({...data,log:{...data.log,[field]:value}}));
  const addArea=(name:string)=>setAppData(data=>{const area:LearningArea={id:`area-${Date.now()}`,name,description:'A new direction to explore and develop.',priority:'Medium',status:'Active',progress:0,focus:'Choose a current focus',topics:[],color:'#8b7cf6'};return{...data,areas:[...data.areas,area]}});
  const addSkill=(name:string)=>setAppData(data=>{const skill:Skill={id:`skill-${Date.now()}`,name,level:'Beginner',target:'Intermediate',practiceCount:0,minutes:0,lastPracticed:'Not yet',focus:'Choose what to practice next',progress:0};return{...data,skills:[...data.skills,skill]}});
  const deleteArea=(id:string)=>setAppData(data=>({...data,areas:data.areas.filter(item=>item.id!==id)}));
  const deleteSkill=(id:string)=>setAppData(data=>({...data,skills:data.skills.filter(item=>item.id!==id)}));
  const practiceSkill=(id:string,minutes:number)=>{const skill=currentData.skills.find(item=>item.id===id);if(!skill)return;const timestamp=now();const log:SkillLog={id:`skill-log-${Date.now()}`,createdAt:timestamp,updatedAt:timestamp,skillId:id,durationMinutes:minutes,occurredAt:timestamp};repository={...repository,skillLogs:[log,...repository.skillLogs].slice(0,2000)};commitEvent({...currentData,skills:currentData.skills.map(item=>item.id===id?{...item,practiceCount:item.practiceCount+1,minutes:item.minutes+minutes,lastPracticed:localDateKey(),progress:Math.min(100,item.progress+2),progressLog:[{date:localDateKey(),minutes,note:''},...(item.progressLog||[])].slice(0,100)}:item)},activity('SkillPractice',`Practiced ${skill.name}`,'Skill',{skillId:id},minutes))};
  const addProject=(name:string)=>setAppData(data=>({...data,projects:[...data.projects,{id:`project-${Date.now()}`,name,type:'Personal project',status:'Planning',progress:0,deadline:'No deadline',meta:'New project',next:'Define the next step',color:'#8b7cf6'}]}));
  const addGoal=(title:string)=>setAppData(data=>({...data,goals:[...data.goals,{id:`goal-${Date.now()}`,title,period:'Personal goal',progress:0,detail:'Just started'}]}));
  const deleteProject=(id:string)=>setAppData(data=>({...data,projects:data.projects.filter(item=>item.id!==id)}));
  const deleteGoal=(id:string)=>setAppData(data=>({...data,goals:data.goals.filter(item=>item.id!==id)}));
  const adjustTaskDifficulty=(id:string)=>setAppData(data=>{const levels=['Easy','Medium','Hard'] as const;return{...data,tasks:data.tasks.map(item=>item.id===id?{...item,difficulty:levels[(levels.indexOf(item.difficulty)+1)%levels.length]}:item)}});
  const autoTuneDifficulty=()=>setAppData(data=>{const daily=data.tasks.filter(item=>item.category==='Daily progress');const ratio=daily.filter(item=>item.status==='done').length/Math.max(daily.length,1);const direction=ratio>=.7?1:ratio<=.3?-1:0;if(!direction)return data;const levels=['Easy','Medium','Hard'] as const;return{...data,tasks:data.tasks.map(item=>{if(item.category!=='Daily progress'||item.status==='done')return item;const index=levels.indexOf(item.difficulty);return{...item,difficulty:levels[Math.max(0,Math.min(2,index+direction))]}})}});
  const generateDailyTasks=(force=false)=>setAppData(data=>{const base=force?{...data,tasks:data.tasks.filter(item=>item.category!=='Daily progress'||item.status==='done')}:data;if(base.tasks.filter(item=>item.category==='Daily progress').length>=6)return data;const area=base.areas.find(item=>item.status==='Active');const skill=base.skills.find(item=>item.progress<100);const additions=[area&&{id:`task-${Date.now()}-area`,title:`Review one ${area.name} concept`,description:`Spend 15 minutes on your current focus: ${area.focus}.`,minutes:15,difficulty:'Easy' as const,category:'Daily progress' as const,areaId:area.id,status:'todo' as const},skill&&{id:`task-${Date.now()}-skill`,title:`Practice ${skill.name} for 20 minutes`,description:`Make one small exercise around: ${skill.focus}.`,minutes:20,difficulty:'Easy' as const,category:'Daily progress' as const,skillId:skill.id,status:'todo' as const}].filter(Boolean) as Task[];return{...base,tasks:[...base.tasks,...additions]}});
  return{data,setData,toggleTask,toggleHabit,updateLog,addArea,addSkill,deleteArea,deleteSkill,practiceSkill,addProject,addGoal,deleteProject,deleteGoal,generateDailyTasks,adjustTaskDifficulty,autoTuneDifficulty};
}
