import { useState } from 'react';
import Icon from './Icon';
import { requestAIRecommendations } from '../services/aiRecommendations';

export default function AIReviewPanel({ data }: { data: any }) {
  const [result, setResult] = useState(() => localStorage.getItem('personal-life-os-ai-review-latest') || '');
  const [history, setHistory] = useState<any[]>(() => { try { return JSON.parse(localStorage.getItem('personal-life-os-ai-review-history') || '[]'); } catch { return []; } });
  const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  const run = async () => { const endpoint = localStorage.getItem('personal-life-os-ai-endpoint') || ''; if (!endpoint) { setMessage('Add your Supabase Function URL in the AI Recommendations panel first.'); return; } setLoading(true); setMessage('Preparing your weekly review…'); try { const text = await requestAIRecommendations(endpoint, { goals: (data.goals || []).map((g:any) => g.title), areas: data.areas.map((a:any) => ({ name:a.name, focus:a.focus, progress:a.progress })), skills: data.skills.map((s:any) => ({ name:s.name, progress:s.progress, practiceCount:s.practiceCount })), tasks: data.tasks.map((t:any) => ({ title:t.title, status:t.status, difficulty:t.difficulty })), journal: data.log }); const entry = { id: Date.now().toString(), date: new Date().toISOString().slice(0,10), text }; const next = [entry, ...history].slice(0,12); setResult(text); setHistory(next); localStorage.setItem('personal-life-os-ai-review-latest', text); localStorage.setItem('personal-life-os-ai-review-history', JSON.stringify(next)); setMessage('Saved to review history'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to generate review'); } finally { setLoading(false); } };
  return <section className="ai-review-panel"><div className="ai-panel-head"><div><span className="pill teal">AI WEEKLY REVIEW</span><h2>Turn activity into a clearer next week.</h2><p className="muted">AI suggests patterns and next steps around the goals you already chose.</p></div><Icon name="Sparkles" size={22}/></div><div className="ai-review-actions"><button className="primary" onClick={run} disabled={loading}><Icon name="WandSparkles" size={16}/>{loading ? 'Reviewing…' : 'Generate weekly review'}</button>{message&&<span className="muted">{message}</span>}</div>{result&&<div className="ai-review-result"><div className="ai-review-result-head"><b>Latest review</b><span>{new Date().toLocaleDateString()}</span></div><p>{result}</p></div>}{history.length>0&&<details className="ai-review-history"><summary>Review history · {history.length}</summary>{history.slice(0,6).map(entry=><button key={entry.id} onClick={()=>setResult(entry.text)}><b>{entry.date}</b><span>{entry.text.slice(0,100)}…</span></button>)}</details>}</section>;
}
