import { useState } from 'react';
import Icon from './Icon';
import type { LearningArea, Priority } from '../domain/types';

export default function AreaEditor({ area, onCancel, onSave }: { area: LearningArea; onCancel: () => void; onSave: (area: LearningArea) => void }) {
  const [draft, setDraft] = useState({ ...area, topicsText: area.topics.join(', '), resourcesText: (area.resources || []).join('\n') });
  const update = (key: string, value: string) => setDraft(current => ({ ...current, [key]: value }));
  const save = () => onSave({ ...area, name: draft.name.trim() || area.name, description: draft.description, priority: draft.priority as Priority, status: draft.status as 'Active'|'Paused', focus: draft.focus, longTermGoal: draft.longTermGoal, notes: draft.notes, topics: draft.topicsText.split(',').map(item => item.trim()).filter(Boolean), resources: draft.resourcesText.split('\n').map(item => item.trim()).filter(Boolean) });
  return <div className="modal-backdrop" onMouseDown={onCancel}><form className="create-modal area-editor" onSubmit={event => { event.preventDefault(); save(); }} onMouseDown={event => event.stopPropagation()}><div className="modal-head"><div><span className="pill purple">LEARNING AREA</span><h2>Edit your direction</h2></div><button type="button" className="modal-close" onClick={onCancel}>×</button></div><label>Name<input autoFocus value={draft.name} onChange={event => update('name', event.target.value)}/></label><label>Description<textarea value={draft.description} onChange={event => update('description', event.target.value)} rows={2}/></label><div className="form-two"><label>Priority<select value={draft.priority} onChange={event => update('priority', event.target.value)}><option>Low</option><option>Medium</option><option>High</option></select></label><label>Status<select value={draft.status} onChange={event => update('status', event.target.value)}><option>Active</option><option>Paused</option></select></label></div><label>Long-term goal<input value={draft.longTermGoal || ''} onChange={event => update('longTermGoal', event.target.value)} placeholder="What would meaningful progress look like?"/></label><label>Current focus<input value={draft.focus} onChange={event => update('focus', event.target.value)}/></label><label>Topics <small>comma separated</small><input value={draft.topicsText} onChange={event => update('topicsText', event.target.value)} placeholder="e.g. EEG, signal processing, neural coding"/></label><label>Resources <small>one link or note per line</small><textarea value={draft.resourcesText} onChange={event => update('resourcesText', event.target.value)} rows={3} placeholder="https://…"/></label><label>Notes<textarea value={draft.notes || ''} onChange={event => update('notes', event.target.value)} rows={3}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary"><Icon name="Save" size={15}/> Save area</button></div></form></div>;
}
