import { useMemo, useState } from 'react';
import Icon from './Icon';
import { useAppStore } from '../store/useAppStore';
import type { LearningArea, Skill } from '../domain/types';

type Concept = { id:string; name:string; summary:string; tier:1|2|3|4; chapter:string; pageRange:string; difficulty:'Core'|'Advanced'; learned:boolean };
type Recall = { id:string; question:string; answer:string; conceptId:string; difficulty:'Easy'|'Medium'|'Hard'; nextReview:string; confidence:number };
type Book = { id:string; title:string; author:string; fileName:string; uploadedAt:string; status:'Ready'|'Processing'; progress:number; areaId?:string; skillId?:string; chapters:string[]; chunks:number; summary:string; concepts:Concept[]; recalls:Recall[]; sessions:{mode:string;completedAt:string}[] };
const storage='personal-life-os-books';
const today=()=>new Date().toISOString().slice(0,10);
function readBooks():Book[]{try{return JSON.parse(localStorage.getItem(storage)||'[]')}catch{return[]}}
function analyze(text:string):Pick<Book,'chapters'|'chunks'|'summary'|'concepts'|'recalls'>{
  const clean=text.replace(/\s+/g,' ').trim(); const parts=clean.split(/(?=(?:chapter|第\s*\d+\s*章|#{1,3}\s+)[^.!?。！？]{2,80})/i).filter(x=>x.length>80); const chapters=(parts.length?parts:clean.match(/.{1,1800}/g)||[]).slice(0,30).map((x,i)=>{const heading=x.match(/^(chapter\s+\d+|第\s*\d+\s*章|#{1,3}\s+[^.!?。！？]{2,60})/i);return heading?.[0]?.replace(/^#+\s*/,'')||`Section ${i+1}`});
  const sentences=clean.split(/(?<=[.!?。！？])\s+/).filter(x=>x.length>35); const candidates=Array.from(new Set(sentences.map(x=>x.replace(/^(chapter\s+\d+|第\s*\d+\s*章)[:：]?\s*/i,'').trim()).filter(x=>x.length>30))).slice(0,24); const concepts:Concept[]=candidates.map((sentence,i)=>{const name=sentence.split(/[,:：，。]/)[0].slice(0,42);return{id:`concept-${Date.now()}-${i}`,name,summary:sentence.slice(0,220),tier:i<8?1:i<15?2:i<21?3:4,chapter:chapters[Math.min(i,Math.max(chapters.length-1,0))]||'Main text',pageRange:`Source ${i+1}`,difficulty:i<8?'Core':'Advanced',learned:false}});
  const recalls:Recall[]=concepts.filter(x=>x.tier<=2).slice(0,12).map((concept,i)=>({id:`recall-${Date.now()}-${i}`,question:`Explain the core idea of “${concept.name}” in your own words.`,answer:concept.summary,conceptId:concept.id,difficulty:concept.tier===1?'Medium':'Hard',nextReview:today(),confidence:0})); return {chapters,chunks:Math.max(1,Math.ceil(clean.length/1800)),summary:clean.slice(0,600),concepts,recalls};
}

export default function BookLearning({ areas, skills, data }: { areas:LearningArea[]; skills:Skill[]; data:any }) {
  const { data:storeData, setData } = useAppStore(); const [books,setBooks]=useState<Book[]>(readBooks); const [selected,setSelected]=useState<Book|null>(null); const [mode,setMode]=useState<'library'|'detail'|'learn'|'map'|'recall'>('library'); const [filter,setFilter]=useState('All'); const [message,setMessage]=useState('');
  const persist=(next:Book[])=>{setBooks(next);localStorage.setItem(storage,JSON.stringify(next))};
  const upload=async(file:File)=>{const name=file.name.replace(/\.[^.]+$/,'');setMessage('Parsing full book…');let text=''; if(file.type==='text/plain'||/\.(txt|md)$/i.test(file.name))text=await file.text(); else if(file.type==='application/pdf'||/\.pdf$/i.test(file.name)){setMessage('PDF selected. Browser MVP will process text-based PDFs in the next parser update.');text=await file.text();} else {setMessage('This format is not supported yet. Use TXT, Markdown or PDF.');return} const result=analyze(text);const book:Book={id:`book-${Date.now()}`,title:name,author:'',fileName:file.name,uploadedAt:new Date().toISOString(),status:'Ready',progress:0,...result,sessions:[]};persist([book,...books]);setSelected(book);setMode('detail');setMessage(`Analysis ready · ${result.concepts.length} concepts · ${result.chapters.length} sections`)};
  const update=(next:Book)=>{persist(books.map(x=>x.id===next.id?next:x));setSelected(next)};
  const start=(book:Book,learningMode:string)=>{const session={mode:learningMode,completedAt:new Date().toISOString()};const next={...book,sessions:[...book.sessions,session],progress:Math.min(100,book.progress+(learningMode==='15 Minute'?15:learningMode==='1 Hour'?30:45))};update(next);setMode('learn');setMessage(`${learningMode} learning session added to your history`)};
  const addPlan=(book:Book)=>{const tasks=book.concepts.filter(x=>x.tier===1).slice(0,7).map((concept,i)=>({id:`book-task-${Date.now()}-${i}`,title:`Learn ${concept.name}`,description:`${book.title} · ${concept.chapter} · ${concept.pageRange}`,minutes:15,difficulty:'Medium' as const,category:'Daily progress' as const,status:'todo' as const,bookId:book.id,conceptId:concept.id,areaId:book.areaId,skillId:book.skillId,notes:`Book concept: ${concept.id}`}));setData({...storeData,tasks:[...tasks,...storeData.tasks]});setMessage(`${tasks.length} book learning tasks added to Today`)};
  const visible=books.filter(book=>filter==='All'||book.status===filter); const current=selected||visible[0];
  if(mode!=='library'&&current)return <div className="content book-detail"><button className="back-link" onClick={()=>{setMode('library');setSelected(null)}}><Icon name="ArrowLeft" size={15}/> Book library</button><div className="book-detail-head"><div className="book-cover"><Icon name="BookOpen" size={30}/><small>BOOK</small></div><div><span className="pill purple">AI BOOK LEARNING</span><h2>{current.title}</h2><p className="muted">{current.author||'Author not added'} · {current.fileName}</p><div className="book-progress"><div className="progress"><i style={{width:current.progress+'%'}}/></div><b>{current.progress}% learning progress</b></div></div></div><div className="book-tabs"><button className={mode==='detail'?'active':''} onClick={()=>setMode('detail')}>Overview</button><button className={mode==='learn'?'active':''} onClick={()=>setMode('learn')}>Learning path</button><button className={mode==='map'?'active':''} onClick={()=>setMode('map')}>Knowledge map</button><button className={mode==='recall'?'active':''} onClick={()=>setMode('recall')}>Active recall</button></div>{mode==='detail'&&<><div className="book-actions"><button className="primary" onClick={()=>start(current,'15 Minute')}>Start 15 min</button><button className="secondary" onClick={()=>start(current,'1 Hour')}>Start 1 hour</button><button className="secondary" onClick={()=>start(current,'Deep Learning')}>Deep learning</button><button className="secondary" onClick={()=>addPlan(current)}><Icon name="CalendarPlus" size={15}/> Add to daily plan</button></div><div className="book-stats"><div><b>{current.concepts.filter(x=>x.tier===1).length}</b><small>Tier 1 concepts</small></div><div><b>{current.chunks}</b><small>source chunks</small></div><div><b>{current.recalls.length}</b><small>recall questions</small></div><div><b>{current.sessions.length}</b><small>sessions completed</small></div></div><section className="book-summary"><h3>Whole-book synthesis</h3><p>{current.summary||'No synthesis available yet.'}</p></section><section><SectionTitle title="80/20 concept ranking"/><div className="concept-list">{current.concepts.slice(0,12).map(c=><div className="concept-row" key={c.id}><span className={'tier tier-'+c.tier}>Tier {c.tier}</span><div><b>{c.name}</b><small>{c.chapter} · {c.pageRange}</small><p>{c.summary}</p></div></div>)}</div></section></>}{mode==='learn'&&<LearningPath book={current} onStart={m=>start(current,m)}/>} {mode==='map'&&<BookMap book={current}/>} {mode==='recall'&&<RecallView book={current} onUpdate={update}/>}</div>;
  return <div className="content book-library"><div className="knowledge-header"><div><span className="pill purple">BOOK LEARNING</span><h2>Turn a full book into a learning path.</h2><p className="muted">Upload a book and keep the important concepts, sources and recall in one place.</p></div><label className="primary upload-button"><Icon name="Upload" size={16}/> Upload book<input type="file" accept=".txt,.md,.pdf,text/plain,text/markdown,application/pdf" onChange={e=>{const file=e.target.files?.[0];if(file)upload(file)}}/></label></div><div className="book-toolbar"><div className="knowledge-filters"><button className={filter==='All'?'active':''} onClick={()=>setFilter('All')}>All</button><button className={filter==='Ready'?'active':''} onClick={()=>setFilter('Ready')}>Ready</button><span className="muted">{books.length} books</span></div></div>{message&&<p className="book-message">{message}</p>}{visible.length?<div className="book-grid">{visible.map(book=><article className="book-card" key={book.id} onClick={()=>{setSelected(book);setMode('detail')}}><div className="book-card-top"><div className="book-cover small"><Icon name="BookOpen" size={20}/></div><span className="resource-status">{book.status}</span></div><h3>{book.title}</h3><p>{book.author||book.fileName}</p><div className="progress"><i style={{width:book.progress+'%'}}/></div><small>{book.concepts.filter(x=>x.tier===1).length} essential concepts · {book.recalls.length} recall questions</small></article>)}</div>:<div className="empty-page"><div className="empty-icon"><Icon name="BookOpen" size={30}/></div><h2>Your book library is ready</h2><p>Start with a TXT, Markdown or text-based PDF. The MVP will extract sections, rank concepts and build active recall.</p><label className="primary upload-button">Upload your first book<input type="file" accept=".txt,.md,.pdf,text/plain,text/markdown,application/pdf" onChange={e=>{const file=e.target.files?.[0];if(file)upload(file)}}/></label></div>}</div>;
}

function SectionTitle({title}:{title:string}){return <div className="section-title"><h2>{title}</h2></div>}
function LearningPath({book,onStart}:{book:Book;onStart:(mode:string)=>void}){const concepts=book.concepts.filter(x=>x.tier<=2);return <section className="book-learning-path"><div className="book-mode-grid"><button onClick={()=>onStart('15 Minute')}><b>15 Minute</b><span>Essential mental model · {concepts.slice(0,3).length} concepts</span></button><button onClick={()=>onStart('1 Hour')}><b>1 Hour</b><span>High-density path · {concepts.length} concepts</span></button><button onClick={()=>onStart('Deep Learning')}><b>Deep Learning</b><span>Revisit sources and evidence</span></button></div><SectionTitle title="Recommended order"/><div className="learning-path-list">{concepts.map((concept,index)=><div key={concept.id}><span>{index+1}</span><div><b>{concept.name}</b><small>{concept.chapter} · {concept.pageRange} · 15 min</small></div><Icon name="ArrowDown" size={15}/></div>)}</div></section>}
function BookMap({book}:{book:Book}){return <section className="book-map"><p className="muted">Core concepts extracted from the whole uploaded text. Tier 1 concepts are central; later tiers are supporting or skippable.</p><div className="book-map-grid">{book.concepts.filter(x=>x.tier<=2).map((concept,index)=><div className={'book-map-node tier-'+concept.tier} key={concept.id}><b>{concept.name.slice(0,36)}</b><small>{concept.chapter}</small>{index<book.concepts.filter(x=>x.tier<=2).length-1&&<Icon name="ArrowRight" size={14}/>}</div>)}</div></section>}
function RecallView({ book, onUpdate }: { book: Book; onUpdate: (book: Book) => void }) {
  const [revealed, setRevealed] = useState<Record<string, boolean>>({});
  const answer = (recall: Recall, correct: boolean) => {
    const next: Book = { ...book, recalls: book.recalls.map(item => item.id === recall.id ? { ...item, confidence: correct ? Math.min(100, item.confidence + 20) : Math.max(0, item.confidence - 10), nextReview: correct ? new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10) : today() } : item) };
    onUpdate(next); setRevealed(current => ({ ...current, [recall.id]: true }));
  };
  return <section className="recall-list">{book.recalls.map(recall => <article className="recall-card" key={recall.id}><span className="pill teal">{recall.difficulty} · review {recall.nextReview}</span><h3>{recall.question}</h3>{revealed[recall.id] && <p>{recall.answer}</p>}<div className="recall-actions">{!revealed[recall.id] ? <button className="secondary" onClick={() => setRevealed(current => ({ ...current, [recall.id]: true }))}>Reveal answer</button> : <><button className="secondary" onClick={() => answer(recall, true)}>I knew it</button><button className="secondary" onClick={() => answer(recall, false)}>Need review</button></>}</div></article>)}</section>;
}
