import { useMemo, useState, type ChangeEvent } from 'react';
import Icon from './Icon';
import { localDateKey } from '../domain/date';
import { useAppStore } from '../store/useAppStore';
import type { Task } from '../domain/types';
import { clearCalendarSubscription, importCalendarFile, loadCalendarSubscription, syncCalendarSubscription } from '../services/calendarSubscriptionService';
import WeeklyRoutinePanel from './WeeklyRoutinePanel';
import{CALENDAR_TIME_CATEGORIES,inferCalendarTaskCategory}from'../services/calendarTaskCategory';

const monthLabel=(date:Date)=>new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(date);
const dateLabel=(key:string)=>new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date(`${key}T12:00:00`));
const shiftMonth=(date:Date,amount:number)=>new Date(date.getFullYear(),date.getMonth()+amount,1);
const timeMinutes=(value:string)=>{const[hours,minutes]=value.split(':').map(Number);return hours*60+minutes};
const taskTimeLabel=(task:Task)=>task.scheduledStartTime?`${task.scheduledStartTime}${task.scheduledEndTime?`–${task.scheduledEndTime}`:''}`:'';

export default function CalendarPage(){
  const {data,setData,toggleTask}=useAppStore();
  const today=localDateKey();
  const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
  const [selected,setSelected]=useState(today);
  const [creating,setCreating]=useState(false);
  const [title,setTitle]=useState('');
  const [minutes,setMinutes]=useState(30);
  const [startTime,setStartTime]=useState('');
  const [endTime,setEndTime]=useState('');
  const [projectId,setProjectId]=useState('');
  const [timeCategory,setTimeCategory]=useState('');
  const [subscription,setSubscription]=useState(loadCalendarSubscription);
  const [feedUrl,setFeedUrl]=useState(subscription.url);
  const [syncing,setSyncing]=useState(false);
  const [syncMessage,setSyncMessage]=useState(subscription.events.length?`${subscription.events.length} UCL events cached.`:'Add an iCalendar subscription or import its .ics file.');
  const cells=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),offset=(first.getDay()+6)%7,start=new Date(month.getFullYear(),month.getMonth(),1-offset);return Array.from({length:42},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return{key:localDateKey(date),date,inMonth:date.getMonth()===month.getMonth()}})},[month]);
  const tasksFor=(key:string)=>data.tasks.filter(task=>task.scheduledDate===key);
  const deadlinesFor=(key:string)=>data.projects.filter(project=>/^\d{4}-\d{2}-\d{2}$/.test(project.deadline)&&project.deadline===key);
  const feedFor=(key:string)=>subscription.events.filter(event=>event.date===key);
  const selectedTasks=tasksFor(selected),selectedDeadlines=deadlinesFor(selected),selectedFeed=feedFor(selected),selectedRoutine=(data.weeklyRoutine?.blocks||[]).filter(block=>block.day===new Date(`${selected}T12:00:00`).getDay()).sort((a,b)=>a.start.localeCompare(b.start));
  const selectedProject=data.projects.find(project=>project.id===projectId);
  const suggestedTimeCategory=inferCalendarTaskCategory(title,selectedProject);
  const goToday=()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelected(today)};
  const createTask=()=>{if(!title.trim()||(startTime&&endTime&&timeMinutes(endTime)<=timeMinutes(startTime)))return;const plannedMinutes=startTime&&endTime?timeMinutes(endTime)-timeMinutes(startTime):Math.max(1,minutes);const task:Task={id:`task-${Date.now()}`,title:title.trim(),description:'Created from Calendar',minutes:plannedMinutes,scheduledStartTime:startTime||undefined,scheduledEndTime:endTime||undefined,difficulty:'Medium',category:'Manual',scheduledDate:selected,projectId:projectId||undefined,priority:'Medium',timeCategory:timeCategory||suggestedTimeCategory,status:'todo'};setData(current=>({...current,tasks:[task,...current.tasks]}));setTitle('');setMinutes(30);setStartTime('');setEndTime('');setProjectId('');setTimeCategory('');setCreating(false)};
  const syncFeed=async()=>{if(!feedUrl.trim())return;setSyncing(true);setSyncMessage('Refreshing UCL timetable…');try{const next=await syncCalendarSubscription(feedUrl.trim());setSubscription(next);setSyncMessage(`${next.events.length} UCL events synced.`)}catch{setSyncMessage('UCL blocks direct refresh here. Download the link and use Import .ics.')}finally{setSyncing(false)}};
  const importFeed=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const next=importCalendarFile(await file.text(),feedUrl.trim());setSubscription(next);setSyncMessage(`${next.events.length} UCL events imported from ${file.name}.`)}catch(error){setSyncMessage(error instanceof Error?`Could not import: ${error.message}`:'Could not import this calendar.')}finally{event.target.value=''}};
  const removeFeed=()=>{clearCalendarSubscription();setSubscription({url:'',events:[],updatedAt:''});setFeedUrl('');setSyncMessage('Calendar subscription removed from this browser.')};
  return <div className="content calendar-page">
    <section className="calendar-subscription"><div><span className="pill teal">UCL TIMETABLE</span><h3>Calendar subscription</h3><p>{syncMessage}</p></div><div className="calendar-subscription-controls"><input aria-label="iCalendar subscription URL" type="url" value={feedUrl} onChange={event=>setFeedUrl(event.target.value)} placeholder="Paste an iCalendar subscription URL"/><button className="secondary" disabled={!feedUrl.trim()||syncing} onClick={syncFeed}><Icon name="RefreshCw" size={15}/>{syncing?'Syncing…':subscription.events.length?'Refresh':'Connect'}</button><label className="secondary calendar-file-button"><Icon name="Upload" size={15}/> Import .ics<input aria-label="Import iCalendar file" type="file" accept=".ics,text/calendar" onChange={importFeed}/></label>{subscription.events.length>0&&<button className="secondary danger-action" onClick={removeFeed}>Remove</button>}</div><small>The private address and imported timetable stay in this browser and are not committed to GitHub.</small></section>
    <WeeklyRoutinePanel/>
    <div className="calendar-toolbar"><div><span className="pill purple">PLAN AHEAD</span><h2>{monthLabel(month)}</h2><p className="muted">Tasks, UCL classes and project deadlines in one place.</p></div><div className="calendar-navigation"><button className="secondary" onClick={()=>setMonth(value=>shiftMonth(value,-1))} aria-label="Previous month"><Icon name="ChevronLeft" size={16}/></button><button className="secondary" onClick={goToday}>Today</button><button className="secondary" onClick={()=>setMonth(value=>shiftMonth(value,1))} aria-label="Next month"><Icon name="ChevronRight" size={16}/></button></div></div>
    <div className="calendar-layout"><section className="calendar-card"><div className="calendar-weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{cells.map(cell=>{const tasks=tasksFor(cell.key),deadlines=deadlinesFor(cell.key),feed=feedFor(cell.key),total=tasks.length+deadlines.length+feed.length,done=tasks.filter(task=>task.status==='done').length;return <button key={cell.key} className={`calendar-day${cell.inMonth?'':' outside'}${cell.key===today?' today':''}${cell.key===selected?' selected':''}`} onClick={()=>setSelected(cell.key)}><span className="calendar-day-number">{cell.date.getDate()}</span>{feed.slice(0,2).map(event=><span key={event.id} className="calendar-event ucl"><i/>{event.startTime} {event.title}</span>)}{tasks.slice(0,Math.max(0,2-feed.length)).map(task=><span key={task.id} className={`calendar-event${task.status==='done'?' done':''}`}><i/>{task.scheduledStartTime?`${task.scheduledStartTime} `:''}{task.title}</span>)}{deadlines.length>0&&feed.length+tasks.length<3&&<span className="calendar-event deadline"><i style={{background:deadlines[0].color}}/>{deadlines[0].name}</span>}{total>3&&<small>+{total-3} more</small>}{tasks.length>0&&<em>{done}/{tasks.length}</em>}</button>})}</div></section>
      <aside className="calendar-agenda"><div className="calendar-agenda-head"><div><span className="pill teal">DAY PLAN</span><h3>{dateLabel(selected)}</h3></div><button className="primary" onClick={()=>setCreating(true)}><Icon name="Plus" size={15}/> Add task</button></div>{selectedTasks.length===0&&selectedDeadlines.length===0&&selectedFeed.length===0&&selectedRoutine.length===0&&<div className="calendar-empty"><Icon name="CalendarDays" size={28}/><b>Nothing planned yet</b><span>Add a task or choose another day.</span></div>}{selectedRoutine.map(block=><div className={`calendar-agenda-item routine-agenda kind-${block.kind}`} key={block.id}><span className="calendar-source-dot">{block.movable?'SOFT':'FIXED'}</span><div><b>{block.title}</b><small>{block.start}–{block.end} · Weekly template{block.optional?' · optional':''}</small></div></div>)}{selectedFeed.map(event=><div className="calendar-agenda-item ucl" key={event.id}><span className="calendar-source-dot">UCL</span><div><b>{event.title}</b><small>{event.startTime}–{event.endTime}{event.location?` · ${event.location}`:''}</small></div></div>)}{selectedDeadlines.map(project=><div className="calendar-agenda-item deadline" key={project.id}><span className="area-dot" style={{background:project.color}}/><div><b>{project.name}</b><small>Project deadline · {project.status}</small></div></div>)}{selectedTasks.map(task=><div className={`calendar-agenda-item${task.status==='done'?' done':''}`} key={task.id}><button className={`check${task.status==='done'?' checked':''}`} onClick={()=>toggleTask(task.id)}>{task.status==='done'&&<Icon name="Check" size={12}/>}</button><div><b>{task.title}</b><small>{taskTimeLabel(task)?`${taskTimeLabel(task)} · `:''}{task.minutes} min{task.projectId?` · ${data.projects.find(project=>project.id===task.projectId)?.name||'Project'}`:''}</small></div><span className="task-priority">{task.priority||'Medium'}</span></div>)}</aside></div>
    {creating&&<div className="modal-backdrop" onMouseDown={()=>setCreating(false)}><form className="create-modal calendar-create" onSubmit={event=>{event.preventDefault();createTask()}} onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><span className="pill purple">CALENDAR TASK</span><h2>{dateLabel(selected)}</h2></div><button type="button" className="modal-close" onClick={()=>setCreating(false)}>×</button></div><label>Task<input autoFocus value={title} onChange={event=>setTitle(event.target.value)} placeholder="What needs to happen?"/></label><div className="form-two"><label>Start time<input type="time" value={startTime} onChange={event=>setStartTime(event.target.value)}/></label><label>End time<input type="time" value={endTime} min={startTime||undefined} onChange={event=>setEndTime(event.target.value)}/></label></div>{startTime&&endTime&&timeMinutes(endTime)<=timeMinutes(startTime)&&<p className="time-message error">End time must be later than start time.</p>}<div className="form-two"><label>Planned minutes<input type="number" min="1" value={startTime&&endTime&&timeMinutes(endTime)>timeMinutes(startTime)?timeMinutes(endTime)-timeMinutes(startTime):minutes} disabled={Boolean(startTime&&endTime&&timeMinutes(endTime)>timeMinutes(startTime))} onChange={event=>setMinutes(Math.max(1,Number(event.target.value)))}/></label><label>Project<select value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">No project</option>{data.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label></div><div className="duration-presets">{[15,30,60,90].map(value=><button type="button" className={minutes===value?'active':''} key={value} onClick={()=>setMinutes(value)}>{value} min</button>)}</div><label>Time category<select value={timeCategory} onChange={event=>setTimeCategory(event.target.value)}><option value="">Auto · {suggestedTimeCategory}</option>{CALENDAR_TIME_CATEGORIES.map(value=><option key={value}>{value}</option>)}</select><small className="muted">Used by Time Tracking; choose one when the suggestion is not right.</small></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="primary" disabled={!title.trim()||Boolean(startTime&&endTime&&timeMinutes(endTime)<=timeMinutes(startTime))}>Add to calendar</button></div></form></div>}
  </div>;
}
