import { useState } from 'react';
import Icon from './Icon';
import { getAppSnapshot, restoreAppSnapshot } from '../store/useAppStore';
import type { RepositorySnapshot } from '../domain/types';

export default function CloudSync({data: _data,setData: _setData}:{data:any;setData:(data:any)=>void}){
  const[url,setUrl]=useState(()=>localStorage.getItem('personal-life-os-supabase-url')||'');const[key,setKey]=useState(()=>localStorage.getItem('personal-life-os-supabase-anon-key')||'');const[message,setMessage]=useState('');const[loading,setLoading]=useState(false);
  const saveConfig=()=>{localStorage.setItem('personal-life-os-supabase-url',url.trim().replace(/\/$/,''));localStorage.setItem('personal-life-os-supabase-anon-key',key.trim());setMessage('Supabase settings saved')};
  const sync=async(mode:'push'|'pull')=>{if(!url||!key){setMessage('Enter Supabase URL and anon key first.');return}setLoading(true);setMessage(mode==='push'?'Uploading complete repository…':'Downloading complete repository…');try{const endpoint=url.replace(/\/$/,'')+'/rest/v1/life_os_snapshots';const headers={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=representation'};if(mode==='push'){const snapshot=getAppSnapshot();const response=await fetch(endpoint+'?user_key=eq.local',{method:'POST',headers,body:JSON.stringify({user_key:'local',payload:snapshot,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error(`Supabase ${response.status}`);setMessage('Complete repository backup finished')}else{const response=await fetch(endpoint+'?user_key=eq.local&order=updated_at.desc&limit=1',{headers});if(!response.ok)throw new Error(`Supabase ${response.status}`);const rows=await response.json();const snapshot=rows[0]?.payload as RepositorySnapshot|undefined;if(snapshot?.data&&Array.isArray(snapshot.activities)){restoreAppSnapshot(snapshot);setMessage('Complete repository restored')}else setMessage('No valid repository snapshot found')}}catch(error){setMessage(error instanceof Error?error.message:'Sync failed. Check the table and credentials.')}finally{setLoading(false)}};
  return <section className="settings-card cloud-sync"><div className="settings-card-head"><div><h3>Supabase cloud sync</h3><p>Sync the complete workspace, including history, books, people, quests and meals.</p></div><Icon name="Cloud" size={20}/></div><div className="form-two"><label>Project URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-project.supabase.co"/></label><label>Anon key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="eyJ…" autoComplete="off"/></label></div><p className="settings-warning"><Icon name="Info" size={15}/> The <b>payload</b> jsonb column stores the complete RepositorySnapshot.</p><div className="settings-actions"><button className="secondary" onClick={saveConfig}>Save settings</button><button className="secondary" onClick={()=>sync('pull')} disabled={loading}>Restore cloud</button><button className="primary" onClick={()=>sync('push')} disabled={loading}>Backup to cloud</button></div>{message&&<p className="muted cloud-message">{message}</p>}</section>;
}
