import { useEffect, useState } from 'react';
import Icon from './Icon';
import { getAppSnapshot, restoreAppSnapshot } from '../store/useAppStore';
import { isSupabaseQuotaError, pullCloudSnapshot, pushCloudSnapshot, recordLastSync, SUPABASE_ANON_KEY, SUPABASE_AUTO_SYNC_KEY, SUPABASE_CONFIG_EVENT, SUPABASE_STATUS_EVENT, SUPABASE_URL_KEY } from '../services/supabaseSync';

type SyncStatus={state:string;message:string;at?:string};
export default function CloudSync({data: _data,setData: _setData}:{data:any;setData:(data:any)=>void}){
  const[url,setUrl]=useState(()=>localStorage.getItem(SUPABASE_URL_KEY)||'');
  const[key,setKey]=useState(()=>localStorage.getItem(SUPABASE_ANON_KEY)||'');
  const[auto,setAuto]=useState(()=>localStorage.getItem(SUPABASE_AUTO_SYNC_KEY)==='true');
  const[message,setMessage]=useState('');
  const[loading,setLoading]=useState(false);
  const[remote,setRemote]=useState<{updated_at:string;payload:any}|null>(null);
  const[status,setStatus]=useState<SyncStatus>({state:'idle',message:'Waiting for sync status'});
  useEffect(()=>{const update=(event:Event)=>setStatus((event as CustomEvent<SyncStatus>).detail);window.addEventListener(SUPABASE_STATUS_EVENT,update);return()=>window.removeEventListener(SUPABASE_STATUS_EVENT,update)},[]);
  const saveConfig=()=>{localStorage.setItem(SUPABASE_URL_KEY,url.trim().replace(/\/$/,''));localStorage.setItem(SUPABASE_ANON_KEY,key.trim());localStorage.setItem(SUPABASE_AUTO_SYNC_KEY,String(auto));window.dispatchEvent(new Event(SUPABASE_CONFIG_EVENT));setMessage(auto?'Supabase settings saved · automatic sync enabled':'Supabase settings saved · automatic sync paused')};
  const sync=async(mode:'push'|'pull')=>{if(!url||!key){setMessage('Enter Supabase URL and anon key first.');return}saveConfig();setLoading(true);setMessage(mode==='push'?'Uploading complete repository…':'Downloading complete repository…');try{if(mode==='push'){const rows=await pushCloudSnapshot(getAppSnapshot());recordLastSync(rows[0]?.updated_at||new Date().toISOString());setMessage('Complete repository backup finished')}else{const row=await pullCloudSnapshot();const snapshot=row?.payload;if(snapshot?.data&&Array.isArray(snapshot.activities)){restoreAppSnapshot(snapshot);recordLastSync(row.updated_at);setMessage('Complete repository restored')}else setMessage('No valid repository snapshot found')}}catch(error){if(isSupabaseQuotaError(error)){localStorage.setItem(SUPABASE_AUTO_SYNC_KEY,'false');setAuto(false);setMessage('Supabase quota exceeded (402). Automatic sync has been paused. Check Billing / Usage in Supabase.')}else setMessage(error instanceof Error?error.message:'Sync failed. Check the table and credentials.')}finally{setLoading(false)}};
  const checkCloudVersion=async()=>{if(!url||!key){setMessage('Enter Supabase URL and anon key first.');return}saveConfig();setLoading(true);setMessage('Checking cloud version…');try{const row=await pullCloudSnapshot();if(!row){setRemote(null);setMessage('No cloud snapshot found yet.');return}setRemote(row);const local=getAppSnapshot().updatedAt;const localTime=Date.parse(local)||0;const remoteTime=Date.parse(row.updated_at)||0;setMessage(remoteTime>localTime?'A newer cloud version is available. Review it before restoring.':remoteTime<localTime?'This device has newer data. Backup it to the cloud when ready.':'Local and cloud versions match.')}catch(error){if(isSupabaseQuotaError(error)){localStorage.setItem(SUPABASE_AUTO_SYNC_KEY,'false');setAuto(false);setMessage('Supabase quota exceeded (402). Automatic sync has been paused. Check Billing / Usage in Supabase.')}else setMessage(error instanceof Error?error.message:'Could not check cloud version.')}finally{setLoading(false)}};
  const restoreCheckedVersion=()=>{if(!remote?.payload)return;restoreAppSnapshot(remote.payload);recordLastSync(remote.updated_at);setRemote(null);setMessage('Cloud version restored after confirmation.')};
  const at=status.at?new Date(status.at).toLocaleString():'';
  return <section className="settings-card cloud-sync"><div className="settings-card-head"><div><h3>Supabase cloud sync</h3><p>Sync the complete workspace, including history, books, people, quests and meals.</p></div><Icon name="Cloud" size={20}/></div><div className="form-two"><label>Project URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-project.supabase.co"/></label><label>Anon key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="eyJ…" autoComplete="off"/></label></div><label className="settings-label"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Automatic sync</label><p className="settings-warning"><Icon name="Info" size={15}/> Automatic sync is off by default to protect Supabase bandwidth. When enabled, checks run at most every 15 minutes; manual Backup and Restore remain available.</p><div className={`cloud-sync-status ${status.state}`}><b>{status.state==='syncing'?'Syncing':status.state==='synced'?'Up to date':status.state==='offline'?'Offline':status.state==='error'?'Needs attention':'Ready'}</b><span>{status.message}{at?` · ${at}`:''}</span></div><div className="settings-actions"><button className="secondary" onClick={saveConfig}>Save settings</button><button className="secondary" onClick={checkCloudVersion} disabled={loading}>Check cloud version</button><button className="secondary" onClick={()=>sync('pull')} disabled={loading}>Restore cloud</button><button className="primary" onClick={()=>sync('push')} disabled={loading}>Backup to cloud</button></div>{remote&&<div className="cloud-version-review"><strong>Cloud version found</strong><span>Local: {new Date(getAppSnapshot().updatedAt).toLocaleString()} · Cloud: {new Date(remote.updated_at).toLocaleString()}</span><div className="settings-actions"><button className="secondary" onClick={()=>setRemote(null)}>Keep local version</button><button className="primary" onClick={restoreCheckedVersion}>Use cloud version</button></div></div>}{message&&<p className="muted cloud-message">{message}</p>}</section>;
}
