import { useState } from 'react';
import Icon from './Icon';
import { getAppSnapshot, restoreAppSnapshot } from '../store/useAppStore';
import { downloadDriveSnapshot, GOOGLE_DRIVE_CLIENT_ID_KEY, uploadDriveSnapshot } from '../services/googleDriveSync';

export default function GoogleDriveSync(){
  const[clientId,setClientId]=useState(()=>localStorage.getItem(GOOGLE_DRIVE_CLIENT_ID_KEY)||'');
  const[message,setMessage]=useState('');const[loading,setLoading]=useState(false);const[remote,setRemote]=useState<{updatedAt:string;payload:any}|null>(null);
  const save=()=>{localStorage.setItem(GOOGLE_DRIVE_CLIENT_ID_KEY,clientId.trim());setMessage('Google Drive settings saved.')};
  const check=async()=>{if(!clientId.trim()){setMessage('Add a Google OAuth Client ID first.');return}setLoading(true);setMessage('Checking Google Drive version…');try{const result=await downloadDriveSnapshot(clientId.trim());if(!result){setRemote(null);setMessage('No Personal Life OS backup found in Google Drive.');return}setRemote(result);const local=Date.parse(getAppSnapshot().updatedAt)||0;const cloud=Date.parse(result.updatedAt)||0;setMessage(cloud>local?'A newer Google Drive version is available. Review it before restoring.':cloud<local?'This device has newer data. Back it up when ready.':'Local and Google Drive versions match.')}catch(error){setMessage(error instanceof Error?error.message:'Could not check Google Drive.')}finally{setLoading(false)}};
  const backup=async()=>{if(!clientId.trim()){setMessage('Add a Google OAuth Client ID first.');return}setLoading(true);setMessage('Uploading complete repository to Google Drive…');try{const result=await uploadDriveSnapshot(getAppSnapshot(),clientId.trim());setRemote(null);setMessage(`Google Drive backup finished · ${new Date(result.updatedAt).toLocaleString()}`)}catch(error){setMessage(error instanceof Error?error.message:'Google Drive backup failed.')}finally{setLoading(false)}};
  const restore=()=>{if(!remote)return;restoreAppSnapshot(remote.payload);setRemote(null);setMessage('Google Drive version restored after confirmation.')};
  return <section className="settings-card cloud-sync"><div className="settings-card-head"><div><h3>Google Drive backup</h3><p>Keep a private repository snapshot in your own Google Drive.</p></div><Icon name="HardDrive" size={20}/></div><label className="settings-label">Google OAuth Client ID<input value={clientId} onChange={e=>setClientId(e.target.value)} placeholder="1234567890-…apps.googleusercontent.com" autoComplete="off"/></label><p className="settings-warning"><Icon name="Info" size={15}/> Create a Web application OAuth Client ID in Google Cloud Console. The app requests access only to files it creates.</p><div className="settings-actions"><button className="secondary" onClick={save}>Save settings</button><button className="secondary" onClick={check} disabled={loading}>Check cloud version</button><button className="primary" onClick={backup} disabled={loading}>Backup to Drive</button></div>{remote&&<div className="cloud-version-review"><strong>Google Drive version found</strong><span>Local: {new Date(getAppSnapshot().updatedAt).toLocaleString()} · Cloud: {new Date(remote.updatedAt).toLocaleString()}</span><div className="settings-actions"><button className="secondary" onClick={()=>setRemote(null)}>Keep local version</button><button className="primary" onClick={restore}>Use cloud version</button></div></div>}{message&&<p className="muted cloud-message">{message}</p>}</section>;
}
