import{useMemo,useState}from'react';
import Icon from'./Icon';

type GroceryPrice={id:string;ingredient:string;supermarket:string;packQuantity:number;unit:string;price:number;note:string;updatedAt:string};
const KEY='personal-life-os-grocery-prices-v1';
const units=['g','kg','ml','L','piece','pack'];
const load=():GroceryPrice[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};

export default function GroceryPriceBook({currencySymbol}:{currencySymbol:string}){
 const[items,setItems]=useState<GroceryPrice[]>(load);const[editingId,setEditingId]=useState('');const[ingredient,setIngredient]=useState('');const[supermarket,setSupermarket]=useState('');const[packQuantity,setPackQuantity]=useState(1);const[unit,setUnit]=useState('piece');const[price,setPrice]=useState(0);const[note,setNote]=useState('');const[query,setQuery]=useState('');
 const persist=(next:GroceryPrice[])=>{setItems(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const reset=()=>{setEditingId('');setIngredient('');setSupermarket('');setPackQuantity(1);setUnit('piece');setPrice(0);setNote('')};
 const save=()=>{if(!ingredient.trim()||!supermarket.trim()||packQuantity<=0||price<0)return;const entry:GroceryPrice={id:editingId||`grocery-${Date.now()}`,ingredient:ingredient.trim(),supermarket:supermarket.trim(),packQuantity,unit,price,note:note.trim(),updatedAt:new Date().toISOString()};persist(editingId?items.map(item=>item.id===editingId?entry:item):[entry,...items]);reset()};
 const edit=(item:GroceryPrice)=>{setEditingId(item.id);setIngredient(item.ingredient);setSupermarket(item.supermarket);setPackQuantity(item.packQuantity);setUnit(item.unit);setPrice(item.price);setNote(item.note)};
 const visible=useMemo(()=>items.filter(item=>`${item.ingredient} ${item.supermarket} ${item.note}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.ingredient.localeCompare(b.ingredient)||a.price/a.packQuantity-b.price/b.packQuantity),[items,query]);
 return <section className="grocery-price-book"><div className="grocery-price-head"><div><span className="pill teal">PRICE BOOK</span><h3>Supermarket unit prices</h3><p>Save package prices once, then compare the real cost per unit.</p></div><div className="grocery-price-count"><b>{items.length}</b><span>saved prices</span></div></div><div className="grocery-price-form"><label>Ingredient<input value={ingredient} onChange={event=>setIngredient(event.target.value)} placeholder="e.g. Salmon"/></label><label>Supermarket<input value={supermarket} onChange={event=>setSupermarket(event.target.value)} placeholder="e.g. Tesco"/></label><label>Pack quantity<input type="number" min="0.01" step="0.01" value={packQuantity} onChange={event=>setPackQuantity(Number(event.target.value))}/></label><label>Unit<select value={unit} onChange={event=>setUnit(event.target.value)}>{units.map(value=><option key={value}>{value}</option>)}</select></label><label>Pack price<input type="number" min="0" step="0.01" value={price} onChange={event=>setPrice(Number(event.target.value))}/></label><label className="grocery-note">Note<input value={note} onChange={event=>setNote(event.target.value)} placeholder="Brand, offer or package details"/></label><div className="grocery-form-actions">{editingId&&<button className="secondary" onClick={reset}>Cancel</button>}<button className="primary" onClick={save} disabled={!ingredient.trim()||!supermarket.trim()||packQuantity<=0}><Icon name={editingId?'Save':'Plus'} size={14}/>{editingId?'Update price':'Add price'}</button></div></div>{items.length>0&&<><div className="grocery-price-search"><Icon name="Search" size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search ingredient or supermarket"/></div><div className="grocery-price-list">{visible.map(item=><article key={item.id}><div><b>{item.ingredient}</b><span>{item.supermarket}{item.note?` · ${item.note}`:''}</span></div><div className="grocery-pack-price"><b>{currencySymbol}{item.price.toFixed(2)}</b><small>{item.packQuantity} {item.unit} pack</small></div><div className="grocery-unit-price"><b>{currencySymbol}{(item.price/Math.max(.01,item.packQuantity)).toFixed(item.price/item.packQuantity<.1?3:2)}</b><small>per {item.unit}</small></div><button title="Edit price" onClick={()=>edit(item)}><Icon name="Pencil" size={13}/></button><button className="danger-action" title="Delete price" onClick={()=>persist(items.filter(value=>value.id!==item.id))}><Icon name="Trash2" size={13}/></button></article>)}</div></>}</section>;
}
