import { useEffect, useState } from 'react';
import Icon from './Icon';
import type { HydrationState } from '../domain/types';

const date=()=>new Date().toISOString().slice(0,10); const fresh=():HydrationState=>({date:date(),goalMl:2500,consumedMl:0,entries:[],reminderMinutes:60,notificationsEnabled:false});
export default function HydrationWidget({ data, setData }: { data:any; setData:(updater:any)=>void }) {
  const [permission,setPermission]=useState(typeof Notification==='undefined'?'unsupported':Notification.permission); const hydration:HydrationState=data.hydration?.date===date()?data.hydration:fresh(); const [custom,setCustom]=useState('');
  useEffect(()=>{if(!data.hydration||data.hydration.date!==date())setData((current:any)=>({...current,hydration:{...fresh(),goalMl:current.hydration?.goalMl||2500,reminderMinutes:current.hydration?.reminderMinutes||60}}));},[data.hydration,setData]);
  useEffect(()=>{const timer=window.setInterval(()=>{const current=data.hydration;if(!current||current.date!==date()||!current.notificationsEnabled||current.consumedMl>=current.goalMl||permission!=='granted')return;const last=current.lastNotifiedAt?Date.parse(current.lastNotifiedAt):0;if(Date.now()-last<current.reminderMinutes*60000)return;const notify=()=>{if('serviceWorker' in navigator)navigator.serviceWorker.ready.then(reg=>reg.showNotification('Time for a water break',{body:`You have had ${current.consumedMl} ml today. Goal: ${current.goalMl} ml.`,icon:'/personal-life-os/icons/app-icon.svg'})).catch(()=>new Notification('Time for a water break',{body:`${current.consumedMl} / ${current.goalMl} ml today.`}));else new Notification('Time for a water break',{body:`${current.consumedMl} / ${current.goalMl} ml today.`})};notify();setData((currentData:any)=>({...currentData,hydration:{...currentData.hydration,lastNotifiedAt:new Date().toISOString()}}))},60000);return()=>window.clearInterval(timer)},[data.hydration,permission,setData]);
  const add=(ml:number)=>setData((current:any)=>{const state=current.hydration?.date===date()?current.hydration:fresh();return{...current,hydration:{...state,consumedMl:Math.min(state.goalMl,state.consumedMl+ml),entries:[...state.entries,{id:'water-'+Date.now(),ml,at:new Date().toISOString()}]}}});
  const enable=async()=>{if(typeof Notification==='undefined'){setPermission('unsupported');return}const next=await Notification.requestPermission();setPermission(next);if(next==='granted')setData((current:any)=>({...current,hydration:{...(current.hydration||fresh()),notificationsEnabled:true}}));}; const toggle=()=>setData((current:any)=>({...current,hydration:{...(current.hydration||fresh()),notificationsEnabled:!hydration.notificationsEnabled}})); const percent=Math.min(100,Math.round(hydration.consumedMl/hydration.goalMl*100));
  return <section className="hydration-widget"><div className="hydration-head"><div><span className="pill teal">HYDRATION</span><h3>Drink water steadily.</h3><p className="muted">Daily goal · {hydration.goalMl} ml</p></div><div className="hydration-total"><b>{hydration.consumedMl}</b><span>/ {hydration.goalMl} ml</span></div></div><div className="hydration-progress"><i style={{width:`${percent}%`}}/></div><div className="hydration-controls"><button className="secondary" onClick={()=>add(250)}>+250 ml</button><button className="secondary" onClick={()=>add(500)}>+500 ml</button><div className="hydration-custom"><input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="ml" inputMode="numeric"/><button className="secondary" onClick={()=>{const ml=Number(custom);if(ml>0){add(ml);setCustom('')}}}>Add</button></div><select value={hydration.reminderMinutes} onChange={e=>setData((current:any)=>({...current,hydration:{...(current.hydration||fresh()),reminderMinutes:Number(e.target.value)}}))}><option value="30">Every 30m</option><option value="60">Every hour</option><option value="90">Every 90m</option><option value="120">Every 2h</option></select>{permission==='granted'?<button className={'hydration-notify '+(hydration.notificationsEnabled?'on':'')} onClick={toggle}><Icon name="Bell" size={14}/>{hydration.notificationsEnabled?'Notifications on':'Notifications off'}</button>:<button className="hydration-notify" onClick={enable}><Icon name="Bell" size={14}/>{permission==='unsupported'?'Notifications unavailable':'Enable notifications'}</button>}</div><div className="hydration-footer"><span>{Math.max(0,hydration.goalMl-hydration.consumedMl)} ml remaining</span><span>{hydration.entries.length} entries today</span></div></section>;
}
