import { useMemo, useState } from 'react';
import type { KnowledgeItem } from '../domain/types';
import Icon from './Icon';
import { metadataRepository } from '../repositories/legacyRepositories';
import { useAppStore } from '../store/useAppStore';

type View = 'inbox' | 'saved' | 'read' | 'archive';
type Takeaways = Record<string, string>;

function CaptureKnowledge({ onCancel, onSave }: { onCancel: () => void; onSave: (item: KnowledgeItem) => void }) {
  const [title, setTitle] = useState(''); const [url, setUrl] = useState(''); const [field, setField] = useState('Personal research'); const [summary, setSummary] = useState('');
  return <div className="modal-backdrop" onMouseDown={onCancel}><form className="create-modal knowledge-capture-modal" onMouseDown={event => event.stopPropagation()} onSubmit={event => { event.preventDefault(); if (!title.trim()) return; onSave({ id: `knowledge-${Date.now()}`, title: title.trim(), source: 'Personal capture', publishedAt: new Date().toISOString().slice(0, 10), field: field.trim() || 'Personal research', summary: summary.trim() || 'Captured for later review.', whyItMatters: 'You chose to keep this idea for your learning system.', url: url.trim() }); }}><div className="modal-head"><div><span className="pill teal">CAPTURE KNOWLEDGE</span><h2>Save an idea with context</h2></div><button type="button" className="modal-close" onClick={onCancel}>×</button></div><label>Title<input autoFocus value={title} onChange={event => setTitle(event.target.value)} placeholder="Paper, idea or question" /></label><div className="form-two"><label>Topic<input value={field} onChange={event => setField(event.target.value)} /></label><label>Source URL <small>optional</small><input value={url} onChange={event => setUrl(event.target.value)} placeholder="https://…" /></label></div><label>Why keep this?<textarea rows={4} value={summary} onChange={event => setSummary(event.target.value)} placeholder="A short summary in your own words" /></label><div className="modal-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={!title.trim()}><Icon name="Plus" size={15} /> Save to inbox</button></div></form></div>;
}

export default function KnowledgePage({ items }: { items: KnowledgeItem[] }) {
  const { data, setData } = useAppStore();
  const [query, setQuery] = useState(''); const [field, setField] = useState('All topics'); const [sourceFilter, setSourceFilter] = useState('All sources'); const [view, setView] = useState<View>('inbox'); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [expanded, setExpanded] = useState<string | null>(null);
  const [savedIds, setSavedIds] = useState<string[]>(() => metadataRepository.get('personal-life-os-saved-knowledge', [])); const [readIds, setReadIds] = useState<string[]>(() => metadataRepository.get('personal-life-os-read-knowledge', [])); const [takeaways, setTakeaways] = useState<Takeaways>(() => metadataRepository.get('personal-life-os-knowledge-takeaways', {})); const [current, setCurrent] = useState<KnowledgeItem[]>(() => metadataRepository.get('personal-life-os-knowledge', items)); const [archived, setArchived] = useState<KnowledgeItem[]>(() => metadataRepository.get('personal-life-os-knowledge-history', []));
  const source = view === 'archive' ? archived : current.filter(item => view === 'saved' ? savedIds.includes(item.id) : view === 'read' ? readIds.includes(item.id) : !readIds.includes(item.id)); const fields = ['All topics', ...Array.from(new Set(source.map(item => item.field).filter(Boolean)))]; const sources = ['All sources', ...Array.from(new Set(source.map(item => item.source).filter(Boolean)))];
  const visible = useMemo(() => source.filter(item => (field === 'All topics' || item.field === field) && (sourceFilter === 'All sources' || item.source === sourceFilter) && `${item.title} ${item.summary} ${item.field} ${item.source}`.toLowerCase().includes(query.toLowerCase())), [source, field, sourceFilter, query]);
  const persistIds = (type: 'saved' | 'read', next: string[]) => { metadataRepository.set(type === 'saved' ? 'personal-life-os-saved-knowledge' : 'personal-life-os-read-knowledge', next); type === 'saved' ? setSavedIds(next) : setReadIds(next); }; const toggle = (id: string, type: 'saved' | 'read') => { const list = type === 'saved' ? savedIds : readIds; persistIds(type, list.includes(id) ? list.filter(value => value !== id) : [...list, id]); };
  const saveTakeaway = (id: string, value: string) => { const next = { ...takeaways, [id]: value }; setTakeaways(next); metadataRepository.set('personal-life-os-knowledge-takeaways', next); setMessage('Takeaway saved. This item is now part of your own knowledge, not just a link.'); };
  const addToToday = (item: KnowledgeItem) => { const exists = data.tasks.some(task => task.notes?.includes(`Knowledge: ${item.id}`) && task.status !== 'done'); if (exists) return setMessage('This reading task is already in Today.'); setData(currentData => ({ ...currentData, tasks: [{ id: `knowledge-task-${item.id}-${Date.now()}`, title: `Read and reflect: ${item.title}`, description: takeaways[item.id] || 'Read the source and write one takeaway.', minutes: 15, difficulty: 'Easy', category: 'Daily progress', status: 'todo', notes: `Knowledge: ${item.id} · ${item.url}` }, ...currentData.tasks] })); setMessage('Added a 15-minute read-and-reflect task to Today.'); };
  const archive = (item: KnowledgeItem) => { const nextCurrent = current.filter(entry => entry.id !== item.id); const nextArchive = [item, ...archived.filter(entry => entry.id !== item.id)].slice(0, 200); setCurrent(nextCurrent); setArchived(nextArchive); metadataRepository.set('personal-life-os-knowledge', nextCurrent); metadataRepository.set('personal-life-os-knowledge-history', nextArchive); setMessage('Moved to Archive.'); }; const restore = (item: KnowledgeItem) => { const nextArchive = archived.filter(entry => entry.id !== item.id); const nextCurrent = [item, ...current.filter(entry => entry.id !== item.id)]; setArchived(nextArchive); setCurrent(nextCurrent); metadataRepository.set('personal-life-os-knowledge-history', nextArchive); metadataRepository.set('personal-life-os-knowledge', nextCurrent); setMessage('Restored to the knowledge inbox.'); };
  const refresh = async () => { setLoading(true); setMessage('Looking for recent research signals…'); try { const response = await fetch('https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=neuroscience%20OR%20machine%20learning&format=json&pageSize=8&sort_date=y'); const body = response.ok ? await response.json() : { resultList: { result: [] } }; const fresh: KnowledgeItem[] = (body.resultList?.result || []).map((item: any) => ({ id: `pmc-${item.id}`, title: item.title || 'Untitled publication', source: 'Europe PMC', publishedAt: item.firstPublicationDate || item.pubYear || 'Recent', field: /brain|neuro/i.test(item.title || '') ? 'Neuroscience' : 'AI / Machine Learning', summary: item.abstractText || 'Publication record available through Europe PMC.', whyItMatters: 'A recent research signal connected to your learning directions.', url: `https://europepmc.org/article/${item.source || 'MED'}/${item.id}` })); const known = new Set([...current, ...archived].map(item => `${item.title}|${item.url}`.toLowerCase())); const additions = fresh.filter(item => !known.has(`${item.title}|${item.url}`.toLowerCase())); const next = [...additions, ...current]; setCurrent(next); metadataRepository.set('personal-life-os-knowledge', next); setView('inbox'); setMessage(additions.length ? `Added ${additions.length} new research signals.` : 'No new signals found this time.'); } catch { setMessage('Refresh could not reach the research source. Your library is unchanged.'); } finally { setLoading(false); } };
  const addCaptured = (item: KnowledgeItem) => { const next = [item, ...current]; setCurrent(next); metadataRepository.set('personal-life-os-knowledge', next); setCreating(false); setView('inbox'); setMessage('Saved to your knowledge inbox.'); }; const tabCounts: Record<View, number> = { inbox: current.filter(item => !readIds.includes(item.id)).length, saved: current.filter(item => savedIds.includes(item.id)).length, read: current.filter(item => readIds.includes(item.id)).length, archive: archived.length };
  return <div className="content knowledge-workspace"><section className="knowledge-workspace-hero"><div><span className="pill teal">KNOWLEDGE WORKSPACE</span><h2>Turn information into something you can use.</h2><p>Inbox is for new signals. Save the useful ones, write one takeaway, then turn the best idea into a small action.</p></div><div className="knowledge-hero-actions"><button className="secondary" onClick={refresh} disabled={loading}><Icon name="RefreshCw" size={15} />{loading ? 'Refreshing…' : 'Find research'}</button><button className="primary" onClick={() => setCreating(true)}><Icon name="Plus" size={15} /> Capture idea</button></div></section>
    <div className="knowledge-purpose-row"><div><Icon name="Inbox" size={19} /><span><b>1. Collect</b><small>New papers and ideas land in Inbox</small></span></div><div><Icon name="Bookmark" size={19} /><span><b>2. Distill</b><small>Save it and write one takeaway</small></span></div><div><Icon name="ListChecks" size={19} /><span><b>3. Apply</b><small>Turn it into a focused Today task</small></span></div></div>
    <nav className="knowledge-tabs">{(['inbox', 'saved', 'read', 'archive'] as View[]).map(tab => <button key={tab} className={view === tab ? 'active' : ''} onClick={() => { setView(tab); setField('All topics'); setSourceFilter('All sources'); }}><Icon name={tab === 'inbox' ? 'Inbox' : tab === 'saved' ? 'Bookmark' : tab === 'read' ? 'CheckCircle2' : 'Archive'} size={15} />{tab[0].toUpperCase() + tab.slice(1)}<span>{tabCounts[tab]}</span></button>)}</nav>
    <section className="knowledge-control-panel"><div className="skills-search"><Icon name="Search" size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search titles, summaries, topics or sources…" /></div><select value={field} onChange={event => setField(event.target.value)}>{fields.map(item => <option key={item}>{item}</option>)}</select><select value={sourceFilter} onChange={event => setSourceFilter(event.target.value)}>{sources.map(item => <option key={item}>{item}</option>)}</select></section>
    {message && <div className="skills-message"><Icon name="Info" size={16} />{message}<button onClick={() => setMessage('')}>×</button></div>}<div className="knowledge-list-heading"><div><h3>{view === 'inbox' ? 'Unprocessed ideas' : view === 'saved' ? 'Worth returning to' : view === 'read' ? 'Already reviewed' : 'Out of the way, not gone'}</h3><span>{visible.length} item{visible.length === 1 ? '' : 's'}</span></div><p>{view === 'inbox' ? 'Open one item, decide if it matters, and leave the rest for later.' : view === 'saved' ? 'These become useful when you add a takeaway or a next action.' : view === 'read' ? 'Your reviewed knowledge and written takeaways.' : 'Restore anything you want to revisit.'}</p></div>
    <div className="knowledge-work-list">{visible.map(item => { const saved = savedIds.includes(item.id); const read = readIds.includes(item.id); const open = expanded === item.id; return <article className={`knowledge-work-item ${open ? 'expanded' : ''}`} key={item.id}><button className="knowledge-item-main" onClick={() => setExpanded(open ? null : item.id)}><div className="knowledge-source-mark"><Icon name={item.source === 'Personal capture' ? 'Lightbulb' : 'FileText'} size={18} /></div><div><div className="knowledge-item-meta"><span>{item.source}</span><span>{item.field}</span><time>{item.publishedAt}</time></div><h3>{item.title}</h3><p>{item.summary}</p></div><Icon name={open ? 'ChevronUp' : 'ChevronDown'} size={18} /></button><div className="knowledge-item-status">{saved && <span><Icon name="Bookmark" size={12} /> Saved</span>}{read && <span><Icon name="Check" size={12} /> Read</span>}{takeaways[item.id] && <span><Icon name="PenLine" size={12} /> Takeaway</span>}</div>{open && <div className="knowledge-item-detail"><div className="knowledge-why"><b>Why this may matter</b><p>{item.whyItMatters}</p></div><label>Your takeaway <small>one sentence in your own words</small><textarea rows={3} defaultValue={takeaways[item.id] || ''} id={`takeaway-${item.id}`} placeholder="What changed in your understanding?" /></label><div className="knowledge-detail-actions">{item.url && <a className="secondary" href={item.url} target="_blank" rel="noreferrer" onClick={() => { if (!read) toggle(item.id, 'read'); }}><Icon name="ArrowUpRight" size={14} /> Open source</a>}<button className={saved ? 'secondary active' : 'secondary'} onClick={() => toggle(item.id, 'saved')}><Icon name="Bookmark" size={14} />{saved ? 'Saved' : 'Save'}</button><button className="secondary" onClick={() => { const value = (document.getElementById(`takeaway-${item.id}`) as HTMLTextAreaElement)?.value || ''; saveTakeaway(item.id, value.trim()); if (!read) toggle(item.id, 'read'); }}><Icon name="Save" size={14} /> Save takeaway</button><button className="primary" onClick={() => addToToday(item)}><Icon name="Sun" size={14} /> Add to Today</button><button className="text-button" onClick={() => view === 'archive' ? restore(item) : archive(item)}>{view === 'archive' ? 'Restore' : 'Archive'}</button></div></div>}</article>; })}</div>
    {!visible.length && <div className="knowledge-empty"><Icon name={view === 'inbox' ? 'Inbox' : 'SearchX'} size={30} /><h3>{query ? 'No matching knowledge' : view === 'inbox' ? 'Inbox processed' : `Nothing in ${view} yet`}</h3><p>{view === 'inbox' ? 'Capture an idea or find fresh research when you are ready.' : 'Items will appear here as you work through the knowledge flow.'}</p>{view === 'inbox' && <button className="primary" onClick={() => setCreating(true)}>Capture an idea</button>}</div>}{creating && <CaptureKnowledge onCancel={() => setCreating(false)} onSave={addCaptured} />}</div>;
}
