import { useMemo } from 'react';
import Icon from './Icon';
import type { AppData, ResourceItem } from '../domain/types';

export default function KnowledgeGraph({ data }: { data: AppData }) {
  const resources: ResourceItem[] = useMemo(() => { try { return JSON.parse(localStorage.getItem('personal-life-os-resources') || '[]'); } catch { return []; } }, []);
  const nodes = useMemo(() => [...data.areas.slice(0,5).map(x=>({id:x.id,label:x.name,type:'Area',color:x.color})), ...data.skills.slice(0,5).map(x=>({id:x.id,label:x.name,type:'Skill',color:'#8b7cf6'})), ...(data.projects||[]).slice(0,4).map(x=>({id:x.id,label:x.name,type:'Project',color:'#d18b62'})), ...resources.slice(0,6).map(x=>({id:x.id,label:x.title,type:'Resource',color:'#62a98b'}))], [data, resources]);
  const links = useMemo(() => resources.flatMap(resource => [resource.areaId && {from:resource.id,to:resource.areaId}, resource.skillId && {from:resource.id,to:resource.skillId}, resource.projectId && {from:resource.id,to:resource.projectId}].filter(Boolean) as Array<{from:string;to:string}>), [resources]);
  const positions = nodes.map((node,index)=>({ ...node, x: 80 + (index%4)*190, y: 70 + Math.floor(index/4)*125 })); const byId = new Map(positions.map(x=>[x.id,x]));
  return <div className="content graph-page"><div className="knowledge-header"><div><span className="pill purple">KNOWLEDGE GRAPH</span><h2>See how your growth system connects.</h2><p className="muted">Areas, skills, projects and resources form a map of what you are building.</p></div><span className="muted">{nodes.length} nodes · {links.length} links</span></div>{nodes.length?<div className="graph-card"><svg viewBox="0 0 860 420" role="img" aria-label="Knowledge graph">{links.map((link,index)=>{const from=byId.get(link.from),to=byId.get(link.to);return from&&to?<line key={index} x1={from.x} y1={from.y} x2={to.x} y2={to.y} stroke="var(--line)" strokeWidth="2"/>:null})}{positions.map(node=><g key={node.id}><circle cx={node.x} cy={node.y} r="27" fill={node.color} opacity=".16" stroke={node.color} strokeWidth="2"/><text x={node.x} y={node.y-2} textAnchor="middle" fill="var(--ink)" fontSize="10" fontWeight="600">{node.label.slice(0,18)}</text><text x={node.x} y={node.y+13} textAnchor="middle" fill="var(--muted)" fontSize="8">{node.type}</text></g>)}</svg><div className="graph-legend"><span><i style={{background:'#8b7cf6'}}/> Area / Skill</span><span><i style={{background:'#d18b62'}}/> Project</span><span><i style={{background:'#62a98b'}}/> Resource</span></div></div>:<div className="empty-page"><div className="empty-icon"><Icon name="Share2" size={30}/></div><h2>Build your first connections</h2><p>Add resources and link them to a learning area, skill or project to see the graph grow.</p></div>}</div>;
}
