import {useMemo,useState} from 'react';
import Icon from './Icon';
import type{AppData,EntityRelation,ResourceItem}from'../domain/types';
import{resourceRepository}from'../repositories/legacyRepositories';
import{loadSnapshot}from'../repositories/appRepository';
import{startTaskTimer}from'../services/timeTrackingService';

type NodeType='Area'|'Skill'|'Project'|'Resource'|'Task'|'Knowledge';
type GraphNode={id:string;label:string;type:NodeType;color:string;subtitle:string;progress?:number;page:string};
type GraphLink={from:string;to:string;label:string};
const colors:Record<NodeType,string>={Area:'#6f63da',Skill:'#8b7cf6',Project:'#d18b62',Resource:'#62a98b',Task:'#5d91c5',Knowledge:'#b777a8'};
const icons:Record<NodeType,keyof typeof import('lucide-react')>={Area:'Compass',Skill:'Sparkles',Project:'FolderKanban',Resource:'Library',Task:'ListTodo',Knowledge:'BookOpen'};

export default function KnowledgeGraph({data,onOpen}:{data:AppData;onOpen?:(page:string)=>void}){
 const[filter,setFilter]=useState<'All'|NodeType>('All');const[query,setQuery]=useState('');const[selectedId,setSelectedId]=useState('');
 const openPage=(page:string)=>{if(onOpen){onOpen(page);return}const target=[...document.querySelectorAll<HTMLButtonElement>('nav button')].find(button=>button.textContent?.trim()===page);target?.click()};
 const resources:ResourceItem[]=useMemo(()=>resourceRepository.load(),[data]);const relations:EntityRelation[]=useMemo(()=>loadSnapshot().relations||[],[data]);
 const nodes=useMemo<GraphNode[]>(()=>[
  ...data.areas.map(item=>({id:item.id,label:item.name,type:'Area' as const,color:item.color||colors.Area,subtitle:item.focus||item.description,progress:item.progress,page:'Learning'})),
  ...data.skills.map(item=>({id:item.id,label:item.name,type:'Skill' as const,color:colors.Skill,subtitle:item.focus||`${item.level} → ${item.target}`,progress:item.progress,page:'Skills'})),
  ...(data.projects||[]).map(item=>({id:item.id,label:item.name,type:'Project' as const,color:item.color||colors.Project,subtitle:item.next||item.meta,progress:item.progress,page:'Projects'})),
  ...resources.map(item=>({id:item.id,label:item.title,type:'Resource' as const,color:colors.Resource,subtitle:`${item.type} · ${item.status}`,page:'Resources'})),
  ...data.tasks.map(item=>({id:item.id,label:item.title,type:'Task' as const,color:colors.Task,subtitle:`${item.status==='done'?'Completed':'Open'} · ${item.trackedMinutes||0}/${item.minutes} min`,progress:Math.min(100,Math.round((item.trackedMinutes||0)/Math.max(1,item.minutes)*100)),page:'Today'})),
  ...(data.knowledge||[]).map(item=>({id:item.id,label:item.title,type:'Knowledge' as const,color:colors.Knowledge,subtitle:`${item.source} · ${item.field}`,page:'Knowledge'})),
 ],[data,resources]);
 const links=useMemo<GraphLink[]>(()=>{const valid=new Set(nodes.map(node=>node.id));const explicit=relations.filter(item=>valid.has(item.sourceId)&&valid.has(item.targetId)).map(item=>({from:item.sourceId,to:item.targetId,label:item.relationType}));const resourceLinks=resources.flatMap(item=>[item.areaId&&{from:item.id,to:item.areaId,label:'supports area'},item.skillId&&{from:item.id,to:item.skillId,label:'builds skill'},item.projectId&&{from:item.id,to:item.projectId,label:'used in project'}].filter(Boolean) as GraphLink[]);const taskLinks=data.tasks.flatMap(item=>[item.areaId&&{from:item.id,to:item.areaId,label:'advances area'},item.skillId&&{from:item.id,to:item.skillId,label:'practices skill'},item.projectId&&{from:item.id,to:item.projectId,label:'moves project'},item.bookId&&{from:item.id,to:item.bookId,label:'studies book'}].filter(Boolean) as GraphLink[]);return[...explicit,...resourceLinks,...taskLinks].filter((item,index,array)=>index===array.findIndex(other=>other.from===item.from&&other.to===item.to&&other.label===item.label))},[data.tasks,nodes,relations,resources]);
 const degree=useMemo(()=>{const result=new Map<string,number>();links.forEach(link=>{result.set(link.from,(result.get(link.from)||0)+1);result.set(link.to,(result.get(link.to)||0)+1)});return result},[links]);
 const visible=nodes.filter(node=>(filter==='All'||node.type===filter)&&(`${node.label} ${node.subtitle}`).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(degree.get(b.id)||0)-(degree.get(a.id)||0));
 const selected=nodes.find(node=>node.id===(selectedId||visible[0]?.id));const related=selected?links.filter(link=>link.from===selected.id||link.to===selected.id).map(link=>{const otherId=link.from===selected.id?link.to:link.from;return{node:nodes.find(item=>item.id===otherId),label:link.label,direction:link.from===selected.id?'out':'in'}}).filter(item=>item.node):[];const disconnected=nodes.filter(node=>!(degree.get(node.id)||0));const counts=nodes.reduce<Record<string,number>>((result,node)=>{result[node.type]=(result[node.type]||0)+1;return result},{});const connected=nodes.length-disconnected.length;
 return <div className="content graph-page graph-workspace"><div className="graph-workspace-hero"><div><span className="pill purple">CONNECTION WORKSPACE</span><h2>Turn connections into next actions.</h2><p>Inspect what supports a goal, find isolated items and jump directly into the work behind each node.</p></div><div className="graph-health"><b>{nodes.length?Math.round(connected/nodes.length*100):0}%</b><span>connected</span></div></div>
 <div className="graph-summary"><div><span>Items mapped</span><b>{nodes.length}</b><small>Across six working types</small></div><div><span>Useful links</span><b>{links.length}</b><small>Why items belong together</small></div><div><span>Unconnected</span><b>{disconnected.length}</b><small>Potential cleanup or linking work</small></div><div><span>Open tasks</span><b>{data.tasks.filter(item=>item.status!=='done').length}</b><small>Actions available now</small></div></div>
 <div className="graph-toolbar"><div className="graph-search"><Icon name="Search" size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search the connection map"/></div><div className="graph-filters">{(['All','Area','Skill','Project','Resource','Task','Knowledge'] as const).map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}{item!=='All'&&<small>{counts[item]||0}</small>}</button>)}</div></div>
 <div className="graph-work-layout"><section className="graph-node-list"><div className="graph-results-head"><b>{visible.length} items</b><span>Most connected first</span></div>{visible.map(node=><button key={node.id} className={selected?.id===node.id?'selected':''} onClick={()=>setSelectedId(node.id)}><i style={{background:node.color}}><Icon name={icons[node.type]} size={15}/></i><span><b>{node.label}</b><small>{node.subtitle}</small></span><em>{degree.get(node.id)||0}<small>links</small></em></button>)}{!visible.length&&<div className="graph-empty"><Icon name="SearchX" size={26}/><b>No matching items</b><span>Try another filter or search.</span></div>}</section>
 <aside className="graph-inspector">{selected?<><div className="graph-inspector-head"><i style={{background:selected.color}}><Icon name={icons[selected.type]} size={18}/></i><div><span>{selected.type}</span><h3>{selected.label}</h3><p>{selected.subtitle}</p></div></div>{selected.progress!==undefined&&<div className="graph-progress"><div><span>Progress</span><b>{selected.progress}%</b></div><div className="progress"><i style={{width:`${selected.progress}%`,background:selected.color}}/></div></div>}<div className="graph-inspector-actions"><button className="primary" onClick={()=>openPage(selected.page)}><Icon name="ArrowUpRight" size={14}/> Open {selected.page==='Learning'?'Learning Areas':selected.page}</button>{selected.type==='Task'&&data.tasks.find(item=>item.id===selected.id)?.status!=='done'&&<button className="secondary" onClick={()=>{const task=data.tasks.find(item=>item.id===selected.id);if(task)startTaskTimer(task);openPage('Time Tracking')}}><Icon name="Clock3" size={14}/> Start timer</button>}</div><section><div className="graph-section-title"><b>Connected to</b><span>{related.length}</span></div>{related.length?<div className="graph-related-list">{related.map(({node,label,direction})=><button key={`${node!.id}-${label}`} onClick={()=>setSelectedId(node!.id)}><i style={{background:node!.color}}/><span><b>{node!.label}</b><small>{direction==='out'?label:`${label} this item`}</small></span><Icon name="ChevronRight" size={14}/></button>)}</div>:<div className="graph-no-links"><Icon name="Unlink" size={20}/><b>This item is isolated</b><p>Connect it by assigning a Task or Resource to the same Area, Skill or Project.</p></div>}</section></>:<div className="graph-empty"><Icon name="Share2" size={28}/><b>Select an item</b><span>Its useful connections will appear here.</span></div>}</aside></div>
 {disconnected.length>0&&<section className="graph-blind-spots"><div><span className="pill teal">BLIND SPOTS</span><h3>Items that are not helping anything yet</h3><p>Open one and connect it through a Task, Resource, Area, Skill or Project.</p></div><div>{disconnected.slice(0,8).map(node=><button key={node.id} onClick={()=>{setFilter('All');setQuery('');setSelectedId(node.id)}}><i style={{background:node.color}}/><span><b>{node.label}</b><small>{node.type}</small></span><Icon name="ArrowRight" size={14}/></button>)}</div></section>}
 </div>;
}
