import { useEffect, useMemo, useState } from 'react';
import { localDateKey } from '../domain/date';

const items = ['睡前不在床上玩手机，把手机放在够不到的位置','起床默念 321，快速铺好床铺','用闹钟代替手机闹铃','10 分钟以内运动','洗澡：热水淋浴＋冷水 90 秒','喝水、维生素和鱼油','带一杯咖啡到室外，写下一天计划','看书 15 分钟','冥想 3 分钟','开始完成最困难的工作'];
const storageKey = 'personal-life-os-morning-checklist-v1';
type Stored = { date: string; checked: boolean[]; completedDates: string[] };
const read = (): Stored => { try { const value = JSON.parse(localStorage.getItem(storageKey) || 'null'); if (value?.date && Array.isArray(value.checked)) return value; } catch {} return { date: localDateKey(), checked: items.map(() => false), completedDates: [] }; };

export default function MorningChecklist() {
  const [stored, setStored] = useState<Stored>(() => read());
  const today = localDateKey();
  const current = stored.date === today ? stored : { ...stored, date: today, checked: items.map(() => false) };
  const done = current.checked.filter(Boolean).length;
  const streak = useMemo(() => { let count = 0; const dates = new Set(current.completedDates); const cursor = new Date(`${today}T12:00:00`); while (dates.has(localDateKey(cursor))) { count++; cursor.setDate(cursor.getDate() - 1); } return count; }, [current.completedDates, today]);
  const [alarmTime, setAlarmTime] = useState(() => localStorage.getItem('personal-life-os-morning-alarm-time') || '07:00');
  const [alarmEnabled, setAlarmEnabled] = useState(() => localStorage.getItem('personal-life-os-morning-alarm-enabled') === 'true');
  const [alarmMessage, setAlarmMessage] = useState('');
  useEffect(() => { if (!alarmEnabled) return; const check = () => { const now = new Date(); const time = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`; const fired = `personal-life-os-alarm-fired-${today}`; if (time === alarmTime && localStorage.getItem(fired) !== 'true') { localStorage.setItem(fired, 'true'); setAlarmMessage('Alarm sent'); if ('Notification' in window && Notification.permission === 'granted') new Notification('Personal Life OS · Morning', { body: 'Good morning. Start your morning checklist.', tag: 'personal-life-os-morning' }); if ('vibrate' in navigator) navigator.vibrate([250, 120, 250]); } }; check(); const timer = window.setInterval(check, 15000); return () => window.clearInterval(timer); }, [alarmEnabled, alarmTime, today]);
  const update = (checked: boolean[]) => { const complete = checked.every(Boolean); const completedDates = complete && !current.completedDates.includes(today) ? [today, ...current.completedDates].slice(0, 365) : current.completedDates.filter(date => date !== today); const next = { date: today, checked, completedDates }; setStored(next); localStorage.setItem(storageKey, JSON.stringify(next)); };
  const enableAlarm = async () => { if ('Notification' in window && Notification.permission === 'default') await Notification.requestPermission(); setAlarmEnabled(true); localStorage.setItem('personal-life-os-morning-alarm-enabled', 'true'); setAlarmMessage('Alarm enabled'); };
  const disableAlarm = () => { setAlarmEnabled(false); localStorage.setItem('personal-life-os-morning-alarm-enabled', 'false'); setAlarmMessage('Alarm off'); };
  return <section className="morning-checklist"><div className="morning-alarm"><div><b>Morning alarm</b><small>Repeats every day and reminds you to begin this checklist.</small></div><input type="time" value={alarmTime} onChange={event => { setAlarmTime(event.target.value); localStorage.setItem('personal-life-os-morning-alarm-time', event.target.value); }} /><button className={alarmEnabled ? 'secondary' : 'primary'} onClick={alarmEnabled ? disableAlarm : enableAlarm}>{alarmEnabled ? 'Turn off' : 'Set alarm'}</button>{alarmMessage && <small className="alarm-message">{alarmMessage}</small>}</div><div className="morning-head"><div><span className="pill teal">MORNING CHECKLIST</span><h3>Start the day on purpose.</h3><p className="muted">{done}/{items.length} complete · {streak} day streak</p></div><strong>{Math.round(done / items.length * 100)}%</strong></div><div className="morning-progress"><i style={{ width: `${done / items.length * 100}%` }} /></div><div className="morning-items">{items.map((item, index) => <label className={current.checked[index] ? 'morning-item checked' : 'morning-item'} key={item}><input type="checkbox" checked={Boolean(current.checked[index])} onChange={event => { const next = [...current.checked]; next[index] = event.target.checked; update(next); }} /><span>{index + 1}</span><b>{item}</b></label>)}</div><button className="secondary" onClick={() => update(items.map(() => false))}>Reset today</button></section>;
}
