import { useMemo, useState } from 'react';
import Icon from './Icon';
import PersonMedia from './PersonMedia';
import type { Person } from '../domain/people';
import { peopleRepository } from '../repositories/legacyRepositories';
import { useAppStore } from '../store/useAppStore';
import { localDateKey } from '../domain/date';

type View='followup'|'all'|'recent';
const defaults:Person[]=[{id:'person-1',name:'Alex Chen',relationship:'Friend · Research collaborator',organisation:'Independent',location:'New York',interests:['BCI','R','Photography'],notes:'Learning R and interested in reading BCI papers together.',lastInteraction:'Today',nextFollowUp:'Next week',cadence:'Every 2 weeks',interactions:[]},{id:'person-2',name:'Maya Patel',relationship:'Mentor',organisation:'NeuroTech Lab',location:'Boston',interests:['Neuroscience','Scientific writing'],notes:'Ask about the latest motor imagery papers.',lastInteraction:'12 days ago',nextFollowUp:'In 2 days',cadence:'Monthly',interactions:[]}];
const blank=():Person=>({id:`person-${Date.now()}`,name:'',relationship:'Friend',organisation:'',location:'',interests:[],notes:'',lastInteraction:'Not yet',nextFollowUp:'Set a follow-up',cadence:'Monthly',interactions:[]});

function PersonPanel({person,onCancel,onSave,onDelete}:{person:Person;onCancel:()=>void;onSave:(person:Person)=>void;onDelete:(person:Person)=>void}){
 const[draft,setDraft]=useState({...person,interestsText:(person.interests||[]).join(', ')});const[deleteReady,setDeleteReady]=useState(false);const set=(key:string,value:string)=>setDraft(current=>({...current,[key]:value}));
 return <div className="modal-backdrop" onMouseDown={onCancel}><form className="create-modal people-panel" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();if(!draft.name.trim())return;onSave({...person,...draft,name:draft.name.trim(),interests:draft.interestsText.split(',').map(value=>value.trim()).filter(Boolean)})}}><div className="modal-head"><div><span className="pill purple">PERSON PROFILE</span><h2>{person.name?'Edit relationship':'Add someone important'}</h2></div><button type="button" className="modal-close" onClick={onCancel}>×</button></div><label>Name<input autoFocus value={draft.name} onChange={event=>set('name',event.target.value)} placeholder="Name"/></label><div className="form-two"><label>Relationship<input value={draft.relationship||''} onChange={event=>set('relationship',event.target.value)} placeholder="Friend, mentor…"/></label><label>Contact rhythm<select value={draft.cadence||'Monthly'} onChange={event=>set('cadence',event.target.value)}><option>Weekly</option><option>Every 2 weeks</option><option>Monthly</option><option>Every 3 months</option><option>As needed</option></select></label></div><div className="form-two"><label>Organisation<input value={draft.organisation||''} onChange={event=>set('organisation',event.target.value)} placeholder="Lab, company, community"/></label><label>Location<input value={draft.location||''} onChange={event=>set('location',event.target.value)} placeholder="City or timezone"/></label></div><label>Interests and shared topics<input value={draft.interestsText} onChange={event=>set('interestsText',event.target.value)} placeholder="BCI, music, research"/></label><label>What should you remember?<textarea rows={5} value={draft.notes||''} onChange={event=>set('notes',event.target.value)} placeholder="Context, preferences, things to ask about…"/></label><div className="form-two"><label>Last interaction<input value={draft.lastInteraction||''} onChange={event=>set('lastInteraction',event.target.value)} placeholder="Today, 3 days ago…"/></label><label>Next follow-up<input value={draft.nextFollowUp||''} onChange={event=>set('nextFollowUp',event.target.value)} placeholder="Next week, 12 Oct…"/></label></div>{deleteReady&&<div className="panel-danger-confirm"><span><b>Remove this person?</b><small>The relationship timeline will also be removed.</small></span><button type="button" onClick={()=>onDelete(person)}>Remove</button><button type="button" onClick={()=>setDeleteReady(false)}>Keep</button></div>}<div className="modal-actions">{person.name&&!deleteReady&&<button type="button" className="text-button danger-action" onClick={()=>setDeleteReady(true)}>Remove person</button>}<button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={!draft.name.trim()}><Icon name="Save" size={15}/> Save profile</button></div></form></div>;
}

function InteractionPanel({person,onCancel,onSave}:{person:Person;onCancel:()=>void;onSave:(note:string,channel:string)=>void}){const[note,setNote]=useState('');const[channel,setChannel]=useState('Conversation');return <div className="modal-backdrop" onMouseDown={onCancel}><form className="create-modal interaction-panel" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();onSave(note.trim()||'Interaction recorded',channel)}}><div className="modal-head"><div><span className="pill teal">INTERACTION</span><h2>What happened with {person.name}?</h2></div><button type="button" className="modal-close" onClick={onCancel}>×</button></div><label>Channel<select value={channel} onChange={event=>setChannel(event.target.value)}><option>Conversation</option><option>Message</option><option>Call</option><option>Meeting</option><option>Email</option><option>Activity</option></select></label><label>What do you want to remember?<textarea autoFocus rows={6} value={note} onChange={event=>setNote(event.target.value)} placeholder="Topics discussed, promises, follow-ups…"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary"><Icon name="Check" size={15}/> Save interaction</button></div></form></div>}

export default function PeopleWorkspace(){
 const{data,setData}=useAppStore();const[people,setPeople]=useState<Person[]>(()=>peopleRepository.load().length?peopleRepository.load():defaults);const[query,setQuery]=useState('');const[view,setView]=useState<View>('followup');const[editing,setEditing]=useState<Person|null>(null);const[logging,setLogging]=useState<Person|null>(null);const[selected,setSelected]=useState<Person|null>(null);const[message,setMessage]=useState('');
 const save=(next:Person[])=>{setPeople(next);peopleRepository.save(next)};const needsFollowUp=(person:Person)=>person.nextFollowUp&&person.nextFollowUp!=='Set a follow-up';const visible=useMemo(()=>people.filter(person=>(view==='all'||(view==='followup'&&needsFollowUp(person))||(view==='recent'&&(person.interactions||[]).length>0))&&`${person.name} ${person.relationship} ${person.organisation} ${person.interests.join(' ')} ${person.notes}`.toLowerCase().includes(query.toLowerCase())),[people,query,view]);
 const update=(person:Person)=>{save(people.some(item=>item.id===person.id)?people.map(item=>item.id===person.id?person:item):[person,...people]);setEditing(null);setSelected(person);setMessage(`${person.name}'s profile was saved.`)};const remove=(person:Person)=>{save(people.filter(item=>item.id!==person.id));setEditing(null);setSelected(null);setMessage(`${person.name} was removed.`)};
 const log=(person:Person,note:string,channel:string)=>{const next={...person,lastInteraction:'Today',nextFollowUp:person.cadence==='Weekly'?'Next week':person.cadence==='Every 2 weeks'?'In 2 weeks':'Next month',interactions:[{id:`interaction-${Date.now()}`,date:'Today',note,channel},...(person.interactions||[])].slice(0,50)};save(people.map(item=>item.id===person.id?next:item));setLogging(null);setSelected(next);setMessage(`Interaction with ${person.name} recorded.`)};
 const addFollowUp=(person:Person)=>{const marker=`Person: ${person.id}`;if(data.tasks.some(task=>task.notes?.includes(marker)&&task.status!=='done'))return setMessage('This follow-up is already in Today.');setData(current=>({...current,tasks:[{id:`people-task-${Date.now()}`,title:`Follow up with ${person.name}`,description:person.notes||`Reconnect with ${person.name}.`,minutes:15,difficulty:'Easy',category:'Manual',timeCategory:'Connection',scheduledDate:localDateKey(),priority:'Medium',status:'todo',notes:marker},...current.tasks]}));setMessage(`Follow-up with ${person.name} added to Today.`)};
 const interactionCount=people.reduce((sum,person)=>sum+(person.interactions||[]).length,0);const followupCount=people.filter(needsFollowUp).length;
 return <div className="content people-workspace"><section className="people-workspace-hero"><div><span className="pill purple">RELATIONSHIP WORKSPACE</span><h2>Remember the person, not just the contact.</h2><p>Keep context, shared interests and promises visible—then make the next conversation easier.</p></div><button className="primary" onClick={()=>setEditing(blank())}><Icon name="UserPlus" size={16}/> Add person</button></section><div className="people-summary-grid"><div><span>People</span><b>{people.length}</b><small>relationships remembered</small></div><div><span>Follow-ups</span><b>{followupCount}</b><small>next contact planned</small></div><div><span>Interactions</span><b>{interactionCount}</b><small>moments in the timeline</small></div></div><nav className="people-tabs">{([['followup','Follow-ups',followupCount],['all','Everyone',people.length],['recent','Recent activity',people.filter(person=>(person.interactions||[]).length).length]] as [View,string,number][]).map(([key,label,count])=><button className={view===key?'active':''} key={key} onClick={()=>setView(key)}><Icon name={key==='followup'?'BellRing':key==='all'?'Users':'History'} size={15}/>{label}<span>{count}</span></button>)}</nav><div className="people-workspace-search"><Icon name="Search" size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search people, organisations, interests or notes…"/></div>{message&&<div className="skills-message"><Icon name="CheckCircle2" size={16}/>{message}<button onClick={()=>setMessage('')}>×</button></div>}
 <div className="people-work-layout"><div className="people-work-list">{visible.map(person=><button className={'people-list-card '+(selected?.id===person.id?'selected':'')} key={person.id} onClick={()=>setSelected(person)}><PersonMedia name={person.name} avatar={person.avatar} images={person.images} onChange={(avatar,images)=>save(people.map(item=>item.id===person.id?{...item,avatar,images}:item))}/><span className="grow"><b>{person.name}</b><small>{person.relationship||'Add relationship'}{person.organisation?` · ${person.organisation}`:''}</small><em>{person.notes||'Add something worth remembering.'}</em></span><span className="people-next"><small>NEXT</small><b>{person.nextFollowUp||'Not set'}</b></span><Icon name="ChevronRight" size={16}/></button>)}{!visible.length&&<div className="people-work-empty"><Icon name="Users" size={27}/><h3>No people in this view</h3><p>Try another view or add someone you want to keep in mind.</p></div>}</div>
 <aside className="people-detail-panel">{selected?<><div className="people-detail-head"><PersonMedia name={selected.name} avatar={selected.avatar} images={selected.images} onChange={(avatar,images)=>save(people.map(item=>item.id===selected.id?{...item,avatar,images}:item))}/><div><h3>{selected.name}</h3><p>{selected.relationship||'Relationship not set'}</p></div><button className="icon-button" onClick={()=>setEditing(selected)}><Icon name="Pencil" size={15}/></button></div><div className="people-detail-actions"><button className="primary" onClick={()=>setLogging(selected)}><Icon name="MessageCircle" size={14}/> Log interaction</button><button className="secondary" onClick={()=>addFollowUp(selected)}><Icon name="Sun" size={14}/> Add to Today</button></div><section><small>REMEMBER</small><p>{selected.notes||'No context saved yet.'}</p></section><section><small>SHARED INTERESTS</small><div className="chips">{selected.interests.length?selected.interests.map(value=><span key={value}>{value}</span>):<span className="muted">None added yet</span>}</div></section><div className="people-detail-meta"><span><small>LAST CONTACT</small><b>{selected.lastInteraction||'Not yet'}</b></span><span><small>NEXT FOLLOW-UP</small><b>{selected.nextFollowUp||'Not set'}</b></span><span><small>RHYTHM</small><b>{selected.cadence||'Not set'}</b></span></div><section className="people-timeline"><div className="section-title"><h3>Timeline</h3><span>{(selected.interactions||[]).length}</span></div>{(selected.interactions||[]).map(entry=><div key={entry.id}><span className="timeline-dot"/><b>{entry.date}</b><small>{entry.channel}</small><p>{entry.note}</p></div>)}{!(selected.interactions||[]).length&&<p className="muted">No interactions yet. Log the next conversation to start the timeline.</p>}</section></>:<div className="people-detail-empty"><Icon name="ContactRound" size={30}/><h3>Select a person</h3><p>Their context, follow-up and timeline will appear here.</p></div>}</aside></div>{editing&&<PersonPanel person={editing} onCancel={()=>setEditing(null)} onSave={update} onDelete={remove}/>} {logging&&<InteractionPanel person={logging} onCancel={()=>setLogging(null)} onSave={(note,channel)=>log(logging,note,channel)}/>}</div>;
}
