import { useEffect, useMemo, useState } from 'react';
import Icon from './Icon';
import ActionMenu from './ActionMenu';
import TaskEditor from './TaskEditor';
import { useAppStore } from '../store/useAppStore';
import { createTaskTimeEntry, saveTrackedTimeEntry } from '../services/timeTrackingService';
import { clearTaskTimer, elapsedTaskSeconds, emptyTaskTimer, loadTaskTimer, pauseTaskClock, saveTaskTimer, startTaskClock, type PersistedTaskTimer } from '../services/taskTimerPersistence';

export default function PersistentTaskRow({task,toggle,onDelete}:{task:any;toggle:()=>void;onDelete?:(id:string)=>void}){
 const{data,adjustTaskDifficulty,setData}=useAppStore();const[editing,setEditing]=useState<any>(null);const[open,setOpen]=useState(false);const[timer,setTimer]=useState<PersistedTaskTimer>(()=>loadTaskTimer(task.id));const[now,setNow]=useState(Date.now());const[deleteReady,setDeleteReady]=useState(false);const live=task;const target=Math.max(1,Number(live.minutes||0)*60);
 useEffect(()=>{setTimer(loadTaskTimer(task.id));setNow(Date.now())},[task.id]);
 useEffect(()=>{saveTaskTimer(task.id,timer)},[task.id,timer]);
 useEffect(()=>{if(!timer.running)return;const refresh=()=>setNow(Date.now());const interval=window.setInterval(refresh,1000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.clearInterval(interval);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[timer.running]);
 const elapsed=useMemo(()=>Math.min(target,elapsedTaskSeconds(timer,now)),[timer,now,target]);const trackedElapsed=Number(live.trackedMinutes||0)*60+elapsed;
 useEffect(()=>{if(timer.running&&elapsed>=target)setTimer({accumulatedSeconds:target,startedAt:null,running:false})},[elapsed,target,timer.running]);
 const toggleClock=()=>{const stamp=Date.now();setNow(stamp);setTimer(current=>current.running?pauseTaskClock(current,stamp):startTaskClock(current,stamp))};
 const reset=()=>{const next=emptyTaskTimer();setTimer(next);setNow(Date.now());clearTaskTimer(task.id)};
 const saveInline=()=>{if(elapsed<1)return;const end=new Date();const minutes=Math.max(1,Math.round(elapsed/60));saveTrackedTimeEntry(createTaskTimeEntry(live,new Date(end.getTime()-elapsed*1000).toISOString(),end.toISOString(),minutes,`${live.title} session`));reset()};
 const format=(value:number)=>`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;
 const remove=()=>{if(deleteReady){(onDelete?onDelete(live.id):setData(current=>({...current,tasks:current.tasks.filter(item=>item.id!==live.id)})));clearTaskTimer(live.id)}else{setDeleteReady(true);setOpen(true)}};
 return <div className={'task-row '+(live.status==='done'?'done':'')}><button className="check" onClick={toggle}>{live.status==='done'&&<Icon name="Check" size={13}/>}</button><button className="task-body" onClick={()=>setOpen(!open)}><b>{live.title}</b><small>{live.description}{live.source&&<span className="task-source"> · {live.source}{live.questId?' quest':''}{live.habitId?' habit':''}{live.bookId?' knowledge':''}</span>}</small></button><span className="tag">{live.minutes} min{live.trackedMinutes>0&&<small> · {live.trackedMinutes}m tracked</small>}</span>{live.priority&&<span className="task-priority">{live.priority}</span>}<button className={'difficulty difficulty-'+String(live.difficulty||'Easy').toLowerCase()} onClick={()=>adjustTaskDifficulty(live.id)}>{live.difficulty}</button><button className={'task-track-button '+(timer.running?'running':'')} onClick={()=>{setOpen(true);toggleClock()}} title={timer.running?'Pause this timer':'Start this timer'}><Icon name={timer.running?'Pause':'Clock3'} size={13}/></button><ActionMenu items={[{label:timer.running?'Pause timer':'Start timer',onClick:()=>{setOpen(true);toggleClock()}},{label:'Edit details',onClick:()=>setEditing(live)},{label:'Duplicate task',onClick:()=>setData(current=>({...current,tasks:[{...live,id:'task-'+Date.now(),status:'todo',completedAt:undefined},...current.tasks]}))},{label:live.status==='done'?'Mark incomplete':'Mark complete',onClick:toggle},{label:'Delete task',danger:true,onClick:remove}]}/>{open&&<div className="task-detail" onClick={event=>event.stopPropagation()}><div className="task-detail-head"><div><b>{timer.running?'Timer running':elapsed?'Timer paused':'Task timer'}</b>{timer.running&&<small className="timer-persistence-note">Keeps running when you leave this page</small>}</div><span>{format(trackedElapsed)} / {format(target)}</span></div><div className="progress task-timer-progress"><i style={{width:`${Math.min(100,trackedElapsed/target*100)}%`}}/></div><div className="task-detail-actions"><button className="primary" onClick={toggleClock}><Icon name={timer.running?'Pause':'Play'} size={14}/>{timer.running?'Pause':elapsed?'Resume':'Start timer'}</button><button className="secondary" onClick={reset}><Icon name="RefreshCw" size={14}/> Reset</button>{elapsed>0&&<button className="secondary" onClick={saveInline}>Save session</button>}{trackedElapsed>=target&&<button className="secondary" onClick={toggle}>Mark complete</button>}</div>{deleteReady&&<div className="task-delete-confirm"><span><b>Delete this task?</b><small>The running timer will also be removed.</small></span><button onClick={remove}>Delete</button><button onClick={()=>setDeleteReady(false)}>Keep</button></div>}</div>}{editing&&<TaskEditor task={editing} projects={data.projects||[]} onCancel={()=>setEditing(null)} onSave={(next:any)=>{setData(current=>({...current,tasks:current.tasks.map(item=>item.id===next.id?next:item)}));setEditing(null)}}/>}</div>;
}
