import{useMemo,useState}from'react';
import Icon from'./Icon';
import type{AppData}from'../domain/types';
import{familyCoverage,inferArchetype,makeQuest,migrateQuest,prerequisitesMet,promotionRequirements,questFamilies,questVariants,rankNames,requirementProgress,requirementsMet,selectBalancedVariants,type AreaRank,type Quest,type QuestType,type Rank}from'../domain/quests';
import{completeQuest,undoQuest}from'../domain/questActions';
import{grantQuestReward,maybeRewardDrop}from'../services/rewardService';
const KEY='personal-life-os-quest-board-v1';
type State={ranks:AreaRank[];quests:Quest[]};
const load=():State=>{try{const raw=JSON.parse(localStorage.getItem(KEY)||'{"ranks":[],"quests":[]}');return{ranks:Array.isArray(raw.ranks)?raw.ranks:[],quests:Array.isArray(raw.quests)?raw.quests.map(migrateQuest):[]}}catch{return{ranks:[],quests:[]}}};
const save=(state:State)=>localStorage.setItem(KEY,JSON.stringify({...state,schemaVersion:2}));
const rankFor=(state:State,id:string,name:string):AreaRank=>state.ranks.find(r=>r.targetId===id)||{targetId:id,targetName:name,rank:1,dailyCompleted:0,weeklyCompleted:0,promotionUnlocked:false,promotionCompleted:false,familyProgress:{}};
const difficultyLabel=(n:number)=>['','Easy','Easy','Medium','Hard','Expert'][n];

export default function QuestBoard({data,setData,onBack}:{data:AppData;setData:(updater:any)=>void;onBack?:()=>void}){
 const targets=useMemo(()=>[...data.areas.map(a=>({id:a.id,name:a.name})),...(data.interests||[]).filter(i=>i.status!=='archived').map(i=>({id:i.id,name:i.name}))],[data.areas,data.interests]);
 const[state,setState]=useState<State>(load);const[selectedArea,setSelectedArea]=useState(targets[0]?.id||'');const[family,setFamily]=useState('all');const[rank,setRank]=useState<'all'|Rank>('all');const[type,setType]=useState<'all'|QuestType>('all');const[difficulty,setDifficulty]=useState('all');const[availability,setAvailability]=useState('all');const[completion,setCompletion]=useState('all');const[history,setHistory]=useState(false);
 const target=targets.find(t=>t.id===selectedArea)||targets[0];if(!target)return <div className="content"><h2>Quest Library</h2><p>Add a Learning Area first.</p></div>;
 const areaRank=rankFor(state,target.id,target.name);const currentRank=Math.max(1,Math.min(8,areaRank.rank)) as Rank;const families=questFamilies(target.name);const coverage=familyCoverage(state.quests.filter(q=>q.targetId===target.id),families);const requirements=promotionRequirements(inferArchetype(target.name),currentRank);const promotionReady=requirementsMet(requirements,state.quests.filter(q=>q.targetId===target.id&&q.status==='completed'));
 const update=(next:State)=>{setState(next);save(next)};
 const generate=()=>{const areaHistory=state.quests.filter(q=>q.targetId===target.id);const variants=questVariants(target.name,currentRank).filter(v=>v.type!=='PROMOTION'&&v.type!=='BOSS');const chosen=selectBalancedVariants(variants,areaHistory,Number(localStorage.getItem('personal-life-os-daily-quest-count')||3),{availableMinutes:30,projectTerms:data.projects?.map(p=>p.name)||[]});update({...state,quests:[...state.quests.filter(q=>q.targetId!==target.id||q.status==='completed'||q.status==='accepted'),...chosen.map(v=>makeQuest(v,target.id,target.name,areaHistory))]})};
 const ensureMilestones=()=>{const variants=questVariants(target.name,currentRank);const milestones=variants.filter(v=>v.type==='PROMOTION'||v.type==='BOSS').map(v=>({...makeQuest(v,target.id,target.name,state.quests),locked:v.type==='PROMOTION'?!promotionReady:currentRank<8}));const byVariant=new Map(milestones.map(q=>[q.variantId,q]));const existing=new Set(state.quests.map(q=>q.variantId));update({...state,quests:[...state.quests.map(q=>q.status==='completed'?q:byVariant.has(q.variantId)?{...q,locked:byVariant.get(q.variantId)!.locked}:q),...milestones.filter(q=>!existing.has(q.variantId))]})};
 const accept=(q:Quest)=>{if(q.locked)return;setData((d:AppData)=>({...d,tasks:[{id:`quest-task-${q.id}`,title:q.title,description:q.description,minutes:q.minutes,difficulty:q.difficulty<=2?'Easy':q.difficulty===3?'Medium':'Hard',category:'Daily progress',source:'quest',questId:q.id,status:'todo'},...d.tasks]}));update({...state,quests:state.quests.map(x=>x.id===q.id?{...x,status:'accepted'}:x)})};
 const complete=(q:Quest)=>{const needsEvidence=q.type!=='DAILY';const evidence=needsEvidence?window.prompt(`Add ${q.evidenceType||'evidence'} for completion:`,''):'';if(needsEvidence&&!evidence?.trim())return;const next=completeQuest(state,q.id,evidence||'');setData((d:AppData)=>({...d,tasks:d.tasks.map(t=>t.questId===q.id?{...t,status:'done',completedAt:new Date().toISOString()}:t)}));grantQuestReward(q.type,q.difficulty,q.id,q.title);maybeRewardDrop(q.type,q.difficulty,q.id);update(next)};
 const undo=(q:Quest)=>{setData((d:AppData)=>({...d,tasks:d.tasks.map(t=>t.questId===q.id?{...t,status:'todo',completedAt:undefined}:t)}));update(undoQuest(state,q.id))};
 const completedAreaQuests=state.quests.filter(q=>q.targetId===target.id&&q.status==='completed');const areaQuests=state.quests.filter(q=>q.targetId===target.id).map(q=>q.status==='completed'?q:{...q,locked:q.type==='PROMOTION'?q.rank!==currentRank||!requirementsMet(q.unlockConditions||[],completedAreaQuests):q.type==='BOSS'?currentRank<8:!prerequisitesMet(q,completedAreaQuests)});const visible=areaQuests.filter(q=>(family==='all'||q.familyId===family)&&(rank==='all'||q.rank===rank)&&(type==='all'||q.type===type)&&(difficulty==='all'||q.difficulty===Number(difficulty))&&(availability==='all'||(availability==='locked')===Boolean(q.locked))&&(completion==='all'||(completion==='completed')===(q.status==='completed'))).sort((a,b)=>Number(Boolean(a.locked))-Number(Boolean(b.locked))||Number(a.rank||1)-Number(b.rank||1));
 if(history){const completed=state.quests.filter(q=>q.status==='completed').sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));return <div className="content"><button className="back-link" onClick={()=>setHistory(false)}><Icon name="ArrowLeft" size={15}/> Quest Library</button><div className="toolbar"><div><span className="pill teal">QUEST HISTORY</span><h2>Evidence of progress.</h2><p className="muted">V1 completions are preserved and mapped into V2 families.</p></div></div><div className="quest-history-list">{completed.map(q=><article className="quest-history-row" key={q.id}><div><span className="pill">{q.type} · R{q.rank||1}</span><h3>{q.title}</h3><small>{q.targetName} · {q.familyId?.split('-').slice(-2).join(' ')}</small></div><p>{q.evidence||'Legacy completion preserved.'}</p></article>)}</div></div>}
 return <div className="content quest-v2"><div className="toolbar"><div><button className="back-link" onClick={onBack}><Icon name="ArrowLeft" size={15}/> Dashboard</button><span className="pill purple">QUEST LIBRARY V2</span><h2>Build capability, not a task pile.</h2><p className="muted">Area → Archetype → Family → Rank → Variant → Quest</p></div><div className="today-actions"><button className="secondary" onClick={()=>setHistory(true)}><Icon name="History" size={15}/> History</button><button className="secondary" onClick={ensureMilestones}>Refresh milestones</button><button className="primary" onClick={generate}><Icon name="RefreshCw" size={15}/> Plan balanced quests</button></div></div>
 <section className="quest-v2-overview"><label>Area<select value={target.id} onChange={e=>{setSelectedArea(e.target.value);setFamily('all')}}>{targets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div><small>ARCHETYPE</small><b>{inferArchetype(target.name)}</b></div><div><small>CURRENT RANK</small><b>R{currentRank} · {rankNames[currentRank-1]}</b></div><div><small>FAMILY COVERAGE</small><b>{Object.values(coverage).filter(x=>x.completed>0).length} / {families.length}</b></div></section>
 <section className="quest-family-grid">{families.map(f=><button className={family===f.id?'active':''} key={f.id} onClick={()=>setFamily(family===f.id?'all':f.id)}><span>{f.name}</span><b>{coverage[f.id]?.completed||0}</b><small>{coverage[f.id]?.lastCompletedAt?'Last '+new Date(coverage[f.id].lastCompletedAt!).toLocaleDateString():'Needs coverage'}</small></button>)}</section>
 <section className="quest-promotion-panel"><div><span className="pill teal">PROMOTION GATE</span><h3>{promotionReady?'Ready for a real Promotion Quest':'Requirements before the Promotion Quest unlocks'}</h3></div><ul>{requirements.map(r=>{const progress=requirementProgress(r,completedAreaQuests);return <li className={progress.complete?'done':''} key={r.label}>{r.label} <strong>{progress.current} / {progress.target}</strong></li>})}</ul></section>
 <div className="quest-filter-bar"><select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">All families</option>{families.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select><select value={rank} onChange={e=>setRank(e.target.value==='all'?'all':Number(e.target.value) as Rank)}><option value="all">All ranks</option>{rankNames.map((n,i)=><option value={i+1} key={n}>R{i+1} {n}</option>)}</select><select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="all">All types</option>{['DAILY','WEEKLY','CHALLENGE','PROMOTION','BOSS'].map(x=><option key={x}>{x}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="all">All difficulty</option>{[1,2,3,4,5].map(x=><option key={x} value={x}>{difficultyLabel(x)}</option>)}</select><select value={availability} onChange={e=>setAvailability(e.target.value)}><option value="all">Locked + unlocked</option><option value="available">Unlocked</option><option value="locked">Locked</option></select><select value={completion} onChange={e=>setCompletion(e.target.value)}><option value="all">Completed + available</option><option value="available">Available</option><option value="completed">Completed</option></select></div>
 <div className="quest-list">{visible.map(q=><article className={`quest-card quest-${q.type.toLowerCase()} ${q.locked?'quest-locked':''}`} key={q.id}><div className="quest-card-top"><span className="pill">{q.type}</span><span>R{q.rank||1} · {difficultyLabel(q.difficulty)} · {q.minutes} min</span></div><h3>{q.title}</h3><p>{q.description}</p><small>{families.find(f=>f.id===q.familyId)?.name||'Legacy / General'} · Evidence: {q.evidenceType||'NOTE'}</small>{q.acceptanceCriteria?.length?<details><summary>Done when</summary><ul>{q.acceptanceCriteria.map(c=><li key={c}>{c}</li>)}</ul></details>:null}<div className="quest-actions">{q.locked?<button disabled>Locked</button>:q.status==='available'?<button className="primary" onClick={()=>accept(q)}>Accept to Today</button>:q.status==='accepted'?<button className="secondary" onClick={()=>complete(q)}>Complete with evidence</button>:q.status==='completed'?<button className="secondary" onClick={()=>undo(q)}>Undo completion</button>:null}<button className="secondary" onClick={()=>update({...state,quests:state.quests.filter(x=>x.id!==q.id)})}>Remove</button></div></article>)}{!visible.length&&<div className="empty-page"><Icon name="Target" size={28}/><h2>No matching quests</h2><p>Generate a balanced set or relax the filters.</p></div>}</div></div>;
}
