import { useEffect, useMemo, useState } from 'react';
import Icon from './Icon';
import type { AppData } from '../domain/types';
import { defaultQuestPool, makeQuest, prerequisitesMet, questTemplates, rankNames, weightedSample, type AreaRank, type Quest } from '../domain/quests';
import { appendActivity } from '../repositories/appRepository';

const KEY='personal-life-os-quest-board-v1';
const read=<T,>(fallback:T):T=>{try{return JSON.parse(localStorage.getItem(KEY)||'')||fallback}catch{return fallback}};
export default function QuestBoard({data,setData}:{data:AppData;setData:(updater:any)=>void}){
 const targets=useMemo(()=>{const existing=[...data.areas.map(x=>({id:x.id,name:x.name})),...(data.interests||[]).filter(x=>x.status!=='archived').map(x=>({id:x.id,name:x.name}))];const names=new Set(existing.map(x=>x.name.toLowerCase()));return [...existing,...defaultQuestPool.map(x=>({id:`seed-board-${x.area}`,name:x.area})).filter(x=>!names.has(x.name.toLowerCase())).filter((x,i,a)=>a.findIndex(y=>y.name===x.name)===i)]},[data.areas,data.interests]);
 const saved=read<{ranks:AreaRank[];quests:Quest[]}>({ranks:[],quests:[]});const seedQuests=defaultQuestPool.slice(0,3).map(item=>makeQuest(item as any,targets.find(x=>x.name===item.area)?.id||`seed-board-${item.area}`,item.area));const [selected,setSelected]=useState('all');const [ranks,setRanks]=useState<AreaRank[]>(saved.ranks);const [quests,setQuests]=useState<Quest[]>(saved.quests.length?saved.quests:seedQuests);
 const persist=(nextRanks:AreaRank[],nextQuests:Quest[])=>{setRanks(nextRanks);setQuests(nextQuests);localStorage.setItem(KEY,JSON.stringify({ranks:nextRanks,quests:nextQuests}))};
 useEffect(()=>{const date=new Date();const monday=new Date(date);monday.setDate(date.getDate()-((date.getDay()+6)%7));const weekKey=monday.toISOString().slice(0,10);if(quests.some(item=>item.type==='WEEKLY'&&item.weekKey===weekKey))return;const weekly=targets.filter(x=>selected==='all'||x.id===selected).slice(0,3).flatMap(target=>questTemplates(target.name).filter(x=>x.type==='WEEKLY').slice(0,1).map(item=>({...makeQuest(item,target.id,target.name),weekKey})));const next=[...quests,...weekly];setQuests(next);localStorage.setItem(KEY,JSON.stringify({ranks,quests:next}))},[]);
 const rankFor=(id:string,name:string)=>ranks.find(x=>x.targetId===id)||{targetId:id,targetName:name,rank:1,dailyCompleted:0,weeklyCompleted:0,promotionUnlocked:false,promotionCompleted:false};
 const generate=()=>{const pool=targets.filter(x=>selected==='all'||x.id===selected);const previous=quests;const now=Date.now();const candidates=pool.flatMap(target=>questTemplates(target.name).filter(x=>x.type==='DAILY'||x.type==='CHALLENGE').map(x=>({...x,target}))).filter(item=>{const old=previous.find(x=>x.title===item.title&&x.status==='completed');return !old||now-new Date(old.completedAt||old.createdAt).getTime()>=((old.cooldownDays||2)*86400000)});const next=weightedSample(candidates,Math.min(3,candidates.length)).map(item=>makeQuest(item,item.target.id,item.target.name));const kept=previous.filter(x=>x.status==='accepted'&&x.type!=='DAILY'||x.status==='completed');const result=[...kept.slice(-50),...next];setQuests(result);localStorage.setItem(KEY,JSON.stringify({ranks,quests:result}))};
 const accept=(quest:Quest)=>{const completed=quests.filter(x=>x.status==='completed');if(!prerequisitesMet(quest,completed)){window.alert('Complete the prerequisite quests before accepting this one.');return}if(quest.type==='PROMOTION'&&!rankFor(quest.targetId,quest.targetName).promotionUnlocked){window.alert('This Promotion Quest is still locked.');return}setData((current:AppData)=>({...current,tasks:[{id:`quest-task-${quest.id}`,title:quest.title,description:quest.description,minutes:quest.minutes,difficulty:quest.difficulty<=2?'Easy':quest.difficulty===3?'Medium':'Hard',category:'Daily progress',status:'todo',notes:`Quest: ${quest.id}`,areaId:current.areas.find(x=>x.id===quest.targetId)?.id},...current.tasks]}));const next=quests.map(x=>x.id===quest.id?{...x,status:'accepted' as const}:x);persist(ranks,next)};
 const complete=(quest:Quest)=>{const requiresEvidence=quest.type==='WEEKLY'||quest.type==='CHALLENGE'||quest.type==='PROMOTION'||quest.type==='BOSS';const evidence=requiresEvidence?window.prompt('Add completion evidence (note, link, file name, or result):',quest.evidence||''):'';if(requiresEvidence&&!evidence?.trim())return;const current=rankFor(quest.targetId,quest.targetName);if(quest.type==='PROMOTION'&&!current.promotionUnlocked)return;const completedAt=new Date().toISOString();const daily=current.dailyCompleted+(quest.type==='DAILY'?1:0);const weekly=current.weeklyCompleted+(quest.type==='WEEKLY'?1:0);const promoted=quest.type==='PROMOTION'&&current.promotionUnlocked;const nextRank={...current,rank:promoted?Math.min(8,current.rank+1):current.rank,dailyCompleted:promoted?0:daily,weeklyCompleted:promoted?0:weekly,promotionUnlocked:promoted?false:daily>=3&&weekly>=1,promotionCompleted:promoted||current.promotionCompleted};appendActivity({id:`quest-activity-${quest.id}`,createdAt:completedAt,updatedAt:completedAt,type:'TaskCompleted',title:quest.title,occurredAt:completedAt,source:'Quest',metadata:{questId:quest.id,targetId:quest.targetId,targetName:quest.targetName,evidence:evidence||undefined}} as any);let nextQuests=quests.map(x=>x.id===quest.id?{...x,status:'completed' as const,evidence:evidence||undefined,completedAt}:x);if(!promoted&&nextRank.promotionUnlocked&&!nextQuests.some(x=>x.targetId===quest.targetId&&x.type==='PROMOTION'&&x.status!=='completed'))nextQuests=[...nextQuests,makeQuest({title:`Promotion Quest: demonstrate ${quest.targetName}`,description:`Complete an observable piece of work that proves your current ${rankNames[current.rank-1]} ability.`,type:'PROMOTION',minutes:45,difficulty:4},quest.targetId,quest.targetName)];persist([...ranks.filter(x=>x.targetId!==quest.targetId),nextRank],nextQuests)};
 const visible=quests.filter(x=>selected==='all'||x.targetId===selected);return <div className="content"><div className="toolbar"><div><span className="pill purple">QUEST BOARD</span><h2>Progress through meaningful quests.</h2><p className="muted">Every learning area and interest has an independent rank. Complete requirements, then earn promotion.</p></div><div className="today-actions"><button className="secondary" onClick={generate}><Icon name="RefreshCw" size={15}/> Rotate quests</button></div></div><div className="quest-targets"><button className={selected==='all'?'active':''} onClick={()=>setSelected('all')}>All boards</button>{targets.map(target=><button className={selected===target.id?'active':''} key={target.id} onClick={()=>setSelected(target.id)}>{target.name}<small>Rank {rankFor(target.id,target.name).rank}</small></button>)}</div><div className="quest-rank-grid">{targets.filter(x=>selected==='all'||x.id===selected).slice(0,8).map(target=>{const rank=rankFor(target.id,target.name);return <div className="quest-rank-card" key={target.id}><div><span className="pill teal">RANK {rank.rank}</span><h3>{target.name}</h3><p className="muted">{rankNames[rank.rank-1]}</p></div><strong>{rank.dailyCompleted} daily · {rank.weeklyCompleted} weekly</strong><div className="progress"><i style={{width:`${Math.min(100,(rank.dailyCompleted/3+rank.weeklyCompleted)*25)}%`}}/></div><small>{rank.promotionUnlocked?'Promotion quest unlocked':'Complete 3 daily + 1 weekly to unlock promotion'}</small></div>})}</div><div className="quest-list">{visible.length?visible.map(quest=><article className={'quest-card quest-'+quest.type.toLowerCase()} key={quest.id}><div className="quest-card-top"><span className="pill">{quest.type}</span><span>{'★'.repeat(quest.difficulty)} · {quest.minutes} min</span></div><h3>{quest.title}</h3><p>{quest.description}</p><small>{quest.targetName} · {quest.status}</small><div className="quest-actions">{quest.status==='available'&&<button className="primary" onClick={()=>accept(quest)}>Accept to Today</button>}{quest.status==='accepted'&&<button className="secondary" onClick={()=>complete(quest)}>Complete quest</button>}<button className="secondary" onClick={()=>persist(ranks,quests.filter(x=>x.id!==quest.id))}>Skip</button></div></article>):<div className="empty-page"><div className="empty-icon"><Icon name="Target" size={28}/></div><h2>No quests on the board</h2><p>Choose a board and rotate quests to create a small daily set.</p><button className="primary" onClick={generate}>Generate today's quests</button></div>}</div></div>;
}
