import { useMemo, useState } from 'react';
import Icon from './Icon';
import type { Capture } from '../domain/capture';
import { captureRepository } from '../repositories/legacyRepositories';

type Parsed = { people: string[]; topics: string[]; followUp: string; action: string };
const topicList = ['BCI','neuroscience','AI','machine learning','Python','R','statistics','photography','finance','psychology'];
function extract(text: string): Parsed { const people = Array.from(text.matchAll(/\b(?:with|and|和|跟|与)\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)?)/g)).map(match => match[1]); const topics = topicList.filter(topic => text.toLowerCase().includes(topic.toLowerCase())); const followUp = /next week|下周|tomorrow|明天|follow.?up|约好|计划|remind|提醒/i.test(text) ? 'Follow-up detected' : ''; const actionMatch = text.match(/(?:need to|should|will|计划|需要|要|准备|完成)\s+([^。.!！\n]{3,48})/i); return { people, topics, followUp, action: actionMatch?.[1]?.trim() || '' }; }

export default function QuickCapture({ onClose }: { onClose: () => void }) {
  const [text, setText] = useState(''); const [parsed, setParsed] = useState<Parsed>({ people: [], topics: [], followUp: '', action: '' }); const [saved, setSaved] = useState(false); const [organizing, setOrganizing] = useState(false); const [aiNote, setAiNote] = useState(''); const preview = useMemo(() => extract(text), [text]);
  const analyze = () => setParsed(preview);
  const save = () => { if (!text.trim()) return; const capture: Capture = { id: Date.now().toString(), text: text.trim(), createdAt: new Date().toISOString(), ...parsed }; captureRepository.save([capture, ...captureRepository.load()].slice(0, 100)); setSaved(true); setTimeout(onClose, 650); };
  const askAI = async () => { const endpoint = localStorage.getItem('personal-life-os-ai-endpoint') || ''; if (!endpoint) { setAiNote('Add your Supabase AI URL in Analytics first.'); return; } setOrganizing(true); setAiNote('AI is organizing this capture…'); try { const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ goals: [], areas: [], skills: [], tasks: [{ title: text, status: 'note', difficulty: 'unknown' }], journal: { notes: text } }) }); const body = await response.json(); setAiNote(response.ok ? `AI suggestion: ${String(body.text || '').slice(0, 260)}` : 'AI could not organize this right now.'); } catch { setAiNote('AI could not organize this right now. You can still save the capture.'); } finally { setOrganizing(false); } };
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="capture-modal" onSubmit={event => { event.preventDefault(); save(); }} onMouseDown={event => event.stopPropagation()}><div className="modal-head"><div><span className="pill purple">QUICK CAPTURE</span><h2>Get it out of your head.</h2><p className="muted">Write naturally, then confirm the suggested structure.</p></div><button type="button" className="modal-close" onClick={onClose}>×</button></div><textarea autoFocus value={text} onChange={event => { setText(event.target.value); setParsed(extract(event.target.value)); }} placeholder="e.g. Today I talked with Alex about BCI. We should read a paper together next week." rows={5}/>{text.trim()&&<div className="capture-preview capture-structured"><Icon name="Sparkles" size={16}/><div><b>Auto-organized preview</b><span>{parsed.people.length ? `People · ${parsed.people.join(', ')}` : 'People · none detected'}</span><span>{parsed.topics.length ? `Topics · ${parsed.topics.join(', ')}` : 'Topics · general note'}</span><span>{parsed.action ? `Action · ${parsed.action}` : 'Action · none detected'}{parsed.followUp ? ' · Follow-up detected' : ''}</span></div></div>}<div className="capture-edit-grid"><label>People<input value={parsed.people.join(', ')} onChange={e=>setParsed({...parsed,people:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label>Topics<input value={parsed.topics.join(', ')} onChange={e=>setParsed({...parsed,topics:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label>Action / next step<input value={parsed.action} onChange={e=>setParsed({...parsed,action:e.target.value})}/></label></div>{aiNote&&<p className="capture-ai-note"><Icon name="Sparkles" size={14}/>{aiNote}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="button" className="secondary" onClick={analyze} disabled={!text.trim()}>Re-analyze</button><button type="button" className="secondary" onClick={askAI} disabled={!text.trim()||organizing}>{organizing?'Organizing…':'Ask AI'}</button><button className="primary" disabled={!text.trim()}>{saved ? 'Saved' : 'Save capture'}</button></div></form></div>;
}
