import { useMemo, useState } from 'react';
import Icon from './Icon';
import ActionMenu from './ActionMenu';
import type { LearningArea, Project, ResourceItem, ResourceStatus, ResourceType, Skill } from '../domain/types';
import { resourceRepository } from '../repositories/legacyRepositories';
import { useAppStore } from '../store/useAppStore';

const types: ResourceType[] = ['Paper','Book','Video','Course','Website','Dataset','Tool','Podcast','Note'];
const statuses: ResourceStatus[] = ['Inbox','To Read','Reading','Finished','Reference'];
type View='inbox'|'active'|'library'|'all';
const icons:Record<ResourceType,keyof typeof import('lucide-react')>={Paper:'FileText',Book:'BookOpen',Video:'PlayCircle',Course:'GraduationCap',Website:'Globe2',Dataset:'Database',Tool:'Wrench',Podcast:'Headphones',Note:'StickyNote'};
function readResources(): ResourceItem[] { return resourceRepository.load(); }

export default function ResourceLibrary({ areas, skills, projects }: { areas: LearningArea[]; skills: Skill[]; projects: Project[] }) {
  const {data,setData}=useAppStore(); const [items,setItems]=useState<ResourceItem[]>(readResources); const [query,setQuery]=useState(''); const [type,setType]=useState<'All'|ResourceType>('All'); const [view,setView]=useState<View>('inbox'); const [form,setForm]=useState<ResourceItem|null>(null); const [message,setMessage]=useState('');
  const save=(next:ResourceItem[])=>{setItems(next);resourceRepository.save(next)}; const updateStatus=(item:ResourceItem,next:ResourceStatus)=>save(items.map(x=>x.id===item.id?{...x,status:next}:x));
  const matchesView=(item:ResourceItem)=>view==='all'||(view==='inbox'&&item.status==='Inbox')||(view==='active'&&['To Read','Reading'].includes(item.status))||(view==='library'&&['Finished','Reference'].includes(item.status));
  const visible=useMemo(()=>items.filter(item=>matchesView(item)&&(type==='All'||item.type===type)&&(item.title+' '+item.notes+' '+item.tags.join(' ')).toLowerCase().includes(query.toLowerCase())),[items,query,type,view]);
  const linkedCount=items.filter(item=>item.areaId||item.skillId||item.projectId).length; const activeCount=items.filter(item=>['To Read','Reading'].includes(item.status)).length; const reusableCount=items.filter(item=>['Finished','Reference'].includes(item.status)).length;
  const create=():ResourceItem=>({id:'resource-'+Date.now(),title:'',type:'Paper',status:'Inbox',url:'',notes:'',tags:[],createdAt:new Date().toISOString()});
  const addToToday=(item:ResourceItem)=>{const marker=`Resource: ${item.id}`;if(data.tasks.some(task=>task.notes?.includes(marker)&&task.status!=='done'))return setMessage('This resource is already in Today.');setData(current=>({...current,tasks:[{id:`resource-task-${Date.now()}`,title:`Use: ${item.title}`,description:item.notes||`Spend focused time with this ${item.type.toLowerCase()}.`,minutes:item.type==='Course'||item.type==='Book'?30:20,difficulty:'Easy',category:'Manual',timeCategory:'Study',areaId:item.areaId,skillId:item.skillId,projectId:item.projectId,priority:'Medium',status:'todo',notes:`${marker} · ${item.url}`},...current.tasks]}));if(item.status==='Inbox')updateStatus(item,'To Read');setMessage(`Added “${item.title}” to Today.`)};
  const related=(item:ResourceItem)=>[item.areaId&&areas.find(x=>x.id===item.areaId)?.name,item.skillId&&skills.find(x=>x.id===item.skillId)?.name,item.projectId&&projects.find(x=>x.id===item.projectId)?.name].filter(Boolean) as string[];
  const nextLabel=(item:ResourceItem)=>item.status==='Inbox'?'Plan to use':item.status==='To Read'?'Start using':item.status==='Reading'?'Continue':item.status==='Finished'?'Use again':'Open reference';
  return <div className="content resource-workspace"><section className="resource-workspace-hero"><div><span className="pill purple">RESOURCE WORKSPACE</span><h2>Keep useful material close to the work.</h2><p>Resources are reusable inputs—papers, courses, datasets and tools. Link each one to a skill, area or project, then give it a clear next use.</p></div><button className="primary" onClick={()=>setForm(create())}><Icon name="Plus" size={16}/> Add resource</button></section>
    <div className="resource-summary-grid"><div><span>Total resources</span><b>{items.length}</b><small>materials and tools</small></div><div><span>In use</span><b>{activeCount}</b><small>to read or currently using</small></div><div><span>Reusable library</span><b>{reusableCount}</b><small>finished or reference</small></div><div><span>Connected</span><b>{linkedCount}</b><small>linked to your system</small></div></div>
    <div className="resource-purpose"><Icon name="Network" size={18}/><p><b>The rule:</b> if a resource has no connection or next action, it stays in Inbox. Knowledge holds what you learned; Resources holds what you can use again.</p></div>
    <nav className="resource-tabs">{([['inbox','Inbox',items.filter(x=>x.status==='Inbox').length],['active','In use',activeCount],['library','Library',reusableCount],['all','All',items.length]] as [View,string,number][]).map(([key,label,count])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}><Icon name={key==='inbox'?'Inbox':key==='active'?'PlayCircle':key==='library'?'Library':'LayoutGrid'} size={15}/>{label}<span>{count}</span></button>)}</nav>
    <section className="resource-control-panel"><div className="skills-search"><Icon name="Search" size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search resources, notes or tags…"/></div><select value={type} onChange={event=>setType(event.target.value as 'All'|ResourceType)}><option value="All">All resource types</option>{types.map(item=><option key={item}>{item}</option>)}</select>{(query||type!=='All')&&<button className="text-button" onClick={()=>{setQuery('');setType('All')}}>Clear filters</button>}</section>
    {message&&<div className="skills-message"><Icon name="CheckCircle2" size={16}/>{message}<button onClick={()=>setMessage('')}>×</button></div>}
    <div className="resource-results-head"><div><h3>{view==='inbox'?'Decide what happens next':view==='active'?'Currently in use':view==='library'?'Ready to reuse':'Every resource'}</h3><span>{visible.length} result{visible.length===1?'':'s'}</span></div><p>{view==='inbox'?'Connect, plan or archive each new item.':view==='active'?'Keep this list short and intentional.':view==='library'?'Finished does not mean forgotten—reuse what works.':'Search across the complete resource system.'}</p></div>
    {visible.length?<div className="resource-work-grid">{visible.map(item=><article className="resource-work-card" key={item.id}><div className="resource-card-top"><span className="resource-type-mark"><Icon name={icons[item.type]} size={16}/>{item.type}</span><ActionMenu items={[{label:'Edit resource',onClick:()=>setForm(item)},{label:'Add to Today',onClick:()=>addToToday(item)},{label:'Move to reference',onClick:()=>updateStatus(item,'Reference')},{label:'Delete resource',danger:true,onClick:()=>{if(window.confirm('Delete this resource?'))save(items.filter(x=>x.id!==item.id))}}]}/></div><h3>{item.title}</h3><p className="resource-work-notes">{item.notes||'Add a note explaining when or why this is useful.'}</p><div className="resource-connection-row">{related(item).length?related(item).map(value=><span key={value}><Icon name="Link2" size={11}/>{value}</span>):<button onClick={()=>setForm(item)}><Icon name="Unlink" size={12}/> Add a connection</button>}</div>{item.tags.length>0&&<div className="resource-tag-row">{item.tags.slice(0,4).map(tag=><span key={tag}>#{tag}</span>)}</div>}<div className="resource-card-footer"><span className={'resource-status status-'+item.status.toLowerCase().replace(' ','-')}>{item.status}</span><select value={item.status} onChange={event=>updateStatus(item,event.target.value as ResourceStatus)} aria-label={`Status for ${item.title}`}>{statuses.map(value=><option key={value}>{value}</option>)}</select></div><div className="resource-primary-actions">{item.url?<a className="secondary" href={item.url} target="_blank" rel="noreferrer"><Icon name="ArrowUpRight" size={14}/> Open</a>:<button className="secondary" onClick={()=>setForm(item)}><Icon name="Link" size={14}/> Add link</button>}<button className="primary" onClick={()=>addToToday(item)}><Icon name="Sun" size={14}/>{nextLabel(item)}</button></div></article>)}</div>:<div className="resource-work-empty"><Icon name="Library" size={30}/><h3>{items.length?'No resources match this view':'Your reusable library starts here'}</h3><p>{items.length?'Try another type or search term.':'Add a paper, course, dataset or tool—and connect it to where you will use it.'}</p><button className="primary" onClick={()=>setForm(create())}>Add resource</button></div>}
    {form&&<ResourceForm item={form} areas={areas} skills={skills} projects={projects} onCancel={()=>setForm(null)} onSave={item=>{save(items.some(x=>x.id===item.id)?items.map(x=>x.id===item.id?item:x):[item,...items]);setForm(null);setMessage(`${item.title} was saved.`)}}/>}</div>;
}

function ResourceForm({item,areas,skills,projects,onCancel,onSave}:{item:ResourceItem;areas:LearningArea[];skills:Skill[];projects:Project[];onCancel:()=>void;onSave:(item:ResourceItem)=>void}){
  const[draft,setDraft]=useState(item);const set=(field:keyof ResourceItem,value:any)=>setDraft(current=>({...current,[field]:value}));
  return <div className="modal-backdrop" onMouseDown={onCancel}><form className="create-modal resource-form" onSubmit={event=>{event.preventDefault();if(draft.title.trim())onSave({...draft,title:draft.title.trim(),tags:draft.tags.map(value=>value.trim()).filter(Boolean)})}} onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><span className="pill purple">RESOURCE</span><h2>{item.title?'Edit resource':'Save something reusable'}</h2></div><button type="button" className="modal-close" onClick={onCancel}>×</button></div><label>Title<input autoFocus value={draft.title} onChange={event=>set('title',event.target.value)} placeholder="Paper, course, dataset or tool"/></label><div className="form-two"><label>Type<select value={draft.type} onChange={event=>set('type',event.target.value)}>{types.map(value=><option key={value}>{value}</option>)}</select></label><label>Workflow status<select value={draft.status} onChange={event=>set('status',event.target.value)}>{statuses.map(value=><option key={value}>{value}</option>)}</select></label></div><label>Original link<input value={draft.url} onChange={event=>set('url',event.target.value)} placeholder="https://…"/></label><label>How will you use it?<textarea value={draft.notes} onChange={event=>set('notes',event.target.value)} placeholder="What is useful here, and what is the next use?"/></label><label>Tags<input value={draft.tags.join(', ')} onChange={event=>set('tags',event.target.value.split(','))} placeholder="methods, BCI, priority"/></label><div className="resource-linking-title"><b>Connect it to your system</b><small>At least one connection makes this resource easier to find and use.</small></div><div className="form-two"><label>Learning area<select value={draft.areaId||''} onChange={event=>set('areaId',event.target.value||undefined)}><option value="">Not linked</option>{areas.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label>Skill<select value={draft.skillId||''} onChange={event=>set('skillId',event.target.value||undefined)}><option value="">Not linked</option>{skills.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label></div><label>Project<select value={draft.projectId||''} onChange={event=>set('projectId',event.target.value||undefined)}><option value="">Not linked</option>{projects.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label><div className="modal-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={!draft.title.trim()}>Save resource</button></div></form></div>;
}
