import { useMemo, useState } from 'react';
import Icon from './Icon';
import ActionMenu from './ActionMenu';
import type { LearningArea, Project, ResourceItem, ResourceStatus, ResourceType, Skill } from '../domain/types';
import { resourceRepository } from '../repositories/legacyRepositories';

const types: ResourceType[] = ['Paper','Book','Video','Course','Website','Dataset','Tool','Podcast','Note'];
const statuses: ResourceStatus[] = ['Inbox','To Read','Reading','Finished','Reference'];
function readResources(): ResourceItem[] { return resourceRepository.load(); }

export default function ResourceLibrary({ areas, skills, projects }: { areas: LearningArea[]; skills: Skill[]; projects: Project[] }) {
  const [items, setItems] = useState<ResourceItem[]>(readResources);
  const [query, setQuery] = useState('');
  const [type, setType] = useState<'All'|ResourceType>('All');
  const [status, setStatus] = useState<'All'|ResourceStatus>('All');
  const [form, setForm] = useState<ResourceItem | null>(null);
  const save = (next: ResourceItem[]) => { setItems(next); resourceRepository.save(next); };
  const visible = useMemo(() => items.filter(item => (type === 'All' || item.type === type) && (status === 'All' || item.status === status) && (item.title+' '+item.notes+' '+item.tags.join(' ')).toLowerCase().includes(query.toLowerCase())), [items, query, type, status]);
  const updateStatus = (item: ResourceItem, next: ResourceStatus) => save(items.map(x => x.id === item.id ? { ...x, status: next } : x));
  return <div className="content resource-page">
    <div className="knowledge-header"><div><span className="pill purple">RESOURCE LIBRARY</span><h2>Keep the things worth returning to.</h2><p className="muted">One calm shelf for research, courses, tools and ideas.</p></div><button className="primary" onClick={() => setForm({id:'resource-'+Date.now(),title:'',type:'Paper',status:'Inbox',url:'',notes:'',tags:[],createdAt:new Date().toISOString()})}><Icon name="Plus" size={16}/> Add resource</button></div>
    <div className="resource-toolbar"><div className="search-field"><Icon name="Search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, notes or tags…"/></div><select value={type} onChange={e=>setType(e.target.value as any)}><option value="All">All types</option>{types.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value as any)}><option value="All">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="resource-summary"><span>{visible.length} resources</span><span>{items.filter(x=>x.status==='Finished').length} finished · {items.filter(x=>x.status==='Reading').length} reading</span></div>
    {visible.length ? <div className="resource-grid">{visible.map(item => <article className="resource-card" key={item.id}><div className="resource-card-top"><span className="resource-type"><Icon name={item.type==='Paper'?'FileText':item.type==='Book'?'BookOpen':item.type==='Video'?'PlayCircle':item.type==='Tool'?'Wrench':'Library'} size={14}/>{item.type}</span><ActionMenu items={[{label:'Edit resource',onClick:()=>setForm(item)},{label:'Mark reading',onClick:()=>updateStatus(item,'Reading')},{label:'Mark finished',onClick:()=>updateStatus(item,'Finished')},{label:'Delete resource',danger:true,onClick:()=>{if(window.confirm('Delete this resource?'))save(items.filter(x=>x.id!==item.id))}}]}/></div><h3>{item.title}</h3><span className={'resource-status status-'+item.status.toLowerCase().replace(' ','-')}>{item.status}</span>{item.notes&&<p>{item.notes}</p>}{item.tags.length>0&&<div className="chips">{item.tags.map(tag=><span key={tag}>#{tag}</span>)}</div>}<div className="resource-related">{item.areaId&&<span>{areas.find(x=>x.id===item.areaId)?.name}</span>}{item.skillId&&<span>{skills.find(x=>x.id===item.skillId)?.name}</span>}{item.projectId&&<span>{projects.find(x=>x.id===item.projectId)?.name}</span>}</div><div className="resource-footer">{item.url?<a href={item.url} target="_blank" rel="noreferrer">Open resource <Icon name="ArrowUpRight" size={13}/></a>:<span className="muted">No link added</span>}<select value={item.status} onChange={e=>updateStatus(item,e.target.value as ResourceStatus)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div></article>)}</div> : <div className="empty-page resource-empty"><div className="empty-icon"><Icon name="Library" size={30}/></div><h2>Your resource shelf is empty</h2><p>Add a paper, course, book or tool so useful ideas stay connected to your growth system.</p><button className="primary" onClick={() => setForm({id:'resource-'+Date.now(),title:'',type:'Paper',status:'Inbox',url:'',notes:'',tags:[],createdAt:new Date().toISOString()})}>Add first resource</button></div>}
    {form&&<ResourceForm item={form} areas={areas} skills={skills} projects={projects} onCancel={()=>setForm(null)} onSave={item=>{save(items.some(x=>x.id===item.id)?items.map(x=>x.id===item.id?item:x):[item,...items]);setForm(null)}}/>}
  </div>;
}

function ResourceForm({ item, areas, skills, projects, onCancel, onSave }: { item: ResourceItem; areas: LearningArea[]; skills: Skill[]; projects: Project[]; onCancel:()=>void; onSave:(item:ResourceItem)=>void }) {
  const [draft,setDraft]=useState(item); const set=(field:keyof ResourceItem,value:any)=>setDraft(x=>({...x,[field]:value}));
  return <div className="modal-backdrop" onMouseDown={onCancel}><form className="create-modal resource-form" onSubmit={e=>{e.preventDefault();if(draft.title.trim())onSave({...draft,title:draft.title.trim(),tags:draft.tags.map(x=>x.trim()).filter(Boolean)})}} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="pill purple">RESOURCE</span><h2>{item.title?'Edit resource':'Save something useful'}</h2></div><button type="button" className="modal-close" onClick={onCancel}>×</button></div><label>Title<input autoFocus value={draft.title} onChange={e=>set('title',e.target.value)} placeholder="e.g. A paper, course or tool"/></label><div className="form-two"><label>Type<select value={draft.type} onChange={e=>set('type',e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={draft.status} onChange={e=>set('status',e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Original link<input value={draft.url} onChange={e=>set('url',e.target.value)} placeholder="https://…"/></label><label>Notes<textarea value={draft.notes} onChange={e=>set('notes',e.target.value)} placeholder="Why is this useful? What should you remember?"/></label><label>Tags<input value={draft.tags.join(', ')} onChange={e=>set('tags',e.target.value.split(','))} placeholder="BCI, methods, priority"/></label><div className="form-two"><label>Learning area<select value={draft.areaId||''} onChange={e=>set('areaId',e.target.value||undefined)}><option value="">Not linked</option>{areas.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Skill<select value={draft.skillId||''} onChange={e=>set('skillId',e.target.value||undefined)}><option value="">Not linked</option>{skills.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label>Project<select value={draft.projectId||''} onChange={e=>set('projectId',e.target.value||undefined)}><option value="">Not linked</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="modal-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={!draft.title.trim()}>Save resource</button></div></form></div>;
}
