import { useState } from 'react';
import Icon from './Icon';
import { loadBooks, saveBooks } from '../repositories/bookRepository';
import { appendActivity, appendRecallAttempt } from '../repositories/appRepository';
import { getReviewQueue } from '../services/reviewQueueService';
import { scheduleRecall } from '../services/recallService';
const tomorrow=()=>{const date=new Date();date.setDate(date.getDate()+1);return date.toISOString().slice(0,10)};
export default function ReviewQueue(){const[books,setBooks]=useState(loadBooks);const[revealed,setRevealed]=useState<Record<string,boolean>>({});const items=getReviewQueue(books,5);const defer=(bookId:string,recallId:string,kind:'snooze'|'skip')=>{const until=tomorrow();const next=books.map(book=>book.id!==bookId?book:{...book,recalls:book.recalls.map(recall=>recall.id!==recallId?recall:{...recall,...(kind==='snooze'?{snoozedUntil:until,nextReview:until}:{skippedUntil:until})})});setBooks(next);saveBooks(next);setRevealed(current=>({...current,[recallId]:false}));};const review=(bookId:string,recallId:string,correct:boolean)=>{const at=new Date().toISOString();const next=books.map(book=>book.id!==bookId?book:{...book,recalls:book.recalls.map(recall=>recall.id!==recallId?recall:{...recall,confidence:correct?Math.min(100,recall.confidence+20):Math.max(0,recall.confidence-10),nextReview:scheduleRecall(Math.ceil(recall.confidence/20),correct)})});setBooks(next);saveBooks(next);const book=next.find(item=>item.id===bookId);const recall=book?.recalls.find(item=>item.id===recallId);if(!book||!recall)return;appendRecallAttempt({id:`recall-attempt-${Date.now()}`,createdAt:at,updatedAt:at,questionId:recallId,bookId,attemptedAt:at,result:correct?'correct':'incorrect',confidence:correct?100:0,nextReview:recall.nextReview});appendActivity({id:`activity-${Date.now()}`,createdAt:at,updatedAt:at,type:'RecallCompleted',title:recall.question,occurredAt:at,source:'Book',metadata:{bookId,questionId:recallId,result:correct?'correct':'incorrect'}})};if(!items.length)return null;return <section className="review-queue"><SectionTitle title="Review due"/><p className="muted">A small queue of high-value concepts due for spaced recall.</p>{items.map(item=><article className="review-item" key={item.recall.id}><div><span className="pill teal">Tier {item.concept.tier} · {item.book.title}</span><h3>{item.recall.question}</h3>{revealed[item.recall.id]&&<p>{item.recall.answer}</p>}</div><div className="review-actions">{!revealed[item.recall.id]?<><button className="secondary" onClick={()=>setRevealed({...revealed,[item.recall.id]:true})}><Icon name="Eye" size={14}/> Reveal</button><button className="secondary" onClick={()=>defer(item.book.id,item.recall.id,'snooze')}>Snooze 1 day</button><button className="secondary" onClick={()=>defer(item.book.id,item.recall.id,'skip')}>Skip today</button></>:<><button className="secondary" onClick={()=>review(item.book.id,item.recall.id,true)}>Got it</button><button className="secondary" onClick={()=>review(item.book.id,item.recall.id,false)}>Review again</button></>}</div></article>)}</section>}
function SectionTitle({title}:{title:string}){return <div className="section-title"><h2>{title}</h2></div>}
