import { useState } from 'react';
import Icon from './Icon';
import type { Level, Skill } from '../domain/types';

export default function SkillEditor({ skill, onCancel, onSave }: { skill: Skill; onCancel: () => void; onSave: (skill: Skill) => void }) {
  const [draft, setDraft] = useState({ ...skill, resourcesText: (skill.resources || []).join('\n'), milestonesText: (skill.milestones || []).join('\n') });
  const update = (key: string, value: string) => setDraft(current => ({ ...current, [key]: value }));
  const save = () => onSave({ ...skill, name: draft.name.trim() || skill.name, level: draft.level as Level, target: draft.target as Level, focus: draft.focus, resources: draft.resourcesText.split('\n').map(item => item.trim()).filter(Boolean), milestones: draft.milestonesText.split('\n').map(item => item.trim()).filter(Boolean) });
  return <div className="modal-backdrop" onMouseDown={onCancel}><form className="create-modal area-editor" onSubmit={event => { event.preventDefault(); save(); }} onMouseDown={event => event.stopPropagation()}><div className="modal-head"><div><span className="pill purple">SKILL TRACKER</span><h2>Edit skill growth</h2></div><button type="button" className="modal-close" onClick={onCancel}>×</button></div><label>Name<input autoFocus value={draft.name} onChange={event => update('name', event.target.value)}/></label><div className="form-two"><label>Current level<select value={draft.level} onChange={event => update('level', event.target.value)}>{['Beginner','Basic','Intermediate','Advanced','Expert'].map(level=><option key={level}>{level}</option>)}</select></label><label>Target level<select value={draft.target} onChange={event => update('target', event.target.value)}>{['Beginner','Basic','Intermediate','Advanced','Expert'].map(level=><option key={level}>{level}</option>)}</select></label></div><label>Current focus<input value={draft.focus} onChange={event => update('focus', event.target.value)} placeholder="What are you practicing next?"/></label><label>Resources <small>one link or note per line</small><textarea rows={3} value={draft.resourcesText} onChange={event => update('resourcesText', event.target.value)} placeholder="Course, book, dataset…"/></label><label>Milestones <small>one milestone per line</small><textarea rows={3} value={draft.milestonesText} onChange={event => update('milestonesText', event.target.value)} placeholder="Complete 10 exercises…"/><div className="skill-log-preview"><b>Progress log</b>{skill.progressLog?.length ? skill.progressLog.slice(0,5).map((entry,index)=><span key={index}>{entry.date} · {entry.minutes} min{entry.note ? ` · ${entry.note}` : ''}</span>) : <span>No practice log yet.</span>}</div></label><div className="modal-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary"><Icon name="Save" size={15}/> Save skill</button></div></form></div>;
}
