import { useState } from 'react';
import Icon from './Icon';
import type { Priority, Task } from '../domain/types';

export default function TaskEditor({ task, projects, onCancel, onSave }: { task: Task; projects: any[]; onCancel: () => void; onSave: (task: Task) => void }) {
  const [draft, setDraft] = useState({ ...task });
  const update = (key: string, value: string|number) => setDraft(current => ({ ...current, [key]: value }));
  return <div className="modal-backdrop" onMouseDown={onCancel}><form className="create-modal" onSubmit={event => { event.preventDefault(); onSave({ ...draft, title: draft.title.trim() || task.title }); }} onMouseDown={event => event.stopPropagation()}><div className="modal-head"><div><span className="pill purple">TASK DETAILS</span><h2>Edit task</h2></div><button type="button" className="modal-close" onClick={onCancel}>×</button></div><label>Title<input autoFocus value={draft.title} onChange={event => update('title', event.target.value)}/></label><label>Description<textarea rows={2} value={draft.description} onChange={event => update('description', event.target.value)}/></label><div className="form-two"><label>Priority<select value={draft.priority || 'Medium'} onChange={event => update('priority', event.target.value as Priority)}><option>Low</option><option>Medium</option><option>High</option></select></label><label>Difficulty<select value={draft.difficulty} onChange={event => update('difficulty', event.target.value)}><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><label>Estimated minutes<input type="number" min="1" value={draft.minutes} onChange={event => update('minutes', Number(event.target.value))}/></label><label>Project<select value={draft.projectId || ''} onChange={event => update('projectId', event.target.value)}><option value="">No project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Notes<textarea rows={3} value={draft.notes || ''} onChange={event => update('notes', event.target.value)} placeholder="What should you remember when doing this?"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary"><Icon name="Save" size={15}/> Save task</button></div></form></div>;
}
