import {useEffect,useMemo,useState} from 'react';
import Icon from './Icon';
import type {Project,Task,TimeEntry} from '../domain/types';
import {TIME_CATEGORIES,createManualTimeEntry,createTaskTimeEntry,deleteTimeEntry,getCategoryTotals,getTimeEntries,getWeeklyTotals,saveTrackedTimeEntry} from '../services/timeTrackingService';
import {localDateKey} from '../domain/date';
import {getGamingAllowance,getRewardState} from '../services/rewardService';
type Subtype='Gaming'|'Novel'|'Video'|'Movie'|'Social Media'|'Other';
type Active={title:string;category:string;entertainmentSubtype?:Subtype;task?:Task;startedAt:string;elapsed:number;running:boolean};
const KEY='personal-life-os-active-timer';
const read=():Active|null=>{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):null}catch{return null}};
const fmt=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

export default function TimeTrackingPage({tasks,projects}:{tasks:Task[];projects:Project[]}){
 const[active,setActive]=useState<Active|null>(read);const[title,setTitle]=useState('');const[notes,setNotes]=useState('');const[category,setCategory]=useState('Study');const[subtype,setSubtype]=useState<Subtype>('Gaming');const[projectId,setProjectId]=useState('');const[message,setMessage]=useState('');const[tick,setTick]=useState(0);const today=localDateKey();
 const allowance=getGamingAllowance(today);const allowOverage=getRewardState().config.allowOverage;const remaining=Math.max(0,allowance.baseMinutes+allowance.activatedVoucherMinutes+allowance.bonusMinutes-allowance.usedMinutes);const totals=useMemo(()=>getCategoryTotals(today),[today,tick]);const week=useMemo(()=>getWeeklyTotals(),[tick]);
 useEffect(()=>{if(!active?.running)return;const id=window.setInterval(()=>setTick(v=>v+1),1000);return()=>window.clearInterval(id)},[active?.running]);
 useEffect(()=>{if(active)localStorage.setItem(KEY,JSON.stringify(active));else localStorage.removeItem(KEY)},[active]);
 const elapsed=active?(active.running?active.elapsed+Math.floor((Date.now()-new Date(active.startedAt).getTime())/1000):active.elapsed):0;
const start=(task?:Task)=>{const gaming=!task&&category==='Entertainment'&&subtype==='Gaming';if(gaming&&!allowOverage&&remaining<=0){setMessage('Gaming allowance is used for today. Enable overage in Settings or activate a voucher.');return}setActive({title:task?.title||title.trim(),category:task?'Study':category,entertainmentSubtype:task?undefined:category==='Entertainment'?subtype:undefined,task,startedAt:new Date().toISOString(),elapsed:0,running:true})};
const stop=()=>{if(!active)return;const end=new Date().toISOString();const minutes=Math.max(1,Math.round(elapsed/60));saveTrackedTimeEntry(active.task?createTaskTimeEntry(active.task,new Date(new Date(end).getTime()-elapsed*1000).toISOString(),end,minutes,`${active.title} session`):createManualTimeEntry(active.title,active.category,new Date(new Date(end).getTime()-elapsed*1000).toISOString(),end,minutes,notes,active.entertainmentSubtype,projectId||undefined));setActive(null);setMessage(`Saved ${minutes} minutes to ${active.category}.`);setNotes('');setTick(v=>v+1)};
 const remove=(entry:TimeEntry)=>{if(!window.confirm(`Delete “${entry.title}” from time history?`))return;if(deleteTimeEntry(entry.id)){setMessage('Time entry deleted and linked totals were restored.');setTick(v=>v+1)}};
 const total=Object.values(totals).reduce((a,b)=>a+b,0);const max=Math.max(1,...Object.values(totals));const recentEntries=week.flatMap(day=>getTimeEntries(day.date).map(entry=>({...entry,date:day.date})));
 return <div className="content time-page"><div className="time-header"><div><span className="pill teal">TIME TRACKING</span><small className="time-allowance">Gaming remaining: {remaining} min</small><h2>Make time visible.</h2><p className="muted">Task sessions are linked automatically. Start anything else manually.</p></div></div>
{active?<section className="time-active"><div><small>NOW TRACKING · {active.category}</small><h3>{active.title}</h3><b>{fmt(elapsed)}</b></div><div className="time-actions">{active.running?<button className="secondary" onClick={()=>setActive({...active,elapsed,running:false,startedAt:new Date().toISOString()})}><Icon name="Pause" size={15}/> Pause</button>:<button className="primary" onClick={()=>setActive({...active,running:true,startedAt:new Date().toISOString()})}><Icon name="Play" size={15}/> Resume</button>}<button className="primary" onClick={stop}><Icon name="Square" size={15}/> Stop & save</button></div></section>:<section className="time-manual"><div><h3>Start a manual session</h3><p className="muted">Use this when you are not starting from a task.</p></div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What are you doing?"/><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What did you do? (optional)" rows={2}/><select value={category} onChange={e=>setCategory(e.target.value)}>{TIME_CATEGORIES.map(item=><option key={item}>{item}</option>)}</select>{category==='Entertainment'&&<select value={subtype} onChange={e=>setSubtype(e.target.value as Subtype)}>{['Gaming','Novel','Video','Movie','Social Media','Other'].map(item=><option key={item}>{item}</option>)}</select>}{projects.length>0&&<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>}<button className="primary" disabled={!title.trim()} onClick={()=>start()}><Icon name="Play" size={15}/> Start timer</button></section>}
 {message&&<p className="time-message">{message}</p>}<section className="time-panel"><div className="time-panel-head"><div><span className="pill purple">TODAY</span><h3>Where did your time go?</h3></div><b>{total} min</b></div><div className="time-breakdown">{Object.entries(totals).map(([name,value])=><div key={name}><div className="time-breakdown-label"><span>{name}</span><b>{value}m</b></div><i><em style={{width:`${value/max*100}%`}}/></i></div>)}{!total&&<p className="muted">No saved time today yet.</p>}</div></section>
 <section className="time-panel"><div className="time-panel-head"><div><span className="pill teal">LAST 7 DAYS</span><h3>Weekly time</h3></div></div><div className="time-bars">{week.map(item=><div key={item.date}><b style={{height:`${Math.min(100,item.minutes/Math.max(1,...week.map(x=>x.minutes))*100)}%`}}/><small>{item.date.slice(5)}</small><em>{item.minutes}m</em></div>)}</div></section>
 <section className="time-panel"><div className="time-panel-head"><h3>Today’s entries</h3></div><div className="time-entry-list">{getTimeEntries(today).map(entry=><div key={entry.id}><Icon name={entry.source==='task'?'CheckCircle2':'Clock3'} size={15}/><span><b>{entry.title}</b><small>{entry.category} · {entry.durationMinutes} min · {entry.source==='task'?'from task':'manual'}</small></span><button className="time-entry-delete" onClick={()=>remove(entry)} aria-label={`Delete ${entry.title}`}>Delete</button></div>)}{!getTimeEntries(today).length&&<p className="muted">Saved sessions will appear here.</p>}</div></section>
<section className="time-panel"><div className="time-panel-head"><div><span className="pill purple">HISTORY</span><h3>Recent entries</h3></div><b>{recentEntries.length}</b></div><div className="time-entry-list">{recentEntries.map(entry=><div key={entry.id}><Icon name={entry.source==='task'?'CheckCircle2':'Clock3'} size={15}/><span><b>{entry.title}</b><small>{entry.date} · {entry.category} · {entry.durationMinutes} min</small>{entry.notes&&<em className="time-entry-notes">{entry.notes}</em>}</span><button className="time-entry-delete" onClick={()=>remove(entry)} aria-label={`Delete ${entry.title}`}>Delete</button></div>)}{!recentEntries.length&&<p className="muted">Recent saved sessions will appear here.</p>}</div></section><section className="time-panel"><div className="time-panel-head"><h3>Start from a task</h3></div><div className="time-task-list">{tasks.filter(task=>task.status!=='done').slice(0,8).map(task=><button key={task.id} onClick={()=>start(task)}><span>{task.title}</span><small>{task.minutes} min · {task.category}</small><Icon name="Play" size={14}/></button>)}</div></section></div>;
}
