import { useState } from 'react';
import CourseTaskTemplates from './CourseTaskTemplates';
import UpcomingCourseTasks from './UpcomingCourseTasks';
import { useAppStore } from '../store/useAppStore';
import { localDateKey } from '../domain/date';
import { addLocalDays } from '../domain/date';

type CourseFile = { id: string; name: string; size: number; type: string; dataUrl: string; reviewedAt?: string };
type StoredFiles = Record<string, CourseFile[]>;

const readFiles = (): StoredFiles => {
  try {
    const parsed = JSON.parse(localStorage.getItem('personal-life-os-course-files-v1') || '{}') as Record<string, CourseFile[] | CourseFile>;
    return Object.fromEntries(Object.entries(parsed).map(([course, value]) => [course, Array.isArray(value) ? value : [{ ...value, id: `course-file-${Date.now()}-${course}` }]]));
  } catch { return {}; }
};

export default function UniCoursePage() {
  const { data, setData, toggleTask } = useAppStore();
  const taskCourses = Array.from(new Set(data.tasks.filter(task => task.notes?.startsWith('Course:')).map(task => task.notes?.split(' · ')[1] || 'Course')));
  const [courseNames, setCourseNames] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('personal-life-os-course-names-v1') || '[]'); } catch { return []; } });
  const [newCourse, setNewCourse] = useState('');
  const courses = Array.from(new Set([...courseNames, ...taskCourses]));
  const [files, setFiles] = useState<StoredFiles>(readFiles);
  const [materialFilter, setMaterialFilter] = useState<'all' | 'todo' | 'reviewed'>('all');
  const saveFiles = (next: StoredFiles) => { setFiles(next); localStorage.setItem('personal-life-os-course-files-v1', JSON.stringify(next)); };
  const upload = (course: string, file: File) => { const reader = new FileReader(); reader.onload = () => { const next = { ...files, [course]: [...(files[course] || []), { id: `course-file-${Date.now()}`, name: file.name, size: file.size, type: file.type, dataUrl: String(reader.result) }] }; saveFiles(next); }; reader.readAsDataURL(file); };
  const formatSize = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
  const remove = (course: string, fileId: string, name: string) => { if (!window.confirm(`Delete ${name}?`)) return; const next = { ...files, [course]: (files[course] || []).filter(file => file.id !== fileId) }; if (!next[course].length) delete next[course]; saveFiles(next); };
  const createStudyTask = (course: string, file: CourseFile) => { setData(current => ({ ...current, tasks: [{ id: `course-material-task-${Date.now()}`, title: `Study · ${course}: ${file.name}`, description: `Review the uploaded course material: ${file.name}`, minutes: 30, difficulty: 'Medium', priority: 'High', category: 'Manual', scheduledDate: localDateKey(), status: 'todo', notes: `Course: ${course} · Study · Material: ${file.name}` }, ...current.tasks] })); };
  const createReviewPlan = (course: string, file: CourseFile) => { const offsets = [1, 2, 4, 7, 14, 28]; setData(current => { const existing = new Set(current.tasks.filter(task => task.notes?.includes(`Material: ${file.name}`)).map(task => `${task.scheduledDate}|${task.notes}`)); const additions = offsets.filter(offset => !existing.has(`${localDateKey(addLocalDays(new Date(), offset))}|Course: ${course} · Review · Material: ${file.name}`)).map(offset => ({ id: `course-material-review-${Date.now()}-${offset}`, title: `Review · ${course}: ${file.name}`, description: `Spaced review after ${offset} days · ${file.name}`, minutes: 15, difficulty: 'Easy' as const, priority: 'Medium' as const, category: 'Manual' as const, scheduledDate: localDateKey(addLocalDays(new Date(), offset)), status: 'todo' as const, notes: `Course: ${course} · Review · Material: ${file.name}` })); return additions.length ? { ...current, tasks: [...additions, ...current.tasks] } : current; }); };
  const toggleReviewed = (course: string, file: CourseFile) => { const next = { ...files, [course]: (files[course] || []).map(item => item.id === file.id ? { ...item, reviewedAt: item.reviewedAt ? undefined : new Date().toISOString() } : item) }; saveFiles(next); };
  const addCourse = () => { const name = newCourse.trim(); if (!name || courses.some(course => course.toLowerCase() === name.toLowerCase())) return; const next = [...courseNames, name]; setCourseNames(next); localStorage.setItem('personal-life-os-course-names-v1', JSON.stringify(next)); setNewCourse(''); };
  const exportCoursePack = () => { const blob = new Blob([JSON.stringify({ version: 1, courseNames: courses, files }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'personal-life-os-course-pack.json'; link.click(); URL.revokeObjectURL(url); };
  const importCoursePack = (file: File) => { const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)) as { courseNames?: string[]; files?: StoredFiles }; const importedNames = Array.isArray(parsed.courseNames) ? parsed.courseNames.filter(name => typeof name === 'string' && name.trim()) : []; const importedFiles = parsed.files && typeof parsed.files === 'object' ? parsed.files : {}; const mergedNames = Array.from(new Set([...courseNames, ...importedNames])); const mergedFiles = { ...files, ...importedFiles }; setCourseNames(mergedNames); setFiles(mergedFiles); localStorage.setItem('personal-life-os-course-names-v1', JSON.stringify(mergedNames)); localStorage.setItem('personal-life-os-course-files-v1', JSON.stringify(mergedFiles)); } catch { window.alert('Invalid course pack.'); } }; reader.readAsText(file); };
  return <div className="content uni-course-page">
    <div className="uni-course-page-header"><div><span className="pill purple">UNI COURSE</span><h2>Turn university courses into a steady rhythm.</h2><p className="muted">Plan preview, study, review, assignment and exam work in one focused place.</p></div><div className="uni-course-header-side"><span className="uni-course-count">{courses.length} course{courses.length === 1 ? '' : 's'}</span><div className="uni-course-add"><input value={newCourse} onChange={event => setNewCourse(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') addCourse(); }} placeholder="New course name"/><button className="primary" onClick={addCourse}>Add course</button></div><div className="uni-course-backup"><button className="secondary" onClick={exportCoursePack}>Export course pack</button><label className="secondary upload-button">Import pack<input type="file" accept="application/json" onChange={event => { const file = event.target.files?.[0]; if (file) importCoursePack(file); event.currentTarget.value = ''; }}/></label></div></div></div>
    <CourseTaskTemplates />
    <section className="course-materials"><div className="section-title"><div><span className="pill teal">COURSE MATERIALS</span><h3>Slides and lecture files</h3><span className="muted">Upload multiple PPT/PPTX decks for each course.</span></div><div className='course-material-filter'><button className={materialFilter === 'all' ? 'active' : 'secondary'} onClick={() => setMaterialFilter('all')}>All</button><button className={materialFilter === 'todo' ? 'active' : 'secondary'} onClick={() => setMaterialFilter('todo')}>Needs review</button><button className={materialFilter === 'reviewed' ? 'active' : 'secondary'} onClick={() => setMaterialFilter('reviewed')}>Reviewed</button></div></div>{courses.length ? <div className="course-material-grid">{courses.map(course => { const courseFiles = files[course] || []; const visibleFiles = courseFiles.filter(file => materialFilter === 'all' || (materialFilter === 'reviewed' ? Boolean(file.reviewedAt) : !file.reviewedAt)); return <article className="course-material-card" key={course}><div className="course-material-title"><b>{course}</b><small>{courseFiles.length ? `${courseFiles.length} file${courseFiles.length === 1 ? '' : 's'}` : 'No slide deck uploaded'}</small></div><div className="course-material-files">{visibleFiles.map(file => <div className="course-material-file" key={file.id}><span><b>{file.name}</b><small>{formatSize(file.size)}</small></span><button className="secondary" onClick={() => createStudyTask(course, file)}>Study task</button><button className="secondary" onClick={() => createReviewPlan(course, file)}>Review plan</button><button className="secondary" onClick={() => toggleReviewed(course, file)}>{file.reviewedAt ? 'Reviewed ' + file.reviewedAt.slice(0, 10) : 'Mark reviewed'}</button><a className="secondary" href={file.dataUrl} download={file.name}>Download</a><button className="secondary danger-action" onClick={() => remove(course, file.id, file.name)}>Delete</button></div>)}</div><label className="secondary upload-button course-material-upload">+ Upload PPT<input type="file" accept=".ppt,.pptx,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation" onChange={event => { const selected = event.target.files?.[0]; if (selected) upload(course, selected); event.currentTarget.value = ''; }}/></label></article>; })}</div> : <p className="muted">Create a course plan first, then its lecture materials will appear here.</p>}</section>
    <UpcomingCourseTasks toggleTask={toggleTask} />
  </div>;
}
