import { useMemo, useState } from 'react';
import Icon from './Icon';
import { useAppStore } from '../store/useAppStore';
import { DEFAULT_WEEKLY_ROUTINE, recommendRoutineSlot, routineTaskEnd } from '../domain/weeklyRoutine';
import type { WeeklyRoutineBlock } from '../domain/types';

const days=[{day:1,label:'Mon'},{day:2,label:'Tue'},{day:3,label:'Wed'},{day:4,label:'Thu'},{day:5,label:'Fri'},{day:6,label:'Sat'},{day:0,label:'Sun'}];
const kindLabel:Record<string,string>={hard:'Fixed',deep:'Deep work',focus:'Focus',light:'Light',admin:'Admin',exercise:'Training',meal:'Meal / nap',recovery:'Protected'};

export default function WeeklyRoutinePanel(){
  const{data,setData}=useAppStore();const routine=data.weeklyRoutine||DEFAULT_WEEKLY_ROUTINE;
  const[open,setOpen]=useState(true);const[editing,setEditing]=useState<WeeklyRoutineBlock|null>(null);const[message,setMessage]=useState('');
  const suggestions=useMemo(()=>data.tasks.filter(task=>task.status!=='done'&&!task.scheduledDate).slice(0,8).map(task=>({task,slot:recommendRoutineSlot(task,data.projects.find(project=>project.id===task.projectId),routine)})),[data.tasks,data.projects,routine]);
  const saveBlock=(next:WeeklyRoutineBlock)=>{setData(current=>({...current,weeklyRoutine:{...(current.weeklyRoutine||DEFAULT_WEEKLY_ROUTINE),blocks:(current.weeklyRoutine||DEFAULT_WEEKLY_ROUTINE).blocks.map(item=>item.id===next.id?next:item)}}));setEditing(null)};
  const schedule=(taskId:string)=>{const task=data.tasks.find(item=>item.id===taskId);if(!task)return;const project=data.projects.find(item=>item.id===task.projectId);let from=new Date(),slot=recommendRoutineSlot(task,project,routine,from);for(let tries=0;slot&&tries<8;tries++){const occupied=data.tasks.some(item=>item.id!==taskId&&item.status!=='done'&&item.scheduledDate===slot!.date&&item.scheduledStartTime===slot!.block.start);if(!occupied)break;from=new Date(`${slot.date}T12:00:00`);from.setDate(from.getDate()+1);slot=recommendRoutineSlot(task,project,routine,from)}if(!slot)return;const end=routineTaskEnd(slot.block,task.minutes);setData(current=>({...current,tasks:current.tasks.map(item=>item.id===taskId?{...item,scheduledDate:slot!.date,scheduledStartTime:slot!.block.start,scheduledEndTime:end}:item)}));setMessage(`${task.title} → ${slot.date} ${slot.block.start}–${end} · ${slot.block.title}`)};
  return <section className="weekly-routine-panel"><div className="weekly-routine-head"><div><span className="pill purple">WEEKLY ROUTINE</span><h2>Time allocation, not a rigid timetable.</h2><p>Fixed commitments stay protected. Research blocks can move; sleep, meals and recovery should not disappear.</p></div><button className="secondary" onClick={()=>setOpen(value=>!value)}><Icon name={open?'ChevronUp':'ChevronDown'} size={15}/>{open?'Collapse':'Open week'}</button></div>
    <div className="routine-foundations"><span><Icon name="Moon" size={14}/><b>Sleep</b> {routine.sleepStart}–{routine.sleepEnd}</span><span><Icon name="Coffee" size={14}/><b>Breakfast</b> optional · up to {routine.breakfastMinutes} min</span><span><Icon name="Dumbbell" size={14}/><b>Training</b> 5–6× weekly</span><span><Icon name="Shield" size={14}/><b>Rule</b> recovery is protected</span></div>
    {open&&<><div className="routine-week-grid">{days.map(({day,label})=><div className="routine-day" key={day}><h3>{label}</h3>{routine.blocks.filter(item=>item.day===day).sort((a,b)=>a.start.localeCompare(b.start)).map(item=><button key={item.id} className={`routine-block kind-${item.kind}${item.optional?' optional':''}`} onClick={()=>item.movable&&setEditing(item)} title={item.note||kindLabel[item.kind]}><time>{item.start}–{item.end}</time><b>{item.title}</b><small>{kindLabel[item.kind]}{item.movable?' · movable':''}</small></button>)}</div>)}</div>
    <details className="routine-rules"><summary>Scheduling rules</summary><ul>{routine.principles.map(item=><li key={item}>{item}</li>)}</ul></details>
    <div className="routine-suggestions"><div><h3>Unscheduled task suggestions</h3><p className="muted">Uses project links, task type and duration. It schedules only when you confirm.</p></div>{suggestions.length?suggestions.map(({task,slot})=><div className="routine-suggestion" key={task.id}><span><b>{task.title}</b><small>{slot?`${slot.reason} · ${slot.date} ${slot.block.start}–${routineTaskEnd(slot.block,task.minutes)}`:'Keep unscheduled until a suitable block opens'}</small></span><button className="secondary" disabled={!slot} onClick={()=>schedule(task.id)}>Use block</button></div>):<p className="muted">No unscheduled tasks need allocation.</p>}{message&&<p className="time-message">{message}</p>}</div></>}
    {editing&&<div className="modal-backdrop" onMouseDown={()=>setEditing(null)}><form className="create-modal routine-edit" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();saveBlock(editing)}}><div className="modal-head"><div><span className="pill teal">MOVABLE SOFT BLOCK</span><h2>{editing.title}</h2></div><button type="button" className="modal-close" onClick={()=>setEditing(null)}>×</button></div><label>Day<select value={editing.day} onChange={event=>setEditing({...editing,day:Number(event.target.value)})}>{days.map(item=><option value={item.day} key={item.day}>{item.label}</option>)}</select></label><div className="form-two"><label>Start<input type="time" value={editing.start} onChange={event=>setEditing({...editing,start:event.target.value})}/></label><label>End<input type="time" value={editing.end} onChange={event=>setEditing({...editing,end:event.target.value})}/></label></div><label>Note<textarea rows={2} value={editing.note||''} onChange={event=>setEditing({...editing,note:event.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={editing.end<=editing.start}><Icon name="Save" size={14}/> Save template block</button></div></form></div>}
  </section>;
}
